### ISSUE TITLE
Milestones/ Roadmap for the next version?

### ISSUE THREAD

**Issue by ashokgelal** [PrismLibrary/Prism#10]
It'd be very helpful for some of us who'd like to contribute to know the features that we'd like to add/fix/remove in the next version. May be discuss them as well (like #8) before we actually start implementing new features.

**Comment by brianlagunas** [comment]
The first major change has already been made and that was the complete restructure of the Prism Library.  We have move MVVM (commanding, and ViewModelLocator), logging, and event aggregation (PubSubEvents) into the core Prism.dll which is now a PCL.  We changed all namespaces to remove Microsoft.Practices, and renamed the other WPF components to Prism.Wpf, Prim.Wpf.Unity, and WPF.Prism.Mef.  There have been a number of minor fixes in the WPF version of Prism that will soon be published in a change log.  We have started adding support for Xamarin.Forms.  We will need a lot of ffedback here, as Xamarin.Forms is a new tech, and this is completely new guidance.  We will be publishing a preview on NuGet shortly.  We will also be looking at Windows 10 very soon and seeing what makes sense there.  Brian Noyes will be leading the effort there.

**Comment by bartlannoeye** [comment]
@brianlagunas one of the most appealing things of Prism for WinRT was that it was much more lightweight than Prism for WPF, while still giving enough guidance. It's one of the main reasons we started using it over other Win8 MVVM frameworks, because most frameworks tend to grow larger over time increasing the learning curve for new team members. It's also feedback that we've heard quite often when mentioning we were using Prism "wow, isn't that too bloated/heavy/complex", as people had Prism for WPF in mind.

So I think for every existing Prism feature not available in WinRT (soon Win10) yet, careful consideration should be made whether to add it or not, independent to the fact that WinRT/Win10 _can_ support it.

Both versions of Prims have their pros and cons and it's up to you (the owners) and us (the community) to find the best way to go forward. A roadmap per platform would be useful for this I think.

**Comment by Michael-DST** [comment]
While we're talking about platforms, I did want to open the discussion about the naming of projects and see if I am off on my own island in this regard (yet again \*smile\*).

The whole new platform thing is, well, new, so I think we're all learning along here.

I am wondering if it makes more sense to categorize namespaces along by technology/concern then platform.  So:

\<Product\>.\<Concern\>.\<Platform\>

Example: Prism.Unity.Windows

The other implied suggestion here is to use "Windows" in place of Wpf, as I feel it is a stronger brand name, and then can also be extended in the case of Windows 10/Universal/One:

Prism.Mef.Windows.Universal or
Prism.Mef.Windows.One

(This is assuming that "Windows One" is the new API name being announced at //build.)

Part of the reasoning behind this suggestion is that I feel this is consistent with Xamarin's approach (which I personally will be adopting, as well):
Xamarin.Forms.Platform.<Platform>

(We would remove platform to make it more succinct).

So in total:
Prism (PCL)
Prism.Windows (WPF Components)
Prism.Forms (Xamarin.Forms Components)
Prism.Unity (PCL)
Prism.Unity.Windows (Unity WPF Components)
Prism.Unity.Windows.One (Unity Windows 10 Components)
Prism.Unity.Forms (Unity Xamarin.Forms Components)
Prism.Mef (PCL)
Prism.Mef.Windows (MEF WPF components)
Prism.Mef.Windows.One (MEF Windows 10 Components)
Prism.Mef.Forms (MEF Xamarin.Forms Components)

Just another thought that's been kicking around my head and had to get it out. :)  Thanks for any consideration as always.

**Comment by brianlagunas** [comment]
features that are needed will be added as issues.  For now, the Navigation needs some serious attention and dog-fooding to make sure we get it right.

**Comment by tomcrusader** [comment]
Working with Xamarin.Forms 1.4.2.6359 (stable) and targeting WinRT+Windows Phone with a Universal project, I can't really get this to work out of the box.

Xamarin PCL's need to target **Windows Phone 8.1** with this update (i.e not Silverlight). With the new PCL profile (111) Prism.Forms can not be installed using NuGet.

![](https://developer.xamarin.com/guides/cross-platform/xamarin-forms/windows/getting-started/Images/pcl.png)

Only the Windows (8/RT) project is allowed as target when installing Prism.Forms.

Same thing for the dependency **Unity** (3.5.1404.0). There is however a *prerelease* of Unity that has updated targets.

Unity 3.5.1405-prerelease can be added to all my projects; PCL, Windows and Windows Phone 8.1.

With a little help from ReSharper I can now in fact add the proper references to my Xamarin PCL projects, even if I can't add the package with NuGet!

**Prism, Prism.Forms, Prism.Forms.Unity** are easily referenced from the NuGet folder
*Prism.Forms.5.6.1-pre1\lib\portable-win+net45+wp80+MonoAndroid10+MonoTouch10+Xamarin.iOS10*
So why does the NuGet package don't have this target?

Now as a Xamarin developer I'm used to hickups like this.
But the main issue is that even with these workarounds I can't get *Navigation* to work. Keeps giving me "null reference" errors. Really missing the navigation callback from Prism Silvelight/WPF right now.

![prism navigation error](https://cloud.githubusercontent.com/assets/396545/7665962/7de16ba0-fbd0-11e4-8bf5-819f87277ea7.JPG)

Going to demo my architecture for other Xamarin developers on Wednesday 2015-05-20 and would really like to tell them that this will in fact work. Because Prism rocks, it is known.

I used Brian's tutorial:
http://brianlagunas.com/first-look-at-the-prism-for-xamarin-forms-preview/

**Comment by brianlagunas** [comment]
This is because Prism.Forms  is in pre-release itself and is not built against Xamarin.Forms 1.4.2.6359, but rather 1.4.0.6341 which does not have the Windows Store and Phone 8.1 support.  Since you need it so quickly, I suggest downloading the source and upgrading the Xamarin.Forms target, then make any modifications you need for your demo.

**Comment by tomcrusader** [comment]
Good idea, that should have been my next logical move. Usually it doesn't even compile when Xamarin is incompatible, but I'll try this out if you think it'll work just by updating the references.

**Comment by tomcrusader** [comment]
Cloned Prism, built Prism.Forms and Prism.Unity.Forms and replaced my references.

Now the viewmodel for my main view isn't resolved any more?
If I manually resolve the ViewModel in my Bootstrapper that works:
```csharp
        protected override Page CreateMainPage()
        {
            var view = this.Container.Resolve<HomeView>();
            var vm = this.Container.Resolve<HomeViewViewModel>();
            view.BindingContext = vm;
            return view;
        }
```
However, getting the NavigationService is now an issue. 
- Going by the tutorial it looks like it would be magically resolved by simply putting a public property for INavigationService in your ViewModel. This property is null for me, even if i decorate it with `[Dependency]`
- Trying to import INavigationService in MainViewModel gives error: "Prism.Navigation.INavigationService, is an interface and cannot be constructed. Are you missing a type mapping?". 
- Importing IUnityContainer and trying to `Resolve<INavigationService>` gives same error.
- Looking through the UnityContainer's Registrations NavigationService is indeed missing.

Feel free to contact me directly.
FB: https://www.facebook.com/thomas.hagstrom
E-mail: thomashagstrom (at) outlook.com

**Comment by brianlagunas** [comment]
You probably have an issue with your ViewModelocator code, because nothing would have changed just by recompiling.  Make sure you are following the default naming conventions.

For INavigationService your ViewModel needs to implement INavigationServiceAware.  It won't work by asking for it from the container because it isn't registered with the container.

**Comment by tomcrusader** [comment]
Ok, so I've been digging through this, testing on Win RT and WP 8.1. Can't see any Android output in the Prism project so I skipped that.

My ViewModelBase already implemented `INavigationAware`, so adding `INavigationServiceAware` doesn't do anything.

![hliviewmodelbase](https://cloud.githubusercontent.com/assets/396545/7688688/e5ca18d4-fda6-11e4-84a6-21eed7344b10.JPG)

With ViewModelLocator, do you refer to the **Bootstrapper** implementation? 

```csharp
using HLI.TimeNodes.Data;
using HLI.TimeNodes.Mobile.ViewModels;
using HLI.TimeNodes.Mobile.Views;
using Microsoft.Practices.Unity;
using Prism.Unity;
using Xamarin.Forms;

namespace HLI.TimeNodes.Mobile
{
    public class Bootstrapper : UnityBootstrapper
    {
        protected override Page CreateMainPage()
        {
            var view = this.Container.Resolve<HomeView>();
            var vm = this.Container.Resolve<HomeViewViewModel>();
            if (view.BindingContext == null)
            {
                // This shouldn't be needed
                // Issue: both vm.NavigationService and this.NavigationService are null??
                view.BindingContext = vm;
                vm.NavigationService = this.NavigationService;
            }

            return view;
        }

        protected override void RegisterTypes()
        {
            // TODO: SettingsViewModel (plugin)
            this.Container.RegisterType(typeof(IDatabaseManager), typeof(DatabaseManager));
            ////this.Container.RegisterType<HomeViewViewModel>();

            this.Container.RegisterTypeForNavigation<SettingView>();
            this.Container.RegisterTypeForNavigation<TimeLogListView>();
            this.Container.RegisterTypeForNavigation<TimeLogView>();
            this.Container.RegisterTypeForNavigation<HomeView>();
        }
    }
}
```
The suspect thing is that I need **Microsoft.Practices.Unity** here in order of using Resolve with type arguments, i.e `<HomeView>` (in general I like my tutorials with full using's for clarity).
Removing that usage doesn't help with the issue though.

That's all I've done locator wise, other than adding `prism:ViewModelLocator.AutowireViewModel="True"` to the views.

'Course checked and double checked conventions:

![timenodes mobile pcl xamarin](https://cloud.githubusercontent.com/assets/396545/7688730/4716ed7e-fda7-11e4-8a27-8089b94eac50.JPG)

Thanks for all your above and beyond help so far - developing is not at its best as a solo adventure.

Sincerely // Thomas

**Comment by brianlagunas** [comment]
We haven't done any testing for WinRT/WP, but just for fun try creating a view called HomePage, and then a HomePageViewModel and see if it works.  We made a change to the convention in the latest code base to Ignore the "View" from a view name to eliminate the ugly "ViewViewModel" that is created.  For example; HomeView has a HomeViewViewModel.  With the change it should only be HomeView and HomeViewModel.

**Comment by brianlagunas** [comment]
I am thinking that we should reconsider this convention change and perhaps revert it back to how it was.

**Comment by tomcrusader** [comment]
Well that worked like a charm, on the last night an everything - what's up with that? :+1: 

The newly added Home**Page** resolves with BindingContext, which in turns has resolved NavigationService.

![eureka](https://cloud.githubusercontent.com/assets/396545/7710673/ae003982-fe65-11e4-9f1f-8fff809d4f1a.JPG)

So what I now did was to conclude:

1. From HomePage I can navigate to self and for example Home**View**.
The latter will however not have a ViewModel resolved.

2. Doing a quick rename of views + VMs to match this updated pattern... **WORKS*** Prism with Xamarin for Windows RT, let's go, folks!

The only thing I can't do is resolve INavigationService in a view by taking it in the constructor, but logic belongs to ViewModel anyway so I'm moving it there.

So many thanks, Prism forever (using it for Silverlight with MEF at my day job) and XOXO

**Comment by brianlagunas** [comment]
Right!  The NavigationService is not a globally available service because navigation in Xamarin.Forms is dependent on the Page the VM is associated with.  Therefore, we don't register the INavigationService with the container because there is no single navigation stack to use, and we don't want to give the impression there is.

Also, you didn't have to rename your views.  You could have just changed the convention for the VML :0).  Like I said, we will probably change the convention back to how is was due to breaking every app the currently uses the old convention and having the "ViewViewModel" is so arbitrary, it's not worth the breaking change and confusion (just like you experienced with your view names).

This is why it is still in Preview :0)

**Comment by tomcrusader** [comment]
Everything Xamarin is preview. That's why we're having another meetup here in Stockholm tomorrow, to work together and learn from eachother's mistakes :)

**Comment by tomcrusader** [comment]
Do you, by the way, mean by specifying view name when registering type for navigation?
```csharp
this.Container.RegisterTypeForNavigation<SettingView>(ViewNames.SettingPage);
```

**Comment by brianlagunas** [comment]
No, I mean change the naming convention for how the ViewModelLocator finds your ViewModels.  You can use what ever convention you want.

Check out: http://brianlagunas.com/getting-started-prisms-new-viewmodellocator/

Look under the "Change those Nasty Conventions" section that explains how to do it.
