### ISSUE TITLE
Consider re-license to MIT, following the Microsoft led projects

### ISSUE THREAD

**Issue by bytesoftly** [PrismLibrary/Prism#1007]
Not a technical issue.
I was wondering if there were any plans to re-license the source under MIT to provide consistency with other code bases (such as Xaramin Core, [LICENSE](https://github.com/xamarin/Xamarin.Forms/blob/master/LICENSE)) your awesome library is often used with? I have been unable to use this super project on more than one occasion because it is not MIT but have been using Xaramin Forms because it is.

Thanks for all your work, a super project.

**Comment by brianlagunas** [comment]
I'm no licensing expert, but there may be an issue with that.  When this project was OSS'd by Microsoft, it was done under the current license.  I don't think I can just change the licensing to something else without carrying forward the original license.

**Comment by bytesoftly** [comment]
Right yes okay. I'm also no licensing expert but have noticed Microsoft have been incredibly receptive to re-licensing under MIT. Would it be too much trouble to ping the guys at MS who OSS'd PRISM about MIT re-licensing, it would certainly green-light the code for a large number of projects at our company and likely others too?

**Comment by brianlagunas** [comment]
I have reached out to Microsoft to see if this would be allowed.  I'll update this thread when I hear something.

**Comment by brianlagunas** [comment]
Just wanted to update this thread.  We are making progress on this.  I am working with the .NET Foundation to make this happen.  Since we had PR's before Prism became part of the .NET Foundation, we will need to get permission from everyone that submitted a PR prior to Aug 30, 2015 to change the license.  Essentially, they will need to sign our CLA in order for us to proceed.  If they don't, then we can't make the change.

**Comment by bytesoftly** [comment]
Super! Thanks for asking, whether or not they decide to relicense.

**Comment by brianlagunas** [comment]
This has been approved.  The next v7.0.0 release will be MIT
