### ISSUE TITLE
Prism double notification after InteractionRequest.Raise

### ISSUE THREAD

**Issue by ArtemPinkevich** [PrismLibrary/Prism#1010]
### Package info

- Platform: WPF
- Prism version: 6.2.0
- Windows 10 pro

### Repro steps

__Problem:__ when NotificationRequest is called, two notification windows appear in sequence. (look the gif)
![doublenotification](https://cloud.githubusercontent.com/assets/5462509/24575880/967bcdd6-16db-11e7-940e-690bb79a523c.gif)

__Source problem:__ two Viewes have the same ViewModel in DataContext parameter. So these two Viewes are subscribers of the InteractionRequest.Raised event.

__My resolve:__ the InteractionRequest was overwritten. As for now Raised event has only one subscriber per one time period. (look the [project archive ](https://drive.google.com/file/d/0B87VosOMZm-TZmhpS0Z0YUlQZjQ/view))

__Question:__ is there a way to resolve the issue with a more right way?

P.s. Duplicate of this issue is in [stackoverflow](http://stackoverflow.com/questions/42990204/prism-double-notification-after-interactionrequest-raise)

**Comment by dvorn** [comment]
Certainly, InteractionRequest was not designed for multiple event subscriptions because the callback action passed into Raise method will be called multiple times and that will break any program logic.

I think the right way to handle this is to throw when somebody subscribes second time. 

On the other hand, I do not think this is a big issue: just do not subscribe twice.  Do not use the same view model for multiple views, or if you do that, make sure only one of them have InteractionRequestTrigger.  And do not define multiple InteractionRequestTriggers for the same InteractionRequest.

**Comment by brianlagunas** [comment]
@dvorn is correct. This is an issue with your application architecture. Basically, don't do what you are doing. Sharing the same VM instance across multiple views is a code smell, and should be a very rare occurrence.
