### ISSUE TITLE
[Win 10 UAP] SplitView and Prism

### ISSUE THREAD

**Issue by diego2k** [PrismLibrary/Prism#102]
Hi, 
currently the usage of the SplitView control in conjunction with Prism is problematic. Prism for UAP doesn't offer regions. So the only possibility is to use frames and to manipulate the Window.Current.Content like jorisdebock did in his example (https://github.com/jorisdebock/Prism/tree/master/Samples/Windows10/ExampleApp1). But this doesn't work if the App starts after "suspend and shutdown", because the OnLaunchApplicationAsync method is't called and so the Window.Current.Content can't be set to a Shell-view. To fix this a method which is called in the case that _isRestoringFromTermination == true must be added in the PrismApplication.OnLaunched method. 
Perhaps I have overlooked something but at the moment there is no support for the SplitView control with Prism?
Thanks.

**Comment by briannoyes** [comment]
Hi,
You are not the only one asking for this. We definitely have it in our backlog for UWP, but have a few other things that are higher priority at the moment. As you mention, we will have to look into whether it makes sense to add some kind of support for SplitView before we add regions into Prism for UWP, or whether it just makes sense to wait until we do that so that then we can just do it as a RegionAdapter. I'll add some more info here once we get to looking into it.

**Comment by jorisdebock** [comment]
@diego2k with one of @veccie updates there is not a method called "CreateShell" and with a simple change to my example

'''
protected override UIElement CreateShell(Frame rootFrame) =>
            new ShellPage(rootFrame);
'''

i also updated the rest of the example to work with the latest prism changes and nuget packages

**Comment by diego2k** [comment]
Works for me, thanks.

**Comment by JohnTasler** [comment]
That's a reasonable solution that takes care of that problem.
