### ISSUE TITLE
Contribute: `Prism.SimpleInjector.Forms`

### ISSUE THREAD

**Issue by WonkiDonk** [PrismLibrary/Prism#1087]
I'd like to contribute a SimpleInjector implementation for Xamarin Forms (`Prism.SimpleInjector.Forms`). I realise there's already a `Prism.SimpleInjector`, but this is not compatible with Xamarin Forms. I'm happy to do the work.

**Comment by dansiegel** [comment]
@WonkiDonk just spoke with @brianlagunas about this. He is open to adding Simple Injector for Prism Forms. I would encourage you to sign up for the [Slack channel](https://prismslack.herokuapp.com/) so that you can discuss this and get some assistance from Brian and I. I would also encourage you to take a look at my [SimpleInjector branch](https://github.com/dansiegel/Prism/tree/feature/SimpleInjector-XF) where I have most of the work done for you. The branch will need to be updated to NetStandard and still needs verification that it actually works :)

**Comment by WonkiDonk** [comment]
https://github.com/PrismLibrary/Prism/compare/master...WonkiDonk:features/1087-SimpleInjector?expand=1

**Comment by bartlannoeye** [comment]
You'll have to hit 'Create pull request' if you want the code to be reviewed and merged at some point. We can see the diff, but can't comment.

**Comment by brianlagunas** [comment]
It looks like this effort has stalled.  I will close this until the effort picks back up or the community would like to revive it.
