### ISSUE TITLE
DirectoryModuleCatalog use of ReflectionOnlyLoad forces an exact match to dependent assemblies

### ISSUE THREAD

**Issue by BrettJaner** [PrismLibrary/Prism#110]
From http://compositewpf.codeplex.com/workitem/9567 posted by strtdusty.

Assembly.ReflectionOnlyLoad does not inspect the publishers policies, but requires that the exact version be present on the system. Assembly.Load DOES inspect the publishers policies and will allow a binding redirect.
  
 The DirectoryModuleCatalog does a ReflectionOnlyLoad in order to determine which modules are available in the module directory. The use of ReflectionOnlyLoad puts a restriction on module loading that any referenced assemblies must be the same version that it was built against. Even though during a normal Assembly.Load it may successfully bind to a more current version. This is true with .NET core assemblies like System.Core.
  
 DirectoryModuleCatalog could change to use Assembly.Load instead of ReflectionOnlyLoad. The ModuleCatalog uses a temporary AppDomain and disposes it after discovering all modules, so there shouldn't be a concern of assemblies being left loaded. I have done this in a local copy of Microsoft.Practices.Prism.dll and this seems to correct the problem.

I have also created a custom DirectoryModuleCatalog based off of strtdusty's suggestion to fix this issue.  If  a pull request would be entertained, I'd be happy to submit.

**Comment by brianlagunas** [comment]
ReflectionOnlyLoad  only loads an assembly so that it can be examined, and does not allow it to be executed.  It also doesn't try to load any dependencies the assembly being loaded may have (depending on the assembly being loaded, this could be a massive dependency tree).  This means that ReflectionOnlyLoad also comes with a performance benefit.

Unfortunately, this is not something we will be changing.  If you require the behavior you describe, you will need to contnue to use your custom DirectoryModuleCatalog.
