### ISSUE TITLE
inject INavigationService in a view 

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1117]
Hi
i wanna inject INavigationService in a ContentPage class but when i want to navigate to this page i get this error.

> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Tipax.Xamarin.Views.CustomBarcodeScannerView' can be invoked with the available services and parameters:
Cannot resolve parameter 'Prism.Navigation.INavigationService navigationService' of constructor 'Void .ctor(INavigationService)'.

I inject my page in RegisterTypes method like this =>
`            Container.RegisterTypeForNavigation<CustomBarcodeScannerView>();
`
i also inject my INavigationService in my page like this.
`    public class CustomBarcodeScannerView : ContentPage
    {
        INavigationService _navigationService;
        public CustomBarcodeScannerView(INavigationService navigationService)
        {`

- Platform: xamarin forms shared project
- Prism version: 6.3.0
- Xamarin version (if applicable): 2.3.4.224

**Comment by brianlagunas** [comment]
You shouldn't inject the Nav Service in a page.  This is not enabled by default. If you are sing MVVM, then navigate from your VM. So either use the NavigationService from the VM via a property, or delegate the navigation to the VM directly.

**Comment by dansiegel** [comment]
I might add that barcode scanning should be looked at as a service for better testability of your code rather than as a View you need to handle in your application. This is such a common scenario in apps I do for clients that I have [open sourced](https://github.com/dansiegel/BarcodeScanner) this and provided it as an easy to use [NuGet](https://www.nuget.org/packages/BarcodeScanning.Service).
