### ISSUE TITLE
Prism Xamarin Forms / Dryioc - Bindable Map HELP!

### ISSUE THREAD

**Issue by kekovespa** [PrismLibrary/Prism#1130]
Hi,
I'm trying to use a bindable map control (TK.CustomMap) on my Xamarin.Forms Prism with Dryioc project.
I found pretty easy to work with Prism and Dryioc ,thanks for that guys, but my app needs a map and I find out that the Xamarin.Forms.Maps official package do not use MVVM pattern and it's not bindable.

I need your help! I can't make TK.CustomMap works with Prism and I don't find any other sample that work with it.

Thanks!

**Comment by brianlagunas** [comment]
This is not related to Prism.  The map is not MVVM compatible, so it will not work with the MVVM pattern in general unless you implement the feature yourself.  Possible an attached property?

**Comment by dansiegel** [comment]
You might want to check this out... The Xamarin.Forms.GoogleMaps library provides everything Xamarin.Forms.Maps does and several other features... the Bindings extension provides you the ability to use Maps with MVVM patterns. 

https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings

**Comment by kekovespa** [comment]
Thanks, I will give it a try. If I'm successful I will come back and post about it.

**Comment by olivertech** [comment]
Using Xamarin.Forms with Prism, which are Netstandard, do not work with those packages... Both of them uses Fullframework and when you try to get each one, a message is throwed saying:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Xamarin.Forms.GoogleMaps 2.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Xamarin.Forms.GoogleMaps 2.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
