### ISSUE TITLE
[UWP] SplitView, Page.DataContext and INavigationService.Navigate

### ISSUE THREAD

**Issue by veccie** [PrismLibrary/Prism#114]
Quick question... What determines what the DataContext of a Page should be if I do not set one?

While working on my SplitView navigation project I found a rather odd behavior.

I have a ShellPage.xaml(ShellPageViewModel) which holds the SplitView. To test the navigation I created a few Pages (Page1Page.xaml, Page2Page.xaml, etc.) that I could navigate to. No ViewModels, just plane default Pages.

The odd thing is that if you use INavigationService.Navigate and navigate to for example Page1Page.xaml then ShellPageViewModel.OnNavigatedTo gets executed. If I navigate to a page where I've actually created and set a ViewModel then there's no problem.

When debugging FrameNavigationService.NavigateToCurrentViewModel and looking at this line:

`var newViewModel = newView.DataContext as INavigationAware;`

Then I can see this:
```
newView = Page1Page
newViewModel = ShellPageViewModel
```

But how? Is this somehow related to the fact that the SplitView's underlying ViewModel is ShellPageViewModel?

**Comment by briannoyes** [comment]
This just because of how DataContexts work in XAML in general. Anytime you set a DataContext on an element, that DataContext becomes the DataContext of all child elements that do not have another DataContext set (explicitly, or through template binding, or through ViewModelLocator). Since your pages that you are putting in the SplitView don't set a DataContext, they are part of the visual tree of that entire screen, so the DataContext of their parent cascades down to them.

The reason the navigation methods on the parent get called is because the way the navigation service is set up, whenever a nav happens on a frame, the service is notified and it tries to cast the DataContext of the current and next Page to INavigationAware. As long as that cast succeeds (which it will in your case because the current DataContext for the Page is the inherited one from the shell page), it will call the OnNavigateTo and OnNavigateFrom methods on that object.

I'd recommend any page that you are going to place in a Frame and do navigation have a ViewModel, even if there is nothing meaningful to put on it at the time. It will both fix this problem and it just keeps the symmetry that all navigation pages are Views in the MVVM sense, and all MVVM Views have their corresponding ViewModel. There are sometimes special cases that you intentionally want to let a child view just inherit its parent's viewmodel, but those should be rare because they are really breaking the encapsulation of the pattern.

**Comment by veccie** [comment]
Ok, I was not aware of how XAML deals with DataContexts by default, but thanks for clarifying.
