### ISSUE TITLE
Exception when using IPageDialogService to show alert in OnNavigatedTo method

### ISSUE THREAD

**Issue by mo-kml** [PrismLibrary/Prism#1144]
Hi there
im developing a xamarin forms shared project and i have this problem. im trying to use pageDialogService to show an alert in some cercemstances in OnNavigatedTo method but i get this error.

> Exception:
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>

**Comment by brianlagunas** [comment]
My guess is that you are doing this when the app first starts.  This exception occurs because there is no application MainPage.  You can easily test this by checking `Application.Current.MainPage` in the method.  

I also bet that you have a deep link in your nav path such as "NavPage/MainPage".  Because the nav stack must be built backwards, the INavAware methods are called on MainPage prior to the NavPage being set as the application MainPage.

You cannot show a dialog without the existence of a MainPage.  You will need to rethink your approach to ensure a page exists prior to showing the dialog.  You may want to listen for the Appearing event and then invoke a command in your VM to show the dialog.
