### ISSUE TITLE
Proposal: De-couple ValidatableBindableBase for PCL/.NETStandard Model Libraries

### ISSUE THREAD

**Issue by prof79** [PrismLibrary/Prism#1149]
### Proposal/Feature Request

I have a netstandard1.x portable library using `Prism.Core` via `project.json` for product item models. This library should be consumed by a Windows 10 app (we know UWP has no native validation) thus requiring `Prism.Windows.Validation`.

The model library cannot/should not refer to `Prism.Windows` which would require UAP.

I would like to expand on request #625 in a more concrete, low-effort, non-breaking way based on the status of Prism 6.3 by copying platform-agnostic code to the `Prism.Core` package. This may also touch on #45.

To decouple things I propose (referring to namespaces/type names):

- Introduce a new interface `Prism.Validation.IBindableValidator`
- make `Prism.Windows.Validation.BindableValidator` inherit from `IBindableValidator`
- copy `Prism.Windows.Validation.IValidatableBindableBase` to `Prism.Validation`
- copy `Prism.Windows.Validation.ValidatableBindableBase` to `Prism.Validation`
- mark `Prism.Windows.Validation.IValidatableBindableBase` and `Prism.Windows.Validation.ValidatableBindableBase` with `ObsoleteAttribute`
- change `Prism.Validation.ValidatableBindableBase` to refer to the interface, not implementation of `IBindableValidator`

Thus we could use `ValidatableBindableBase` in PCL or netstandard libraries for our models yet still use the fine standard implementation of `Prism.Windows.Validation.BindableValidator` under Windows 10. Compatibility with existing projects would be ensured (copying classes not moving). Those who desire could even implement their own `IBindableValidator` for other platforms.

I'm just a hobbyist developer so please forgive me if I'm missing some points in the greater scheme of things.

If you approve and don't have the time I could try prepare a sample implementation and pull request for this.

### Package info

- Platform: UWP and .NETStandard/WPF interoperability
- Prism version: 6.3.0
- Xamarin version (if applicable): not tested/researched
- Windows 10 SDK version (if applicable): Anniversary 14393

### Repro steps

Try adding/accessing `ValidatableBindableBase` from PCL or .NETStandard library project.

Regards,
Markus

**Comment by brianlagunas** [comment]
Thanks for the suggestion.  If we were to create such interfaces in the core Prism assembly, every platform Prism supports would need to implement it.  We cannot add a class or interface to the core for just a single platform.  Another issue is that I am not convinced that validation is something Prism should be responsible for (exactly why WPF and XF do not have it built in).  There are many validation frameworks already available for various platforms, I'm not sure creating another one is beneficial or a problem space Prism should be trying to solve.

Luckily, this is very easy to workaround.  Simply create your own ValidatableBindableBase in your .NET standard project and use that instead of Prim for UWP's implementation.  YOu can use Prism's source code to get you started.  There is a preview of Prism.Core 7.0 with .NET Standard support on our MyGet server now.  Check out the Readme for it's location.
