### ISSUE TITLE
Error after upgrade of System.Diagnostics.DiagnosticSource 4.4.1, System.Text.Encoding.Codepages 4.4.0 and System.ComponentModel.Annotations 4.4.0

### ISSUE THREAD

**Issue by IsmailHassani** [PrismLibrary/Prism#1163]
after updating some nuget packages I get the following error: https://imagebin.ca/v/3axmKw4KxDQq
The packages updated are: System.Diagnostics.DiagnosticSource 4.4.1, System.Text.Encoding.Codepages 4.4.0 and System.ComponentModel.Annotations 4.4.0

Stacktrace:
`at Prism.DryIoc.DryIocBootstrapper.Run(Boolean runWithDefaultConfiguration) at ISynergy.App.OnStartup(StartupEventArgs e) in D:\Projects\I-Synergy\src\I-Synergy.Shared\Application\App.cs:line 201 at System.Windows.Application.<.ctor>b__1_0(Object unused) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

Platform: WPF with .net 4.7 with the latest Prism library 6.3.0

When I go back to the 4.3.0 version the error is gone and I can run the application.

**Comment by brianlagunas** [comment]
This is not an issue with Prism so much as it is with DryIoC.  If you look at the dependencies of DryIoC they rely on v4.3.0.  The NuGet packages bring in the required dependencies.  No need to upgrade.

**Comment by IsmailHassani** [comment]
Thank you Brian. I will pass this to Maksim.

**Comment by dadhi** [comment]
I am not sure what is deal with this upgrade. If you go to [DryIoc nuget page](https://www.nuget.org/packages/DryIoc.dll) Dependecies section, you'll see that the Net Standard 1.0 is indeed dependent on >= 4.3 BCL packages. But in your case the Full .NET version is used. And anyway it is __>=4.3__ and not just __4.3__.

Looking at some popular packages like [Json.net](https://www.nuget.org/packages/Newtonsoft.Json/) does not bring too much difference. The only notable thing is dependency on meta-package of NETStandard.Library instead of individual System.Blah... But this is also just for .Net Standard and not for Full .NET.
