### ISSUE TITLE
Change Prism.Interactivity.PopupWindowAction.CreateDefaultWindow to virtual

### ISSUE THREAD

**Issue by darinclarkdev** [PrismLibrary/Prism#1165]
Currently if you wish to provide your own implementation of DefaultConfirmationwindow and DefaultNotificationWindow you must override GetWindow in the child class. If CreateDefaultWindow was virtual like CreateWindow is you could override just the 2 methods and leave GetWindow in the base class.

**Comment by brianlagunas** [comment]
We accept PR's :)

**Comment by roberszr** [comment]
Hi Brian,
I'm new on using Prism (6.3), and I've got a strange behavior when using PopupWindowAction . I would try to explain; I've got a module in which there is a third party library for a softphone (VoIP library). The problem is that if i show a PopupWindowAction,  the third party library, VoIP library, gets blocked until i close the PopupWindow...Am I doing something wrong? Is the only way to do that? Is the third library wrong? I don't know what to do because i can't use PopupWindow on, for example, an incoming call...
Best rergards

**Comment by brianlagunas** [comment]
I don't know as I am not familiar with your third party plugin or hw it works.

**Comment by darinclarkdev** [comment]
Maybe launch a second shell instead of using a PopupWindowAction. Check out Infragistic's reference apps that emulate word, excel and outlook. They use prism with some advanced designs.

**Comment by brianlagunas** [comment]
Done
