### ISSUE TITLE
UWP Feature Request and Roadmap?!

### ISSUE THREAD

**Issue by HesamKashefi** [PrismLibrary/Prism#1172]
Hi, I want to know that whether there is any plan to update Prism.Windows with new features or not? specially now that it seems there is no focus on Prism.Windows .
Here is my list of requests : 

1. Adding Frame object to the NavigationService
2. Adding NavigationEvents to NavigationService
3. Adding InteractionRequest and InteractionRequestTriggers
4. Adding Support for Modules (like WPF)
5. Adding a Navigation Service Factory ! This can be used to generate NavigationService for a particular Frame... I don't know if there is a solution for this right now or not!
6. Adding DOCUMENTATION (Currently there is only for WPF and Xamarin, does this imply that UWP version is going to be obsolete ?).

And I want to know if there is any Roadmap or not?

Thanks in advance.

**Comment by brianlagunas** [comment]
I would suggest adding these requests individually so they can be properly tracked.  Otherwise they will be lost once this issue is closed, which is going to be right now :)

There is no road map at this time.  UWP is not a focus at this time as we are currently focused on the Xamarin.Forms platform.  When XF has been stabilized and our core features are in place, with docs completed, we will begin to re-evaluate the UWP platform.  Honestly, this is not going to happen anytime soon.  This effort will easily begin in 2018.

If you feel this timeline is not acceptable, we would appreciate if you would help us implement these features by submitting PR's for all of these requests.  The best way to move something forward is to participate in its development.

**Comment by brianlagunas** [comment]
This is a community driven project. If the community doesn't drive it or contribute, it won't get done.
