### ISSUE TITLE
Upgrade to CommonServiceLocator 2.0.1

### ISSUE THREAD

**Issue by devdeer-alex** [PrismLibrary/Prism#1211]
CommonServiceLocator implemented a breaking change in [Version 2.0.1](https://github.com/unitycontainer/commonservicelocator/commit/908a30f0f4c036d1ded0c0967fa3a7ae823aa5ce). 

Prism should use the newer package because runtime errors will occur when a project updates the CommonServiceLocator to the newer version. 

Be aware that hey changed their namespace from `Microsoft.Practices.ServiceLocation` to `CommonServiceLocator`.

**Comment by bartlannoeye** [comment]
Upgrading CommonServiceLocator would limit UWP apps to Fall Creators Update only (.netstandard 2.0).

**Comment by devdeer-alex** [comment]
I see. So how about implementing it completely inside of Prism. CSL is not very difficult to rebuild and I think it could be improved a bit also.

**Comment by brianlagunas** [comment]
Prism for WPF is the only platform that requires CommonServiceLoctor.  There is no removing it from there.  We are also not adding CSL as part of Prism.

**Comment by devdeer-alex** [comment]
OK. Thanks.

**Comment by dationguyen** [comment]
Hi Guys,
Is it possible to upgrade to CommonServiceLocator 2.0.1 in newest xamarin.form ?

**Comment by brianlagunas** [comment]
Prism for XF doesn't use CommonServcieLocator.  That is a dependency if you are using unity.  Since the current versin of Prism 6.3 is based on Unity 4, you cannot upgrade unity or it's dependency on CSL.  We are looking at upgrading to Unity 5 for Prism 7.

**Comment by a-einstein** [comment]
This indeed seems a BREAKING change.

When I try to run, I get an exception as Prism.Mef.Wpf 6.3 seems to be still referring Microsoft.Practices.ServiceLocation instead of CommonServiceLocator. Check the Fuslogvw below. Apparently this is a bug.

Is there a way to get around this?
Otherwise please fix this.
Thanks.

------------------------------------------------------------------------------------------
*** Assembly Binder Log Entry  (03/11/2017 @ 21:54:53) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  P:\projects\RCS\shopping\clients\WpfShop\RCS.WpfShop\bin\Debug\RCS.WpfShop.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///P:/projects/RCS/shopping/clients/WpfShop/RCS.WpfShop/bin/Debug/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = RCS.WpfShop.exe
Calling assembly : Prism.Mef.Wpf, Version=6.3.0.0, Culture=neutral, PublicKeyToken=40ee6c3a2184dc59.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: P:\projects\RCS\shopping\clients\WpfShop\RCS.WpfShop\bin\Debug\RCS.WpfShop.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///P:/projects/RCS/shopping/clients/WpfShop/RCS.WpfShop/bin/Debug/Microsoft.Practices.ServiceLocation.DLL.
LOG: Attempting download of new URL file:///P:/projects/RCS/shopping/clients/WpfShop/RCS.WpfShop/bin/Debug/Microsoft.Practices.ServiceLocation/Microsoft.Practices.ServiceLocation.DLL.
LOG: Attempting download of new URL file:///P:/projects/RCS/shopping/clients/WpfShop/RCS.WpfShop/bin/Debug/Microsoft.Practices.ServiceLocation.EXE.
LOG: Attempting download of new URL file:///P:/projects/RCS/shopping/clients/WpfShop/RCS.WpfShop/bin/Debug/Microsoft.Practices.ServiceLocation/Microsoft.Practices.ServiceLocation.EXE.
LOG: All probing URLs attempted and failed.

**Comment by brianlagunas** [comment]
@a-einstein This isn't a bug.  Prism 6.3 is built against CSL 1.3.  You cannot upgrade the CSL to 2.0, because Prism is not built against that version.  The only way to get this to work is for Prims to upgrade it's dependency on CSL and release an update.  This will be done as part of the up coming 7.0 release.

**Comment by a-einstein** [comment]
I think the same problem occurs when I tried using 1.4. So in the end I had to backtrack to 1.3.

Thanks for your clarification Brian. 

But I wonder if there is a way of making this clear in advance. Now I was prompted by NuGet to update,  then ran into problems. It took me a lot of time to isolate that problem to CommonServiceLocator, checking everything, trying to work around the problem, get Fuslogvw working, and finally stumble upon this issue.

So I hope there is some other way.

**Comment by brianlagunas** [comment]
Assembly dependencies work the same, nothing changes when using Nuget.  This is the problem with Nuget.  NuGet will always show you the newest version, even if it is a dependency of something else.  NuGet should be smart enough to know that it is a dependency and not show you an upgrade.  This will get you into trouble.

**Comment by a-einstein** [comment]
Well, I meant if there is some way of expressing the restriction of Mef.Wpf 6.3 of CommonServiceLocator  <=1.3. That would have saved me a lot of trouble.
I have been looking into the restrictions, but I do not think that was able to give me the needed information.

**Comment by brianlagunas** [comment]
We will never allow the ability to upgrade major versions (example going from 1.3 to 2.0) as that would be a risk of breaking binary compatibility.  Going forward we will at least allow minor updates (1.4, 1.5, 1.6, etc)

**Comment by brianlagunas** [comment]
Done with PR #1240
