### ISSUE TITLE
[XF] Issue using DelegateCommand in a ListView ContextAction MenuItem on UWP

### ISSUE THREAD

**Issue by sschutten** [PrismLibrary/Prism#1267]
### Package info

- Platform:UWP
- Prism version: 6.3.0
- Xamarin version (if applicable): 4.7.10.22
- Windows 10 SDK version (if applicable): Fall Creators Update (10.0.16299.15)
- Xamarin.Forms: 2.4.0.74863

### Repro steps

I've created a simple app to reproduce the issue. It can be found [here](https://github.com/sschutten/context-actions-bug-verify). The sample shows two identical ListViews side-by-side, one bound to a Command vs one bound to the DelegateCommand. Both bind to the exact same ItemSource. The latter is showing the issue.

I have an issue where on UWP I would see empty ListView rows, while on Android and iOS the details are visible. I've boiled it down to the use of a ContextActions MenuItem on the ViewCell of the ListView. The MenuItem has a binding to a Command and CommandParameter. I use the generic DelegateCommand in order to pass in the object through the CommandParameter. If the non-generic DelegateCommand is used or Prism's DelegateCommand is replaced with Xamarin.Forms' Command the details are shown on UWP. Since it's working with the Xamarin.Forms' Command I suspect somthing odd is happening in the DelegateCommand that freaks Xamarin.Forms out.

**Comment by brianlagunas** [comment]
Actually, this is a bug in Xamarin that they have never fixed.  The issue is that when the page is first being created, the parameter being passed to the command is actually the `MainPage`, which causes an exception inside DelegateCommand because it does not match your `T`.  You can see this by adding a CanExecute to the DelegateCommand and make the parameter type of `<object>`, then set a break point in the method as the app starts up. You will see the parameter is actually MainPage for each list item.

Xamarin had to implement a work-around in the command to validate if the type was the same in order to get around this.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Command.cs#L27

We can't implement this work-around because Prism's DelegateCommand is used on multiple platforms and not just XF.  So you have a coupe of options.

1. Don't use DelegateCommand for this specific use-case

1. Use `DelegateCommand<object>` and cast the parameter to Person if not null `var p = person as Person`

1. Create a custom command that derives from DelegateCommand and implement the same workaround

**Comment by sschutten** [comment]
Thanks for responding this quickly and providing the options. I tried your suggestion with adding the CanExecute method and indeed see the `MainPage` being passed.
