### ISSUE TITLE
Grace as a new IOC Container for Xamarin Forms (and WPF)

### ISSUE THREAD

**Issue by rinoandrejohnsen** [PrismLibrary/Prism#1273]
Hi all!
I have a question. Will the team accept a project for the Grace IOC container in Prism XF?

I have done some simple benchmarks and it seems to be about twice as fast as DryIoc, so I believe that it has a place since the speed is important for some apps. I have done all the work necessary, since I will at least use it myself, but wondering if it is something to share.  

P.S. I will also take a hold on a WPF project with Grace if that is required to get this through the program.

**Comment by brianlagunas** [comment]
I would be hesitant to accept another container, especially one I have never heard of.  The issue is that once we bring it into Prism, I have to support it.  While I try to rely on the community to support the other containers we have, no one really has stepped up tot the plate to do so.

Also, if we do add a container, it must be added to the other platforms as well.  I want to get away from platforms support different containers.  It also would not be added to the Prism Template pack unless it was supported on WPF and XF.  This means that it must support the features of WPF as well as XF.

You can submit your PR or review, but there is no guarantee of when, or if, it will be accepted as it will take time to properly review and test. If we release it without testing then it will provide a bigger support burden on me.

**Comment by rinoandrejohnsen** [comment]
That sounds fair enough to me. I can understand your hesitancy towards possible getting more work on your plate. I will however create a pull request for it, so it can be reviewed and at least have a chance of getting trough. I am putting a bit of pressure on it since I have used some time to find a new go-to-ioc-container after Unity slowed down. Grace have really peaked my interest and I think sharing this great piece of software is the right thing to do.

I will present a pull request and you and your team can deal with it according to your possibilities and whishes. I will also follow it through if you have feedback or changes you want to see down the line.

**Comment by brianlagunas** [comment]
I would also caution you that this container seems new to GitHub, has very small number of downloads, and doesn't appear to have an active community behind it.  Adoption may be way too low for us to even consider adding it.

**Comment by rinoandrejohnsen** [comment]
Noted, I shall embalm myself with idea that chances are pretty low for this passing during my programming, but for the time being I am finding a great joy with this, so I will try to keep some wind in my sails.

**Comment by brianlagunas** [comment]
Sounds good. Enjoy!
