### ISSUE TITLE
Documentation for NavigationResult.Result is unclear

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#128]
It is a nullable bool, but when is it true, when is it false and when is it null? This should probably be replaced by an enum or by a SuccesfulNavigationResult, a FailedNavigationResult and a CancelledNavigationResult class with further info.

**Comment by brianlagunas** [comment]
I don't think we will change the data type of the return value since this would break many people and require more than just a find/replace type of fix.  We are currently trying to decide the best way to host our documentation, and when we figure that out, we will update the documentation to be more explicit in describing this behavior.

**Comment by brianlagunas** [comment]
were you able to get a null result?  I am not able to create the conditions necessary to have the Result property return null.
