### ISSUE TITLE
Create Project and Item template for Prism.Wpf

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#13]
We will be looking at creating project template for Prism for WPF.  We need to start getting ideas about what kind of project and item templates to make.

Here are some ideas for Project Template:
Stubbed out starter application
Stubbed Module

Item Templates:
UserControl with ViewModelLocator.AutowireViewModel set to true
UserControl with ViewModel and the ViewModelLocator.AutowireViewModel set to true
XAML Module Catalog
App.config Module Catalog

Not sure about the names of these templates.  Also, I would love to hear other ideas of templates we should support.

For example, should we provide a base Module class, or a base ViewModel class in our project templates?

**Comment by bartlannoeye** [comment]
Prism for Windows Runtime already had a nice set of templates, we could use it as a reference for the WPF templates: https://visualstudiogallery.msdn.microsoft.com/2a6c37e4-fe9a-4a93-baae-a9bce4cf60c7. For more detail on each template check http://www.davidbritch.com/p/prism-for-windows-runtime.html.

I like the fact that there's a project template with and without Unity, as I'm mostly using Autofac as IoC container.

**Comment by brianlagunas** [comment]
@bartlannoeye Good idea on the Blank templates.  Also, you wouldn't happen to have created a Prism.Autofac assembly for your AutoFac support, would you?  I think that would be a great contribution to Prism :)

**Comment by bartlannoeye** [comment]
I've plugged Autofac in Prism for Windows Runtime before, but never in WPF. I'll give it a shot, nothing to loose and lots to win if we can add it :)

Maybe you could split up issue #15 to a separate one for each IoC container? That way a pull request can close a single issue. Feel free to assign me the Autofac one then.

**Comment by mos8580** [comment]
Very interested in this! :+1:

**Comment by gep13** [comment]
Is this something that could be made "easier" using SideWaffle:

http://sidewaffle.com/

i.e. rather than going to the length of creating your own VSIX extension, build on the existing framework, to add the item and project templates?

There are YouTube videos on how this can be done here:

https://www.youtube.com/watch?v=naY3jbBNNgY&feature=youtu.be

and here:

https://www.youtube.com/watch?v=NChUqnArTrI&feature=youtu.be

Just a thought.

**Comment by briannoyes** [comment]
Good point @gep13 I use Sidewaffle for a lot of web templates. Have never built out templates on Sidewaffle, so not sure how much easier it really is. I think @britchdavid might jump in there and do this for us since he created some before for the p&p Prism team. Would leave that decision up to him.

Only thing I don't like about SideWaffle is that unless you get into customizing it you end up with the clutter of a lot of templates (project and item) that you probably don't use and just adds noise to the environment.

**Comment by gep13** [comment]
@briannoyes I think you might have got David's Twitter handle, did you mean @davidbritch

>@briannoyes said..
Only thing I don't like about SideWaffle is that unless you get into customizing it you end up with the clutter of a lot of templates (project and item) that you probably don't use and just adds noise to the environment.

That's a good point.  I wonder if there is a way to turn on/off which templates are activated.

**Comment by davidbritch** [comment]
Does SideWaffle include the ability to call into custom code when creating a solution from a template? That was required for the Prism WinRT project templates.

**Comment by gep13** [comment]
Pass, that would be a question for @sayedihashimi... Sayed?

**Comment by sayedihashimi** [comment]
@briannoyes 
>Only thing I don't like about SideWaffle is that unless you get into customizing it you end up with the clutter of a lot of templates (project and item) that you probably don't use and just adds noise to the environment.

I'm guessing you mean that's the result when you fork+add to the existing SideWaffle templates. If you are creating your own template pack instead of forking SideWaffle you can create a new VSIX Project and then add the [TemplateBuilder](https://www.nuget.org/packages/TemplateBuilder/) nuget package. Using that project you can create a .vsix which contains just your templates. SideWaffle uses TemplateBuilder for the template creation process in this same way. In many cases the name SideWaffle is used to refer to TemplateBuilder as well. The best resource is https://msdn.microsoft.com/en-us/magazine/mt147242.aspx.

@davidbritch 
>Does SideWaffle include the ability to call into custom code when creating a solution from a template? That was required for the Prism WinRT project templates.

SideWaffle/TemplateBuilder builds on top of the existing VS template system. To call custom code during project/item creation you'd use a custom wizard. Templates with wizards is not a problem for SideWaffle/TemplateBuilder. I have some [rough notes on custom wizards](https://github.com/ligershark/side-waffle/wiki/How-to-use-a-custom-wizard). If you have any issues let me know.

**Comment by briannoyes** [comment]
Thanks for the info @sayedihashimi . I knew that I could customize the set of templates that get installed by forking the code and tweaking things as you said and did start going down that path one time. But in the end since I didn't need to create any templates of my own, I gave up after a short while, and decided to instead just keep downloading the vsix that is on the home page for SideWaffle and then deal with mild annoyance at seeing templates I don't care about. :)

**Comment by pellea** [comment]
Is there any (partial) template available yet ? (or any sample for WPF)

**Comment by brianlagunas** [comment]
Not yet. We haven't gotten there yet.  We are still working on features.

**Comment by mtaulbee** [comment]
The command snippet ideas are very similar to those used in MVVM Light Toolkit.
I added the summary comments for this forum, but I don't have them in the snippets I use.

[prismProp.txt](https://github.com/PrismLibrary/Prism/files/52026/prismProp.txt)
[prismVM.txt](https://github.com/PrismLibrary/Prism/files/52027/prismVM.txt)
[prismDelCmd.txt](https://github.com/PrismLibrary/Prism/files/52030/prismDelCmd.txt)
[prismDelCmdCanExecute.txt](https://github.com/PrismLibrary/Prism/files/52029/prismDelCmdCanExecute.txt)

**Comment by brianlagunas** [comment]
The first version of this has been released. Please test it out and let me know if you run into any issues:

https://visualstudiogallery.msdn.microsoft.com/e7b6bde2-ba59-43dd-9d14-58409940ffa0

Right now there are no WPF templates, but they are coming.

**Comment by mtaulbee** [comment]
Just did a quick smoke test for the Window and UserControl templates, works as expected. Took me a second to realize you added a Prism node under C#, I like it, very nice touch. Testing was done using VS 2015 Update 1.

**Comment by brianlagunas** [comment]
@mtaulbee Thanks for testing them out. Now I need to start adding a project template for WPF.  Multi-project ProjectTemplates take forever to create and test.  Besides a full project templae, I am also thinking of a "Module" project template too.

**Comment by brianlagunas** [comment]
@mtaulbee Did you try the ViewModel item template too?  Thoughts?

**Comment by mtaulbee** [comment]
I didn't see the ViewModel template under wpf. I have a few ideas though...
A module template is high on my list.
The other would be a wizzard for the UserControl and ViewModel though. The wizzard would allow us to inherent from a base class of some sort.

**Comment by brianlagunas** [comment]
The ViewModel Template is just under the **Prism** category since it is used on all platforms.  Yeah, I need to learn how to write a custom wizard that lets you create a View ad ViewModel while placing them in the appropriate Views/ViewModels folders, but also give you the ability to change the folders.  It gets complicated :)

**Comment by mtaulbee** [comment]
Nice! Just tested the VM, works as expected.
I think VS has an interface called IWizard that can be implemented for wizards? It's been a few years since I've made project or item templates though......
If we can somehow add the ability to derive the UserControl and VM from a different base class, I'd use those item templates all the time. 
Good work so far though!

**Comment by motisch** [comment]
I think it would be nice to have a complete solution template with the projects liker so:
App.Shell;
App.MainModule;
App.ServiceInterfaces;
App.Services;
App.Graphics;(Maybe)
App.Api;

And item templates as pairs of view and viewmodel.

**Comment by brianlagunas** [comment]
Those templates coming soon.
