### ISSUE TITLE
[UWP] OnNavigatedTo and OnNavigatingFrom for shell in case of a SplitView

### ISSUE THREAD

**Issue by diego2k** [PrismLibrary/Prism#131]
Hi, 
currently the solution for the SplitView is to give the PrismApplication another Frame which should be used for the navigation. The Problem is the shell may also have a state which has to be saved in case of a suspension. Because the shell is always visible the OnNavigatingFrom and OnNavigatedTo should be called every time a suspension happens. 
I think at the moment the only possibility to save the state of the shell is to use the Resuming and Suspending event in the App.xaml.cs which is not a really nice solution ... 
Thanks

**Comment by tomzorz** [comment]
What about PrismApplication calling those two methods directly on suspend/resume (only if they are available of course), and than putting the state into the SessionStateService.SessionState dict? Seems like a simple solution, but please try to poke holes in my idea.

**Comment by briannoyes** [comment]
No, not a crazy idea @tomzorz, I had the same thought as an easy workaround for now is just to inject ISessionStateService into the corresponding ViewModel and/or View to write what is needed in and out of there. The hitch with that is that I don't think you wouldn't get the persistence of the navigation stack history (forward/back state) of the outer frame. Once we get to doing regions in UWP we would make sure to cover this scenario because regions can always be nested in other regions in WPF and they each maintain their own nav stack. But I think it is a ways off until either of us Brians will have time to get to that since this is not part of our day job.

**Comment by diego2k** [comment]
@tomzorz I think this would work. I implemented a workaround in a similar way. 
Additionally, in my first post I wrote that OnNavigationFrom and OnNavigationTo should be in the shell, but now I'm not sure ... the shell does not navigate, it's the shell ... just a thing to think about.

**Comment by tomzorz** [comment]
@diego2k Yup, that makes sense. Although I can imagine a few scenairos where the shell changes around, so we shouldn't rule it out completely.

What about introducing ILifecycleAware (naming not set in stone :smile:), and checking if the shell object returned by CreateShell implements that. If it does, then wire it up inside the resuming/suspending cycle.

**Comment by briannoyes** [comment]
ok, I'm going to leave this issue open for now as a reminder that we need to do some work around making Prism for UWP play nice with SplitView, but removing it from the first release milestone

**Comment by tjones0808** [comment]
hey guys, any update on this?

**Comment by brianlagunas** [comment]
Nothing yet, sorry.  We are slammed with our day jobs right now.  We hope to find some free time soon.

**Comment by tjones0808** [comment]
Alright no worries. Thanks for the update

**Comment by brianlagunas** [comment]
This should be fixed with the new Template10 merge.
