### ISSUE TITLE
Consider deprecating/removing Uri based navigation

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#132]
This is leftover functionality from the Silverlight days and is not actually used by the WPF implementation.

**Comment by briannoyes** [comment]
Because it was released as Prism 4 for WPF and Silverlight and was the only way to pass parameters until Prism 5, lots of WPF apps use it too. We would break too many apps by removing it and I think some people might actually prefer using the query string style of passing the arguments instead having to create other objects in the dictionary of parameters now supported.

Personally I don't think it should be deprecated, but would like to hear other opinions since we have deprecated and removed other capabilities that had replacement approaches (i.e. CompositePresentationEvent). But in those cases it was more of a 1 for 1 replacement, not an alternative  style.

**Comment by brianlagunas** [comment]
There are a lot of apps that actually use this feature.  Even I have some that do.  We will not be removing this support.
