### ISSUE TITLE
Not able to find override InitializeShell() method

### ISSUE THREAD

**Issue by acharyabhaskar** [PrismLibrary/Prism#1358]
I have been following puralsight tutorials by Brain Lagunas of Prism

On the 2nd Chapter demo for Creating a Unity Shell, Demonstrated to create a method override method called InitializeShell(), but the reference I am using this method is not available as override.

The references I have used are
1. Microsoft.Practices.Composite v2.0.1.0
2. Microsoft.Practices.Composite.Presentation v2.0.1.0
3. Microsoft.Practices.Composite.UnityExtensions v2.0.1.0

Please let me know either specifically which version of DLL I should use, I have a restricted environment so can not connect to nuget site for download, thus if you can assist me the equivalent of InitializeShell in this DLL would be a better option. 

Bhaskar

**Comment by brianlagunas** [comment]
You need to provide more information. The issue template asked a number of question that would help guide you to provide the information we need in order to properly support you.  I am assuming you are trying to use WPF.  This means you need to make use you are using version 6.3.

Since you can't use Nuget, you can download the assemblies here: https://github.com/PrismLibrary/Prism/releases/tag/Prism.v6.3.0

Also, the assemblies you provided are not Prism assemblies and are not supported by Prism.
