### ISSUE TITLE
INavigationService can't be injected into contructors outside main application and no method RegisterSingletonForNavigation

### ISSUE THREAD

**Issue by Erave** [PrismLibrary/Prism#1366]
I have noticed that if you create a view inside Prism MainApp and you want INavigationService as contructor parameter there is no problem. Unity resolve correctly INavigationService instance. But If you do the same into a Module, you can't navigate into you registered View (using registerNavigation) because Unity can't resolve INavigationService !
This is very strange because my UnityContainer owns this instance.

Have you an idea for this issue ?

Another question, we come from an Prism3 WPF project using MEF. MEF by default uses singleton object and we think it is a good idea to avoid memory leak. 
In Unity, you can use Register or RegisterSingleton ... Good we can choose. But for Navigation there is only Register. 
I had a look at Prism Source Code and there is no implementation for **RegisterSingletonForNavigation**. This can be very useful. No ?

**Comment by brianlagunas** [comment]
This is by design.  You cannot inject the INavService into anything other than a ViewModel that is associated with a Page.

No, navigation in XF is not based, and cannot be based, on a singleton.  Using singletons has nothing to do with avoiding memory leaks, and in fact can be a source of memory leaks if hooking into events.

**Comment by brianlagunas** [comment]
Also, having singleton based Pages in XF is very dangerous.  For example, let's assume your navigation stack looks like this:

"NavigationPage/ViewA/ProductList"

if you registered ViewA for navigation as a singleton, and then tried to navigate from the ProductList page to "ViewA" again, an exception would be thrown because it already exist in the navigation stack.  If you really want to do this you can, you'll just have to implement it yourself using the existing source code as a guide.

**Comment by Erave** [comment]
Thanks brian for your reply.
Ok for singleton. I understand.

By the way, about my INavService, I tried to create a Page/ViewModel into main App, then it works and after moved this Page/ViewModel into a module and there it fails. In both case my ViewModel is associated to a View (ContentPage)

**Comment by brianlagunas** [comment]
This tells me you aren't following the namespace/naming conventions. Just register the VM with the View and you'll be fine.  RegisterForNavigation<Viewm VM>

**Comment by Erave** [comment]
Ok I just start a new project from scratch with default view into module and add INvaigationService into constructor. No problem with that, it should be a problem with my project. I don't see anything wrong at the moment but I will find ;-)
Thank you for your help
Eric
