### ISSUE TITLE
xamarin.forms TabbedPage switching tabs with navigating to child

### ISSUE THREAD

**Issue by krzysiekkania7** [PrismLibrary/Prism#1367]
Hi.

I have TabbedPage with Children wrapped into NavigationPages. When trying to switch tabs and go to next page with 
**_await NavigationService.NavigateAsync($"BlnakApp1:///Main?{KnownNavigationParameters.SelectedTab}=Tab2/Content");_**
 app goes blank. It navigate to requested page but doesn't display anythig.  Only on ios

Version: 7.0.0.396
Xamarin.Forms: 2.5.0.122203

Sample:
https://github.com/krzysiekkania7/TabbedPageSample

**Comment by brianlagunas** [comment]
I have confirmed this as a bug within Xamarin.Forms.  I have reproduced this in a non-Prism application and have submitted it to the XF GitHub issues for the Xamarin team to fix.  I will update this issue when they have fixed their bug.

https://github.com/xamarin/Xamarin.Forms/issues/2562

**Comment by JoeDurand3** [comment]
It looks like they moved that issue to inactive - I hope it doesn't sit there too long.

**Comment by dansiegel** [comment]
Adding a Help Wanted tag to this issue. This is actually a Xamarin.Forms issue, however it is not likely to be worked on by the Forms team anytime soon. Anyone from the community who has capacity is encouraged to help out and tackle the issue xamarin/Xamarin.Forms#2562

**Comment by almirvuk** [comment]
I've left the comment on the main issue on XF repo to increase attention, hopefully they will try to fix it in some next releases. 😞

**Comment by WarBorg** [comment]
I saw they placed it back in the backlog a couple of days before

BTW @brianlagunas in the above sample I noticed something weird, using the sample above updated to the latest Xam Forms version, on iOS, if I click on the GO button from the second tab "Categories" a navigation bar appears for the "Content" page which is to be expected since the tab is wrapped in a Navigation page but if I do this on the app start:

```C#
await NavigationService.NavigateAsync($"Main?{KnownNavigationParameters.SelectedTab}=Tab2/Content");
```

the "Content" page has no navigation bar, is this related to the Xam Forms bug or should I report it as a bug or am I missing something ?
