### ISSUE TITLE
Use container in ConfigureModuleCatalog

### ISSUE THREAD

**Issue by joelweiss** [PrismLibrary/Prism#137]
The container is initialized after the ModuleCatalog is configured. this doesn't allow you to use the container in `ConfigureModuleCatalog()`, Maybe move the up `ConfigureContainer()` in the initialization

example use case: 
```csharp
protected override void ConfigureModuleCatalog()
{
    foreach (var module in Container.GetAllInstances<IModule>().Cast<ModuleBase>())
    {
        var moduleType = module.GetType();
        ModuleCatalog.AddModule(new ModuleInfo
        {
            ModuleName = moduleType.Name,
            ModuleType = moduleType.AssemblyQualifiedName,
            DependsOn = new System.Collections.ObjectModel.Collection<string>(module.DependentTypeNames.ToList()),
            InitializationMode = module.InitializationMode
        });
    }
}
```

**Comment by briannoyes** [comment]
We could consider this, but would need to make sure there would not be any side effects that might break existing apps by doing do. If I understand what you are trying to do there, you want to use what is registered with the container to determine what modules load instead of just configuring them through Prism's normal mechanisms.

The problem with the code you showed there is that the ConfigureModuleCatalog method is intended for just what its name implies - reading in or programmatically setting the configuration of what modules are supposed to be loaded. The instancing of modules happens later, when the ModuleManager uses that catalog and creates a ModuleInitializer to load and initialize each module. 

So if you did what you are showing here, the call to GetAllInstances would create an instance of all the modules registered with the container, just to get metadata about them to shove into the module catalog and then it would be releasing those instances, then the module manager would kick in and create new instances which would then be used to actually call Initialize... not a very efficient approach unless the modules are registered with the container as singletons, and that goes against the model of Prism that module classes are just a transient object that is created and used to initialize the module, but then goes away.

With the existing code the "right" way to do it would be to implement your own ModuleManager, which gets called after the container is initialized, and have it figure out what modules to load from the container and not even use the module catalog.

**Comment by brianlagunas** [comment]
I am in agreement with @briannoyes.  I am closing this until substantial evidence in support of this request can be made.

**Comment by joelweiss** [comment]
Thanks @briannoyes for the detailed reply, will work around it.
