### ISSUE TITLE
[UWP] ViewModel instances not disposed after navigation

### ISSUE THREAD

**Issue by oliverluethi** [PrismLibrary/Prism#1377]
We encountered a problem with our Prism UWP application. Everytime we navigate to the same page, a new instance is created and the old one is held in memory and is not disposed. This will cause crashes because global events are fired several times.

We're using the Prism.Unity NuGetPackage 6.3.0. The application is pretty basic. We're using the NavigationService for navigating through the pages. Our pages and usercontrols are bound to the viewmodels with `prismMvvm:ViewModelLocator.AutoWireViewModel="True"` in XAML.

I've seen some threads about similar problems and the solution was to add an RegionBehaviour with Regions, but as far as I know, Prism UWP doesn't support regions in current release.

I think the problem is in ViewModelLocator and NavigationService, because registering the viewmodels with `Container.RegisterType` and with a different LifetimeManager did not help or at least has no effect. 

Sample Application
1.) Execute application
2.) Navigate several times between Test1 and Test2
3.) Hit "RaiseEvent" for executing a global event.
4.) All instances logging their hashcode

[App1.zip](https://github.com/PrismLibrary/Prism/files/1759877/App1.zip)

**Comment by brianlagunas** [comment]
Just because you navigate away from a page does not means it and all its resources are disposed of immediately.  Prism has zero control over when the UWP framework decides to dispose of any objects in memory. You should either filter your subscriptions, unsubscribe from them or make sure you have proper code in your event handlers to check for nulls as to not throw exceptions.  If your app crashes because of events being fired then you need to start looking into your implementation of those methods, because simply executing events multiple times will not cause your app to crash. ViewModeLocator odes nothing but create the VM and assign the DataContext.  So regardless of how you set the DataContext, you will have the same issue.

**Comment by oliverluethi** [comment]
@brianlagunas As far as i know, the lifetime manager should handle how long instances are held in memory before they're released to garbage collector. Some lifetime managers are holding a strong reference to them `ContainerControlledLifetimeManager` and some lifetime managers are holding a weak reference to the classes they create `ExternallyControlledLifetimeManager.` Probably its more an Unity rather than a Prism topic I guess.

But I understand your point and for that reason I've created a behavior class for handling loaded / unloaded events from the page / usercontrol who checks for an interface. On the loaded / unloaded event this behavior calls functions form that interface. The unloaded function will unregister global events or eventhandlers from the view and / or viewmodel.

Thanks for your explanation

**Comment by brianlagunas** [comment]
While containers can keep objects in memory, they don't control when the GC is called or even when objects will be freed from memory.
