### ISSUE TITLE
[XF] CreateTab and SelectedTab not supported in NavigationParameters class

### ISSUE THREAD

**Issue by JunkyXL86** [PrismLibrary/Prism#1391]
### Description

I created a small sample solution using the latest NuGet version of Prism.Forms 7.0.0.396 that reproduces the bug(s).
Navigating to a TabbedPage using NavigationParameters to create and select a tab does not really work unless you specify the parameters within the query string. If you use the overload with the NavigationParameters param, they are not respected or it even fails with a NullReferenceException.

### Steps to Reproduce

The parameters ->
```
var parameters = new NavigationParameters();
parameters.Add(KnownNavigationParameters.CreateTab, nameof(PageA));
parameters.Add(KnownNavigationParameters.CreateTab, nameof(PageB));
parameters.Add(KnownNavigationParameters.SelectedTab, nameof(PageB));
```

Navigation ->
```
// Nothing happens
NavigationService.NavigateAsync("TabbedPage", parameters);
```

```
// Works as expected
NavigationService.NavigateAsync("TabbedPage" + parameters);
```

Note the '+' which concatenates the parameters to an entire query string.
Whereas the first approach using the parameter overload does not work.

Using a more complex scenario it even throws an exception:
```
// throws NullReferenceException
NavigationService.NavigateAsync("MyMasterDetailPage/NavigationPage/TabbedPage", parameters);
```

Just using the query string works:
```
// Works as expected
NavigationService.NavigateAsync("MyMasterDetailPage/NavigationPage/TabbedPage" + parameters);
```

### Expected Behavior

Exact same navigation behavior like using parameters within the query string.

### Actual Behavior

Navigation parameters in query string are treated differently.

### Basic Information

- Version with issue: Prism.Forms 7.0.0.396
- Last known good version: -
- Xamarin.Forms version: 2.5.0.122203
- IDE: Visual Studio 2017 (15.5.6)

### Reproduction Sample

[NavParams.zip](https://github.com/PrismLibrary/Prism/files/1802072/NavParams.zip)

**Comment by brianlagunas** [comment]
I have a couple of concerns about implementing this.  First, there would be an immediate limitation of not being able to deep link into an app that has multiple TabbedPages.  This is because both TabbedPages would read the NavParams class and create tabs based on those values.  This could be very bad, and there is no way to control it.

Another problem is the amount of code churn and logic that would need to be added to the NavigationService to support this.

The safest and most reliable way to do this would be to keep it in the query string.  However, if there is an overwhelming request from the community, we can add it, but will have to note the known limitation which many people won't know about until they actually run into the problem and open an issue here :)

Thoughts?

**Comment by brianlagunas** [comment]
After thinking about this more, I have decided not to suppor this for the reasons I outline in my previous comment. However, you can still use the NavigationParameters class if you like, you just have to provide them inline in the URI like you outlined in your example.
