### ISSUE TITLE
This Prism vs Prism.Mvvm, Prism.StoreApps, etc

### ISSUE THREAD

**Issue by kfinke70** [PrismLibrary/Prism#141]
I've been working on a Windows 10 UWP app.  I've been attempting to use the nuget packages mentioned above, including Unity and a UnityAppBase.  I kept running into issues with navigation and other things. I assumed it was because I was blending a combination of projects, but now I'm starting to suspect some of the things I was using weren't meant to work together.
I went back to the well and started looking around, and it led me here.  Now, we use EntLib and Prism at work with great success.  I saw the announcement of Prism going open source and in your hands.  I was happy for the news, but didn't connect them together with what I needed.
So, even though I hate to open this as an issue, it's really just a question.  Is this the place to be?  Seems like the Core part has been released to nuget, and WPF, but not Windows (UWP)?  But, I can go through git (already cloned) and reference from there for now?
Again, sorry I opened this as an issue.  What's the right way to have asked this question?
Kevin

**Comment by briannoyes** [comment]
You are in the right place, and we are using this for general questions for now. 

What you want for Win10 UWP development is the Prism for UWP part of the code base here. We don't have NuGet packages out there yet because we are pre-release, but hope to get a release out early next week. For now you can download the code and use the Prism, Prism.Windows, and Prism.Windows.Unity libraries as those have all been ported from the Prism for Windows Runtime release a couple years ago for Windows 8.1 to Windows 10 UWP.

**Comment by bartlannoeye** [comment]
There was a release from Patterns & Practices for Windows 8 Store apps (v1.0) and a release for 8.1 Universal apps (code for both on https://prismwindowsruntime.codeplex.com/) which is on NuGet as Prism.StoreApps and works together with Prism.Mvvm. But as you've noticed this release is indeed not compatible with those packages.
