### ISSUE TITLE
Do not require Window as base type for Shell

### ISSUE THREAD

**Issue by BadMadDev** [PrismLibrary/Prism#1413]
### Description

In Prism 7 for WPF the return value of method CreateShell from class PrismApplication is of type Shell.
This breaks making applications not using a sub class of Window for the main window. 
In my case, I am using RadWindow from Telerik which is not a subclass of Window.

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

You should be able to return DependencyObject again.

### Actual Behavior

CreateShell return a Window.

### Basic Information

- Version with issue: PRISM 7 for WPF
- Last known good version: PRISM 6.3 for WPF
- IDE:

**Comment by brianlagunas** [comment]
Sounds like Telerik made a bad decision creating a Window control that's not a Window.  At this time we are not planning to change the return type of CreateShell.  However, you can still use your RadWindow.  Just return null in CreateShell, and then override OnInitialized to show your RadWindow. Or continue to use the bootstrapper, since it's not going anywhere anytime soon.

**Comment by karelkral** [comment]
I agree with BadMavDev - this is unfortunate change. You can return null from CreateShell and initialize your own Shell in OnInitialized, but you must duplicate some code from PrismApplicationBase.
```
protected override Window CreateShell()
{
	// because RadWindow is not Window, cannot create here.
	// https://github.com/PrismLibrary/Prism/issues/1413
	return null;
}

protected override void OnInitialized()
{
	ShellWindow shellWindow = Container.Resolve<ShellWindow>();
	shellWindow.Show();
	MainWindow = shellWindow.ParentOfType<Window>();

	// there lines was not executed because of null Shell - so must duplicate here. Originally called from PrismApplicationBase.Initialize
	RegionManager.SetRegionManager(MainWindow, Container.Resolve<IRegionManager>());
	RegionManager.UpdateRegions();
	InitializeModules();

	base.OnInitialized();
}
```

**Comment by njsent** [comment]
We have a legacy winforms app with hundreds of forms that we are attempting to slowly convert to wpf by newing up instances of wpf windows (I know, it's awful).  The app does not have a wpf 'shell' per se so we return null in the CreateShell method.  However, this bombs with a null reference exception which occurs when MainWindow.Show() is invoked (since MainWindow is null) from PrismApplicationBase.OnInitialized().  

Do we have any recourse other than implementing Bootstrapper, or do we need to roll back to 6.3?

**Comment by brianlagunas** [comment]
@njsent follow the code snippet above. Return null from `CreateShell`, and then override `OnIitialized`.

**Comment by njsent** [comment]
I appreciate the response Brian but that won't work unfortunately.  We don't have a specific wpf window that is launched at startup since it's a winforms app.  The user may not even open a wpf window during their session since there are hundreds of winform 'forms' and only a few wpf windows.  We are in the process of replacing winforms forms with wpf windows so this is not a traditional wpf application.

**Comment by brianlagunas** [comment]
So are you launching a WinForms app that contains WPF views or are you launching a WPF app that hosts WinForms views?

**Comment by njsent** [comment]
It is a WinForms app that contains WPF views.  There are about 100 Windows Forms to every 1 WPF view so  it's likely a user may not even open a WPF view during their session.   We we are attempting to do is add all new content to this app as WPF views to lessen the burden of converting down the road.

**Comment by brianlagunas** [comment]
Ahhhhh.. in that case just keep using the bootstrapper :)

**Comment by njsent** [comment]
Thanks Brian - great work on Prism and I appreciate your passion for it.

**Comment by Shazter** [comment]
From Where I get the Type ShellWindow?

**Comment by KarthikSync** [comment]
> Thanks Brian - great work on Prism and I appreciate your passion for it.

I am on the same boat , If you could post the code snippet on how to host prism application in winforms that would be very helpful.  Thanks!
