### ISSUE TITLE
Navigation Service not working after Navigating to a page with Custom Layout

### ISSUE THREAD

**Issue by johnfurog** [PrismLibrary/Prism#1441]
### Description
Navigation Service not working after Navigating to a page with Custom Layout on Xamarin.Forms Version >2.5.0.280555

### Steps to Reproduce

1. Navigate to a page with Custom Layout using Navigationservice
2. Go Back
3.  Navigate to any page

### Expected Behavior
Able to navigate to pages using NavigationService
### Actual Behavior
NavigationService not working
### Basic Information

- Version with issue: All Version
- Last known good version:
- Xamarin.Forms version: >2.5.0.280555
- IDE: Visual Studio 2017 Community Edition 15.6

### Reproduction Link
https://github.com/johnkennethfurog/PrismNavigationService

**Comment by johnfurog** [comment]
It seems that this is not a Prism Issue , Tried it using the Navigation from the Code behind and still getting the same behavior.

Created new issue on Xamarin.Form Github : 
https://github.com/xamarin/Xamarin.Forms/issues/2710

**Comment by brianlagunas** [comment]
Thank you for the update. I hope they fix your issue soon.

**Comment by johnfurog** [comment]
Hi brian could we re open this issue ? since replicating this scenario without using prism resolves it.

**Comment by dansiegel** [comment]
If you’ve replicated the issue without Prism then it’s a Xamarin Forms issue.

**Comment by akhileshzimozi** [comment]
[OrderDetails.txt](https://github.com/PrismLibrary/Prism/files/2532804/OrderDetails.txt)
This is the output window and when I click a button for navigation then It is not working.Please help me.
Thanks

**Comment by dansiegel** [comment]
@akhileshzimozi this is a closed issue... if you have a new legitimate issue you'll need to open that appropriately. Remember if you believe you have encountered a bug you must provide an actual sample that reproduces the issue you are reporting otherwise we will close your issue. Debug Output is not acceptable. If you have a question because you aren't sure how to do something and it isn't covered in the docs, then you should ask that on StackOverflow with the tag `Prism`.
