### ISSUE TITLE
For a view registered for navigation with name a new instance always gets created in Prism.Wpf

### ISSUE THREAD

**Issue by BadMadDev** [PrismLibrary/Prism#1442]
### Description

When i register a view for navigation using a different name, e.g.
`containerRegistry.RegisterForNavigation<DockView>("ShowData")`
everytime i navigate to the view using `regionManager.RequestNavigate("ContentRegion", "ShowData")`
a new instance of the view gets created.

I have tried to
1) register the view as singleton,
2)  implemented IRegionMemberLifetime and always return true on KeepAlive
3) implemented INavigatioNAware and aölways return true on IsNavigationTarget (never gets called)
without success, a new instance gets always created.
I use DryLoc as IoC-Container.

### Steps to Reproduce

1. Register a view with a different name, e.g. `containerRegistry.RegisterForNavigation<DockView>("ShowData")`
2. Navigate to the view using `regionManager.RequestNavigate("ContentRegion", "ShowData")`

### Expected Behavior

A view shlulb be reused if kept alive, and IsNavigationTarget should be called to be able to decide wheter a new instance should be created or not.

### Actual Behavior

A new instace is always created.

### Basic Information

- Version with issue: 7
- Last known good version: 6

**Comment by dvorn** [comment]
Are you sure that worked for Prism 6?

When Prism is looking for a possible target view among all views already existing in the region, Prism does not know the names under which the view types were registered in container.  The only information available is the type itself - that is, its name.  Thus, if you register your view with a name different from the type name, the view will not be found.

I think this is by design.

https://github.com/PrismLibrary/Prism-Documentation/blob/master/docs/wpf/Navigation.md#navigating-to-existing-views:

Note: For Prism to determine the type of the target view, the view's name in the navigation URI should be the same as the actual target type's short type name. For example, if your view is implemented by the MyApp.Views.EmployeeDetailsView class, the view name specified in the navigation URI should be EmployeeDetailsView. This is the default behavior provided by Prism. You can customize this behavior by implementing a custom content loader class; you can do this by implementing the IRegionNavigationContentLoader interface or by deriving from the RegionNavigationContentLoader class.

**Comment by brianlagunas** [comment]
@dvorn is correct. This is by design.
