### ISSUE TITLE
WPF and GTK platforms

### ISSUE THREAD

**Issue by dvorn** [PrismLibrary/Prism#1449]
Now that WPF and GTK added to Xamarin.Forms

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/gtk?tabs=vswin

should they be added to RuntimePlatforms?

**Comment by dansiegel** [comment]
GTK absolutely can be... WPF through Xamarin Forms is flat out not supported by Prism at this time.

**Comment by pdinnissen** [comment]
Is there any reason why WPF couldn't be added in the future though?

**Comment by pprometey** [comment]
yes, WFP this is a dead-end branch of development

**Comment by brianlagunas** [comment]
There are a number of reasons WPF will never make it into XF.  As @pprometey mentioned, WPF is a dead-end branch in XF. Microsoft (Xamarin) only merged it because it was a community PR and they have no plans of actually supporting it. As it sits now, the support is very basic and not worth even using for a real production app.  If you want to have a WPF app, just write one.  You can reuse all your VM's if you wish, but running a mobile app "as-is" on desktop is just a bad idea in general.
