### ISSUE TITLE
[Win10 UWP] Refactor inflexible application initialization

### ISSUE THREAD

**Issue by JohnTasler** [PrismLibrary/Prism#146]
I don't understand why the following properties of PrismApplication are read-write. It seems they should only be read-only:
* Shell
* SessionStateService 
* NavigationService 
* DeviceGestureService 
* ExtendedSplashScreenFactory 

With these properties being writable, it gives the illusion that setting them will affect the application code as intended. The Shell property, for example, is created by overriding CreateShell, so its setter should be private. Otherwise it indicates that the derived class can change the property and have something affected in some deterministic way.

SessionStateService is **really** annoying. Although I can change the property, I can only do so either before (the non-virtual) InitializeFrameAsync or after it. In the latter case, when InitializeFrameAsync is called, the SessionStateService property gets wiped out with a new instance. If I set SessionStateService _after_ InitializeFrameAsync, it's too late because SessionStateService.RegisterFrame has already been called, so my implementation of that method doesn't get called. There's no way to correctly replace the ISessionStateService, meaning that _it's not really a service at all_.

I'm not sure about the last three (NavigationService, DeviceGestureService, ExtendedSplashScreenFactory), but they likely have similar problems. Since these are named with the **Service** (or Factory) suffix, it really seems like these should be coming from an IoC container. That way, I can just register my implementations of these interfaces and have the implementation get used at the correct places.

But, since the application doesn't really have a good place to plug-in a DI (other than the clunky virtual Resolve(Type) method, the next best thing would be to allow the creation of these services to be in overridden protected virtual methods.

The simplest would be to change CreateNavigationService (and similar) to protected virtual. Also, there should, of course, be a protected virtual CreateSessionStateService. However, to protect the base implementation from misunderstood virtual, it might be prudent to keep the private methods, but to have them call into the protected virtual methods, as such:

```cs
    private INavigationService CreateNavigationService(IFrameFacade rootFrame)
    {
        NavigationService = OnCreateNavigationService(rootFrame) ??
            new FrameNavigationService(rootFrame, GetPageType, SessionStateService);
        return NavigationService;
    }

    protected virtual OnCreateNavigationService(IFrameFacade rootFrame)
    {
        return null;
    }

```

Also, the Frame creation should be overridable:

```cs
    private Frame CreateRootFrame()
    {
        var frame = OnCreateRootFrame() ?? new Frame();
        return frame;
    }

    protected virtual Frame OnCreateRootFrame()
    {
        return null;
    }
```

Of course, I can fairly easily make these changes, but I figured some design discussion would be prudent prior to a pull request.

**Comment by briannoyes** [comment]
All very valid points. The reason for some of this is that the current code is just a quick port of the Prism for Windows Runtime code. When the p&p team built that, they explicitly did not want to take a dependency on having a dependency injection container because their assertion was that most Windows Store apps were not going to be that complication so shouldn't necessarily need one and the team did not want to force the idea that someone that wanted to use Prism would have to know anything about DI. 

We have found a lot of places in the Prism code base where there was insufficient use of virtual to allow overrides of things, so totally agree that opening things up for extension through inheritance makes sense. 

I generally prefer the pattern of base class private method calls a virtual or abstract method that the derived type would override to do the extension at the right time in terms of whatever the base class implementation is doing.

I'd say go ahead and submit a pull request with the changes you are recommending and we will pull it in.

**Comment by bartlannoeye** [comment]
Be careful with setting the NavigationService private as that would mean nobody is able anymore to inject his own NavigationService, which was a problem we encountered for one of our more complex projects on Windows 8.1 (and the reason I logged #24).

**Comment by JohnTasler** [comment]
Thanks, Bart, for implementing this!

**Comment by bartlannoeye** [comment]
Most of the credits go to @tomzorz for the grunt work.

**Comment by briandunnington** [comment]
I know it is not super helpful to post just to say 'Thank You', but thank you! Even just the ability to create our own frame without having to copy the entire base class into our own project is a huge win for us. Great to see this all get addressed.
