### ISSUE TITLE
Breaking changes in IModule

### ISSUE THREAD

**Issue by ENikS** [PrismLibrary/Prism#1508]
### Description

We are working on upgrade to latest version of Prism but because of breaking change in ``IModule`` unable to proceed. Considering number of existing modules requiring manual rewriting ( in hundreds of thousands for entire organization ) it is becoming too costly and impractical. 

The company I work for ( one of the largest in NY ) is considering abandoning this library for in house solution because of this change. I am pretty sure there will be more unhappy customers as soon as v7 is out of pre stage and more organizations start to upgrade.

I understand you are striving for greatness but perhaps it could be done without breaking most fundamental and used pattern/interface? 

**Is it possible that you could reconsider this change and provide legacy support as well as new features?**

### Steps to Reproduce

N/A

### Basic Information

- Version with issue: 7.1
- Last known good version: 7.0.0.336
- Xamarin.Forms version:
- IDE:

**Comment by brianlagunas** [comment]
This was a concern of mine when we first made this change, but we do have to move the framework forward.  The changes to IModule really are for the better, and will result in a better developer API and experience.  Honestly, you can update your IModule with very minimal effort.  Just implement the new methods as empty, and then copy/past the code you have in the old Initialize method into the OnInitialized method.  You don't have to change anything else. You don't even need to use any of the new interfaces in the new methods.  My approach to this would be to create a simple console app that did this for all my modules and it's done in seconds.

I will note, that you are more than welcome to stop using Prism and create your own internal framework that you can maintain and support internally.  Prism is open source, and we do not get paid when someone uses it.  So if your company stops using it, we don't lose anything. If your company would like to take on the burden on creating and maintain their own framework, they should go for it. Many companies do that now, and a lot of those frameworks are based off of Prism.

Actually, I will say this.  If your company (one of the largest in NY) would like to pay for this backwards compatibility, we can make it happen.  It would require a lot of thought and work, because it is not a simple change, but if we are paid for that time, then we can make it work.  It is probably cheaper than your company creating their own framework and maintaining it over the life of your projects, and then replacing Prism with your new framework in your current projects.  Just a thought.

**Comment by dansiegel** [comment]
@ENikS I should add here, just like Unity had to make breaking changes (which broke EVERY single Prism app across all platforms using Unity) to move the framework forward, Prism also must make changes from time to time to move the framework forward. I'm sure as a the maintainer for Unity you can understand these sorts of breaking changes aren't made lightly. In fact we have often held back on changes because we feel it would be too painful for WPF developers.

**Comment by GreenKn1ght** [comment]
@ENikS Do you propose to make one more breaking change? This will be painful for all Prism users who have already migrated their apps to latest version.
IMHO with this number of modules you need to expose your own abstraction. You can implement abstract class that will inherit IModule, implement its members and provide your own overridable abstract API. Or I believe you can override ModuleCatalog and ModuleInitializer to load and instatiate your own IModule. Both option allow you to use Find and Replace feature of any text editor to change legacy code instead of manual rewriting.

**Comment by ENikS** [comment]
Brian, it is not MY company, I just work there :)

Let me make one thing clear, I am not your enemy here. I like Prism and I use it everywhere I can and because of that I opened this issue. I would like to keep using it...

The decision to use or stop using the library is not up to me or even the team I work for, it is budget thing for the whole company. Think about economics of this change:

- Every single module in the world needs to be manually changed (however simple it might be)
- Every single change has to be accompanied with unit tests amended
- Every single module has to be regression tested

This creates unreasonable burden for all users of the library. The bigger the user, the more expensive it is. We are talking about hundreds of millions spent on this change worldwide and for WHAT?

Original `IModule` was brilliant in its simplicity and robustness. It was completely agnostic of container, platform, etc. It would easily accommodate any 'Resource Locator Pattern' you could throw at it, including new Prism one.

I am all for change and progress and I am not criticizing you for breaking the interface, but this particular change is too expensive for the benefits it provides. 

I would like to propose a compromise: Lets have a discussion with wider audience of users on this issue, after all, we are a democracy here, and get more opinions on this matter?

**Comment by bartlannoeye** [comment]
Nobody forces you to leave v6 and go to v7, you can limit NuGet updates by using [version ranges](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards). It's a major version bump for a reason. Some of my clients are sticking to Autofac v4 to stay away from the immutable container, or on Json.net v9 to not drag in a zillion dependencies until they move to .NET Core.

**Comment by ENikS** [comment]
But we do want to use the latest. We just don't want to pay so much for so little benefits.

**Comment by dansiegel** [comment]
> Let me make one thing clear, I am not your enemy here. I like Prism and I use it everywhere I can and because of that I opened this issue. I would like to keep using it...

@ENikS nobody is saying you're an enemy here. But certainly there is a huge irony that the person responsible for breaking so many Prism apps using Unity, is the one complaining about an API change in Prism that was made in large part because of the breaking changes that you did. 

>Think about economics of this change:
>- Every single module in the world needs to be manually changed (however simple it might be)
>- Every single change has to be accompanied with unit tests amended
>- Every single module has to be regression tested

I would say you're really making a bigger issue of this than it ought to be. All you really need is to add two lines of code to your modules and they'll work just fine.

```cs
public class LegacyModule : IModule
{
    public void OnInitialized(IContainerProvider containerProvider){ }

    public void Initialize(IContainerRegistry containerRegistry) => Initialize();
}
```

> Original IModule was brilliant in its simplicity and robustness. It was completely agnostic of container, platform, etc.

The "Original" IModule was overly simply, and not very robust at all. IModule was hardly agnostic of a container, it was closer to a straight up Atheist denying the very existence of a Container. The resulting pattern meant that in order to register anything, the Module was explicitly tied to a container. By contrast the updated IModule with the IoC abstractions is more of an Omnist, believing it should be able to work with any container, except Autofac because they're determined to be immutable. In addition to that the new IModule helps developers enforce a pattern of Register / Do Stuff rather than putting all of the code they need into a single method (which let's be honest most people were doing).

**Comment by ENikS** [comment]
@dansiegel You concentrating on **me** complaining about the change, breaking Unity, and simplicity of the change but you missing fundamental point: **This change is prohibitively expensive to implement. Like in real money expensive,**  

It is not a namespace change, or rename, where Resharper or cut and paste can help you. This is required manual change for every single module with all the testing to follow...


As for breaking Unity, I really had no choice in all these changes. I tried as hard as I could to preserve original contracts. I could go ever every single change with you and provide justification for each and every one. I do not think Unity breaking changes could be compared with `IModule`.

**Comment by dansiegel** [comment]
@ENikS I am hardly focusing solely on you complaining about the change. I do not think you fully appreciate the irony though.

The snippet below is all you need to make your module v7 compatible. If your company requires something more, as @brianlagunas mentioned before this is an Open Source library, you are more than welcome to fork or submit a PR. If your bosses feel it would be too expensive to add two lines of code, they are also welcome to pay for the backwards compatibility to be added for them.

**Comment by ENikS** [comment]
@dansiegel The irony does escapes me, what am I missing?

**Comment by istvanfarmosi** [comment]
Actually, the complexity of the upgrade isn't in the code changes required - as Brian said that's pretty much a string replace job. However, enterprise users of Prism tend to write applications using multiple teams, each releasing their own part in some form, independent of the others. This works as long as shared components do not really change, allowing you to use assembly bindings. Having such a basic interface change breaks this, forcing all of these teams to update their code and release it all at the same time - the coordination involved could be quite the challenge. I can see this pushing companies towards either delaying the upgrade indefinitely (read: never) or removing Prism from their code, neither of which is optimal.

Even though Prism is an open source project and it doesn't have financial motivation to get people to keep using it, it needs to have a reason to exist - that is, it needs people to use it. I'm not sure if losing (some) enterprise users has a bigger impact than the gains from the standardization, but the whole issue could be avoided by offering some form of backwards compatibility (even if only maintained for a short timeframe).  I'm thinking something along the lines of keeping the old IModule as-is, marking it obsolete and adding the new interface under a new name, then in version 8 or so moving completely to the new one. Letting them coexist for a while would allow large users of the library to update their stuff piece-by-piece, which I think would be a huge benefit. Would you consider this option if someone put in the effort to write it?

**Comment by ENikS** [comment]
Does not even have to be new name, just use different namespaces.

**Comment by psmulovics** [comment]
It even can be the same name, just under a different namespace.
