### ISSUE TITLE
Call RegisterTypes for all modules with InitializationMode.WhenAvailable before calling OnInitialize 

### ISSUE THREAD

**Issue by cfneese** [PrismLibrary/Prism#1522]
With the new interface for IModule introduced in Prism 7.x for WPF, why not call RegisterTypes on all modules that are loading together before calling OnInitialize on the same modules?

This would be useful, because it would allow removal of module dependencies in some cases.  I also believe that this is the intuitive behavior implied by the new interface: since the IModule interface now requires two methods a naive assumption is that these two methods are invoked at different stages during bootstrapping.  Otherwise why have two methods when one would suffice?

**Comment by brianlagunas** [comment]
First off, modules are short lived and prism does not maintain a collection of the module instances as this could lead to memory leaks.  Modules can also be loaded at any time in many different ways including dynamically loaded into the app domain at runtime from a module being dropped into a folder.  The new methods provide clear guidance on where to place your code and helps separate the concerns of your code (registering vs initialization code).  It also gives access to the new IContainerProvider and IContainerRegistry to ensures you are using them properly.  It also aligns the interface across platforms.  You also have to consider dependent modules and scenarios where services must be resoved in order to be used in a dependent module.  We also do not want to change the behavior of how modules load in WPF s that would be a massive behvaioral breaking change which could have very severe consequences to user's applications.

Needless to say, we will not be chnaging how we load modules.

**Comment by cfneese** [comment]
Thanks for the quick response Brian.

Prism would not need to maintain a collection of module instances beyond the time it takes to initialize the modules so there should not be an additional chance of memory leaks.  Second, I understand that modules can be discovered and loaded at different times.  This additional behavior would only apply to modules that are loaded at the same phase of the application.  So if I have an application that is dynamically discovering modules from a folder, then the proposed behavior would simply not apply, because the modules would be discovered one at a time, and would load one at a time if they have InitializationMode.WhenAvailable.

Aligning the interface across platforms is obviously great, but I'm not suggesting changing the interface.  The behavior I am describing is actually only possible because of the new interface and the fact that the new interface encourages correct use of IContainerProvider and IContainerRegistry.  

So here's the catch: A module that ignores the separation of concerns imposed by IContainerProvider and IContainerRegistry and resolves objects from the RegisterTypes method or registers types from the OnInitialized method might lead to different program behavior.  For WPF there shouldn't yet be many of these critters in the wild.  The fact that Xamarin has had this interface for a while may be a significant concern.  These are probably poorly written modules but it is perfectly reasonable to be averse to breaking poorly written code.  (That said, there is already a breaking change in 7)

I'm perfectly fine with the current load module process.  If I wasn't, I would provide a pull request or a standalone module manager.  But I think it is important to point out that if I have module B that is going to resolve types registered by module A and registering and resolving are clearly separated by the IModule interface then the load sequence register A, register B, resolve A, resolve B or register B, register A, resolve B, resolve A can eliminate the explicit B -> A dependency.
