### ISSUE TITLE
System.InvalidOperationException on navigating to MasterDetailPage with MasterBehavior="Split"

### ISSUE THREAD

**Issue by AlexanderVolkovDA** [PrismLibrary/Prism#1536]
### Description

System.InvalidOperationException on navigating to MasterDetailPage with MasterBehavior="Split"
Exception message:
"Can't change IsPresented when setting Split"

StackTrace: 
[StackTrace.txt](https://github.com/PrismLibrary/Prism/files/2315225/StackTrace.txt)

### Steps to Reproduce

1. Create MasterDetailPage
2. Set MasterBehavior to "Split"
3. Navigate to this page from another page

### Expected Behavior

MasterDetail page appears in splitted mode

### Actual Behavior

Navigation crashes with exception

### Basic Information

- Version with issue: 7.0.0.396
- Last known good version: ---
- Xamarin.Forms version: 2.5.0.122203, 
- IDE: Microsoft visual studio v 15.7.6

### Reproduction Link

[MasterPageTest.zip](https://github.com/PrismLibrary/Prism/files/2315248/MasterPageTest.zip)

**Comment by AlexanderVolkovDA** [comment]
I haven't checked properly, but from the first look the root of the problem is in Prism.Navigation.PageNavigationService.ProcessNavigationForMasterDetailPage()
It doesn't check CanChangeIsPresented property before seting currentPage.IsPresented. Suppose adding this check could help.

**Comment by brianlagunas** [comment]
I haven't looked into this yet, but this is the first thought I had when I read the issue. Looks like an easy fix.

**Comment by brianlagunas** [comment]
I was able to reproduce this issue. The reason I never ran into it is because my MasterDetailPages always implemented `IMasterDetailPageOptions` as follows:
```
        public bool IsPresentedAfterNavigation
        {
            get { return Device.Idiom != TargetIdiom.Phone; }
        }
```
For now, you can use that as a workaround.

By the way, there is no CanChangeIsPresented property on the MasterDetailPage in XF. One more thing, do not place a MasterDetailPage in a NavigationPage. That is a navigation "no-no".

**Comment by brianlagunas** [comment]
Actually, now I remember... You must use the `IMasterDetailPageOptions` to control how you want the IsPresented to work because Prism cannot determine the combination of device orientation AND the MasterMode required to make that decision for you.

Look at the following table of possible scenarios:
![image](https://user-images.githubusercontent.com/835562/45580477-ab8e7500-b84e-11e8-9df9-af1b72d00fa2.png)

If your setting is set to Split, then the code snippet I provided will work fine for you. However, if you have more complex behavior such as SplitOnLandscape, you'll have to change your implementation of the interface to work with your situation.
