### ISSUE TITLE
Android: Different behavior of INavigatingAware for back button and GoBackAsync navigation

### ISSUE THREAD

**Issue by WebDucer** [PrismLibrary/Prism#1571]
### Description

We have a modal page with "Cancel" button on it. The page from which we navigate to implements INacvigatingAware.

If we use the "Cancel" button (that call `GoBackAsync` on), the `OnNavigatingTo()` method is triggered on the previous page.
If we use the "Back" button (hardware) on Android device, the `OnNavigatingTo` method is not triggered.

In both cases the `OnNavigatedTo` is triggered.

### Steps to Reproduce

1. Create two pages
2. First page implements `INavigatingAware`
3. Navigate to the second page from the first page
4. Navigate from second page to the first page with Navigation (`GoBackAsync`) or back button (in navigation bar or hardware)

### Expected Behavior

The same behavior for  `INavigatingAware` independent wether we use back button or back navigation.

### Actual Behavior

`INavigatingAware` is not called, if navigated back with Android hardware button.

### Basic Information

- Version with issue: 7.1.0279
- Last known good version:
- Xamarin.Forms version: 3.2
- IDE: VS 2017.8

**Comment by jacksonveroneze** [comment]
@WebDucer 

Hello, I have the same problem and have not yet found a solution for it.

**Comment by brianlagunas** [comment]
This is a known limitation of the Xamarin.Forms API.  We are not able to intercept the hardware back button before navigation occurs. We must handle two events for back button support, ModalPopped on the application class and the NavigationPopped on the NavigationPage, neither of which provide us the ability to gain access to any pages before navigation actually occurs.  In both cases, these events are fired after navigation has actually occurred.  Therefore, calling INavigatingAware would make no sense because it's not an accurate time to call it. Technically, we could call the method in the Popped events followed immediately by the INavigatedAware method, but this is not an accurate representation of the nav process and would be misleading as any code you would expect to fire before a page is navigated to would not work. This is important for data which you are trying to prepopulate the page before the binding engine updates and syncs to the UI.

Essentially, this would be the code block
```
OnNavigatingFrom(previousPage, parameters);
OnNavigatedFrom(previousPage, parameters);

var onNavToTarget = GetOnNavigatedToTargetFromChild(currentPage);
OnNavigatingTo(onNavToTarget, parameters);
OnNavigatedTo(onNavToTarget, parameters);
```
It would be similar to calling the same method twice.
