### ISSUE TITLE
XAML NavigateTo on Partial Views error

### ISSUE THREAD

**Issue by YZahringer** [PrismLibrary/Prism#1572]
### Description
NavigateTo on Partial Views does not work.

### Steps to Reproduce
Add Button with NavigateTo command on PartialView.

### Actual Behavior
System.ArgumentNullException: Value cannot be null. Parameter name: parentObject    at Prism.Navigation.Xaml.NavigationExtensionBase.Initialize(IProvideValueTarget valueTargetProvider, IRootObjectProvider rootObjectProvider)    at Prism.Navigation.Xaml.NavigationExtensionBase.ProvideValue(IServiceProvider serviceProvider)

### Basic Information
- Version with issue: 7.1.0.279-pre
- Xamarin.Forms version: 3.2.0.871581
- IDE: VS2017 15.8.6

**Comment by brianlagunas** [comment]
You need to provide a sample as stated in the Issue template. I will re-open when a reproduction is provided. Your description doe not provide enough information.

**Comment by YZahringer** [comment]
Reproduction link: https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/Prism-PartialView-NavigateTo

**Comment by dansiegel** [comment]
It would seem this is actually likely due to the use of XamlC. Effectively what you end up with is:

```cs
var partialView = new PartialView();
var page = new Page
{
    Content = partialView
};
```

The problem with this is that when the PartialView is constructed the Command is also set in your Button. This is a problem since we currently are trying to retrieve the ParentPage before there is one set. This needs to be refactored so that we grab the parent object and do no further analysis of it until we are ready to get the Parent Page when the Command is executing.
