### ISSUE TITLE
AutoWireViewModel="True" and several Views per ViewModel and keeping CodeBehind clean

### ISSUE THREAD

**Issue by HansKrJensrud** [PrismLibrary/Prism#162]
In a case where two or more Views use the same ViewModel, the DataContext may be set in different ways when the AutoWireViewModel="False". My question is if this is possible when AutoWireViewModel="True". 

As far as I understand, the reference to the ViewModel is set by using naming conventions (and partly namespace conventions?). This is ok as a default solution, but if not already easy to achieve, it would be an improvement if the View's default ViewModel could be registered to the View independent of naming (otherwise standard naming conventions is used).

In my case Company and System uses many of the same properties, but it seems obvious to me that it is quite common that one ViewModel may present its properties in several different ways.

Any simple solution / changes to the ViewModelLocator which may be used to resolve this, or am I on a wrong path regarding this?

**Comment by noufionline** [comment]
Hi HansKr Jensrud,

I think by using ViewModelLocationProvider.SetDefaultViewTypeToViewModelTypeResolver((viewType) => {

});
you can create your own mechanism as required.

**Comment by HansKrJensrud** [comment]
Yes, this was the solution using Prism 5 if you wanted both the View and ViewModel in the same folder/ namespace. This will probably work regarding the issue above as well. I hoped for something even easier if possible, but I'll look into. Guess it will work just fine. Thanks!

**Comment by briannoyes** [comment]
@HansKrJensrud The conventions are just intended to be a starting point that hopefully work for a majority of users. Of course that is very hard to determine since we don't have direct contact with everyone who uses Prism. But @noufionline said, one way to make it happen is with SetDefaultViewTypeToViewModelTypeResolver. Another way that I would recommend because the former is meant to set a default that will be used for all resolutions, would be to use the Register method. This lets you set up a mapping for any given view type to provide a factory method that constructs the appropriate ViewModel (possibly through the container). This is called internally before falling back to the default conventions, so that would be the most appropriate way for what you are describing. 

Also consider that there is nothing saying that every single V/VM pair in your app has to use VML. I'll often have some number of views in my app that get married to their ViewModel dynamically, such as by placing a ViewModel into a Region and having the View provided by a data template mapped to it with the DataType property.

So for example in your case you could put the view in a UserControl, have two data templates each with their DataType set to a different ViewModel type, and have the content of those two DataTemplates just be the corresponding ViewModel type.

Hope that helps.

**Comment by HansKrJensrud** [comment]
Thanks! It was something like the Register method I was looking for.
