### ISSUE TITLE
Dependency Service Dependencies not being resolved via container

### ISSUE THREAD

**Issue by james1301** [PrismLibrary/Prism#1627]
### Description
Registering a dependency does not seem to work by default like the documentation here: [Using Dependency Service in Prism](https://prismlibrary.github.io/docs/xamarin-forms/Dependency-Service.html). It doesn't seem to automatically resolve the dependency's that are part of the dependency service. I have instead had to have the dependency service brought in and then resolved it from there.

### Steps to Reproduce

1. Create a dependency in the iOS project for the ITextToSpeech interface
2. Try to bring that through to the MainViewModel
3. Error

### Expected Behavior
As the dependency is set in the iOS project, it should be part of the container and not error.

### Actual Behavior
Errors as it doesn't seem to have the dependency in the container.

### Basic Information

- Version with issue: 7.1.0.431 (Prism Forms, Core and Unity)
- Last known good version: Unknown
- Xamarin.Forms version: 3.4
- IDE: Visual Studio 2017 for Windows

### Screenshots
N/A

### Reproduction Link
[App1.zip](https://github.com/PrismLibrary/Prism/files/2595152/App1.zip)

**Comment by dansiegel** [comment]
This is by design in Prism 7. While Prism 6 supported this behavior, this was always an anti-pattern and very limiting as it meant all of your platform types had to use a default constructor and could not benefit from services registered with your container. 

To use Platform Specific Implementations/Types please use `IPlatformInitializer`, you can see a sample in our [Sandbox app](https://github.com/PrismLibrary/Prism/tree/master/Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS).

**Comment by james1301** [comment]
Cool sounds good. Any chance of updating the documentation? I think this is what confused me the most.

**Comment by brianlagunas** [comment]
We accept PRs :)

**Comment by dansiegel** [comment]
@james1301 it had actually previously been removed from the Navigation Menu, it appears you discovered a link embedded in one of the pages, that has since been removed.

**Comment by james1301** [comment]
Yeah I had just noticed that actually!
