### ISSUE TITLE
Expand IoC Abstraction API

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1654]
### Description

The IoC Abstractions introduced in Prism 7 help to provide a consistent API regardless of the specific DI Container used. This opens a range of possibilities for code sharing where Modules could potentially be developed and shared across organizations, or even within an organization where teams may differ on a preferred DI/Container. 

The current API surface is perhaps overly simplistic though and would greatly benefit from the addition of a couple of new API's that are likely to be encountered in Production, as well as potentially helping to further simplify some of the existing Prism API surface.

#### Is Registered

It is a fairly common requirement where a developer may need to validate that a particular service has been registered. For example you may wish to use this in a module in a situation where you register a default implementation of a service in the event that it has not yet been registered.

```cs
if(!containerRegistery.IsRegistered<IFooService>())
{
    containerRegistery.Register<IFooService, DefaultFooService>();
}
```

#### Register a Singleton for all implemented interfaces

This is actually the preferred approach when using the Prism Logging Plugins where the logger implements multiple interfaces including `ILoggerFacade`, `ILogger`, `IAnalyticsService`, and `ICrashesService`. 

```cs
containerRegistery.RegisterMany<AwesomeLogger>();

try
{
    var loggerFacade = Container.Resolve<ILoggerFacade>();
    var logger = Container.Resolve<ILogger>();
    if(!object.ReferenceEquals(loggerFacade, logger))
    {
        throw new Exception("This would never happen because we're using the same instance...");
    }
}
catch(Exception ex)
{
    Container.Resolve<ICrashesService>().Report(ex);
}
```

#### Resolve Type with specified Arguments

This would actually simplify code for Prism.Forms and Prism.Windows by allowing types to be Resolved with specified types such as a specific instance of INavigationService, or a specific Frame in UWP.

```cs
var navService = Container.Resolve<INavigationService>(PrismApplicationBase.NavigationServiceName);
((IPageAware)navService).Page = page;
// Resolve(Type, params object[])
return Container.Resolve(viewModelType, navService);
```

**Comment by hnabbasi** [comment]
@dansiegel, for **Register a Singleton for all implemented interfaces**, does the `RegisterMany<>()` register all named and unnamed registrations?

e.g. If,
```csharp
public interface IBeta { void Log(string s); }

public class A : IAlpha, IBeta
public class B : IBeta
```
is registered as,
```csharp
containerRegistery.RegisterMany<A>();
containerRegistery.Register<IBeta, A>("BA");
```
then:
```csharp
var a = Container.Resolve<IBeta>("BA");
var b = Container.Resolve<IBeta>();
var c = Container.Resolve<IBeta>();
```
are `a`,`b`,`c` same? or will `a` still be a differnet instance? And how will this API work with `RegisterSingleton<>()`?

**Comment by rafsanulhasan** [comment]
Is it possible to support registering instances as singletons? 


```
// Current I'm using this
containerRegistry.RegisterInstance(CrossConnectivity.Current);
containerRegistry.RegisterInstance(CrossSecureStorage.Current);
containerRegistry.RegisterInstance(CrossSettings.Current);
containerRegistry.RegisterInstance<IRunInvoker>(new UIThreadRunInvoker());
// I Want this
containerRegistry.RegisterSingletonInstance(CrossConnectivity.Current);
containerRegistry.RegisterSingletonInstance(CrossSecureStorage.Current);
containerRegistry.RegisterSingletonInstance(CrossSettings.Current);
containerRegistry.RegisterSingletonInstance<IRunInvoker>(new UIThreadRunInvoker());
```

**Comment by dansiegel** [comment]
@hnabbasi to answer your question:

> does the RegisterMany<>() register all named and unnamed registrations?

Yes... so given that you have something like:

```cs
public interface IFoo { }
public interface IBar { }

public class A : IFoo, IBar { }
public class B : IBar { }
```

With the current API you might do something like:

```cs
containerRegistry.RegisterSingleton<IFoo, A>();
containerRegistry.RegisterSingleton<IBar, A>();
containerRegistry.RegisterSingleton<IBar, B>("foo");
```

If we compare the instances you'll see the following:

```cs
object.ReferenceEquals(c.Resolve<IFoo>(), c.Resolve<IBar>()); // false
object.ReferenceEquals(c.Resolve<IFoo>(), c.Resolve<IFoo>()); // true
object.ReferenceEquals(c.Resolve<IBar>(), c.Resolve<IBar>()); // true
object.ReferenceEquals(c.Resolve<IBar>(), c.Resolve<IBar>("foo")); // false
```

Whereas the RegisterMany API (which happens to correspond to the DryIoc API) would look like:

```cs
containerRegistry.RegisterMany<A>();
containerRegistry.RegisterSingleton<IBar, B>("foo");
```

You'll notice however that when we compare the instances this time you'll see that IFoo and IBar are the same instance.

```cs
object.ReferenceEquals(c.Resolve<IFoo>(), c.Resolve<IBar>()); // true
object.ReferenceEquals(c.Resolve<IFoo>(), c.Resolve<IFoo>()); // true
object.ReferenceEquals(c.Resolve<IBar>(), c.Resolve<IBar>()); // true
object.ReferenceEquals(c.Resolve<IBar>(), c.Resolve<IBar>("foo")); // false
```

@rafsanulhasan to answer your question...

RegisterInstance already treats this as a singleton... so any time you resolve the service you will get the same exact instance... 

```cs
containerRegistry.RegisterInstance(CrossConnectivity.Current);

object.ReferenceEquals(c.Resolve<IConnectivity>(), c.Resolve<IConnectivity>()); // true
```

In fact all of the plugins you referenced use a singleton pattern in the first place, so even if you were to use a delegate to try to make it a Transient Service, it would still return the same instance since that's how the libraries were architected... Also I would say that scoped lifetimes are outside of what we want to include.

**Comment by ZmorzynskiK** [comment]
I second that thread. Generally it was a great move to abstract IoC 👏, but the lack of:

```csharp
containerRegistry.RegisterSingleton<TFrom, TTo>("NAME");
```
is killing me right now 😉 as I need to add unity directly to any project that registers some kind of singleton instance (service) and at some point I want to get all of those registered singletons (services).

**Comment by rafsanulhasan** [comment]
What about 
```
containerRegistry.RegisterInstance<WebAuthenticator, OAuth2Authenticator>(new OAuth2Authenticator(_Configuration.GitHub.AppId, _Configuration.GitHub.AppSecret, "user,repo", authorizeUri, redirectUri, accessTokenUrl, null, false)
			{
				IsLoadableRedirectUri = true,
				ShowErrors = true,
				//AccessTokenName = "access_token",
				ShouldEncounterOnPageLoaded = false,
				Title = "Login to GitHub"
			}, "GitHubAuth");
```

**Comment by rafsanulhasan** [comment]
What if I want to register my own service abstractions as singleton lifetime like the following:

```
containerRegistry.RegisterSingletonInstance<IAuthService, AuthServcie>(new AuthService());
```

**Comment by Haukinger** [comment]
I don't get why this abstraction layer has to be visible to the user. It _may_ be useful within Prism, but for the user it only complicates things. In the end, it's either incomplete (in which case the user as to use his container anyway) or at least as complex as the container it tries to abstract from. As a bonus, it introduces bugs in the user code if different abstraction-implementations act differently (example: dryios and unity and multiple interface-singletons).

It's a myth that you can swap out one container for another, as it's a myth that you could abstract from entity framework and swap it out for nhibernate transparently. It's the same as trying to abstract from Prism to be able to exchange it by mvvmlight, it just won't work.

**Comment by dansiegel** [comment]
@totht91 we considered it, but it would have created an additional dependency, and the API isn't all that great to be honest, not to mention that you've got certain container authors that will tell you Microsoft introduced some very bad patterns there.

@Haukinger while I would agree with you that it's a myth that you could ever simply swap a MVVM frameworks, overwhelmingly most questions that we get are about DI. We can write docs around how to do this or that, but we'd only be showing how to do it with a specific container which may not be the one that you want to use. Not to mention it isn't Prism's job to document the Containers. While there are in fact some missing API's in our container abstractions, the goal is to simplify the vast majority of your registrations which for most people believe it or not actually would accomplish the goal of exchanging one container for another. Truth be told, with the proposed changes, I could actually ship Prism production ready Modules via NuGet that could allow you to simply add that Module without regard for which container you are specifically using.

**Comment by brianlagunas** [comment]
@totht91 I will also add that is does not meet the most basic requirements of a DI container that Prism requires. It must be mutable and allow register/resolve using a named instance.

@Haukinger The IoC abstraction is not about trying to abstract Prism so you can swap in a different MVVM framework. That would be impossible since Prism is much more than jus MVVM. It is not a myth that you can't swap out DI containers though. Taking the time to actually do it is another story. The Prism abstraction is more about making Prism easier to develop and maintain as well as create a consistent API across platforms and containers. This helps developers understand all Prism concepts outside of a specific conatienrs, as well as video tutorials and documentation.  The abstraction actually dramatically simplifies things for Prism developers, especially across platforms.  Also, the implementations do not behave differently. The behave the exact same which is why we have our own IoC API.

**Comment by Haukinger** [comment]
> They behave the exact same which is why we have our own IoC API.

@brianlagunas I have to disagree here. Run this and see that one test fails while the other succeeds (I've arbitrarily chosen the unity behavior to mean success):

    internal class ContainerAbstractionFixture
    {
        [TestCaseSource(nameof(ContainerFactories))]
        public void OneSingletonWithTwoInterfaces( IContainerExtension container )
        {
            container.RegisterSingleton<Service>();
            container.Register<IFirstInterface, Service>();
            container.Register<ISecondInterface, Service>();

            var first = container.Resolve<IFirstInterface>();
            var second = container.Resolve<ISecondInterface>();

            Assert.That( first, Is.SameAs( second ) );
        }

        private interface ISecondInterface
        {
        }

        private interface IFirstInterface
        {
        }

        private class Service : IFirstInterface, ISecondInterface
        {
        }

        private static IEnumerable ContainerFactories
        {
            get
            {
                yield return new Prism.Unity.Ioc.UnityContainerExtension( new Unity.UnityContainer() );
                yield return new Prism.DryIoc.Ioc.DryIocContainerExtension( new DryIoc.Container() );
            }
        }
    }

The `UnityContainerExtension` resolves the same instance twice while the `DryIocContainerExtension` resolves two different instances. Arguably not the most common use case, but clearly different behavior. To live up to the promise of being able to swap out containers, there may not be any differences.

**Comment by brianlagunas** [comment]
> To live up to the promise of being able to swap out containers, there may not be any differences.

There is no promise. That is not the point of the Prism IoC abstraction.

**Comment by Haukinger** [comment]
@brianlagunas you're talking about swapping out containers, @dansiegel is talking about using modules with different containers. Of course, there's a promise in the mere existence of the container abstraction.

From a user perspective, the Prism 6 system of having specialized bootstrappers for each container is much more useful and less misleading as the Prism 7 system with its leaky abstraction. I understand your reasons for introducing the abstraction, but as user I just don't care. What I care for is a well documented library that's intuitive to use and does not surprise me with hidden bugs.

**Comment by brianlagunas** [comment]
@Haukinger there is no promise, as that is not the primary purpose of the abstraction. It is possible to swap out containers more easily with this abstraction, but that is not it's primary intent. It's more of a side-effect.

Obviously, we cannot control the behavior of the various containers, and as a developer you should have tests to validate your code. Especially if you are going to switch containers (which very rarely happens).  Also, pointing out one fringe scenario does not prove that the entire abstraction is problematic. It just shows a very interesting behavior difference in various containers when doing some unorthodox registrations.

You are only one of the very few people that feel that having specialized bootstrapper was better.  The abstraction is not "leaky". That is a gross mischaracterization. Since all you care about is a well documented library, then you should love the new abstractions because it allows us to provide just that. Keeping the old way would require multiple doc topics covering the many different ways to do things using the different containers. We would never be able to accomplish that with the old system.

Since you feel so strongly about it, don't use the abstraction. You can continue to use your specific container directly in Prism. You are not forced to use the abstraction.

**Comment by Haukinger** [comment]
@brianlagunas when I stumbled across this issue, I took the chance to voice my concerns. I work with Prism on a daily basis, and I can work with the new system, but I don't like it and I think sacrificing quality to save on support personnel is the wrong way.

Right now, `IContainerRegistry` contains _zero_ documentation. At least, there should be a warning note that the implementations for different containers behave differently. I mean, when you have `ICar.Start()`, would you expect `Mercedes` to just start the engine while `BMW` starts the engine on the first press and closes the windows if you press it again?

**Comment by brianlagunas** [comment]
Absolutely zero quality is being sacrificed with the new abstraction API.  The fact that you would make such a statement reinforces my opinion that people really have no idea how much work and effort goes into maintaining a project such Prism.  Asking us to support multiple containers with different APIs and implementations shows there is a lack of respect for our time or the efforts we put into Prism.  Pointing out one unorthodox registration behavior difference between containers does not support your position.  Which by the way, if you use the container directly would still have the same registration behavior difference. So that doesn't support the position you are taking.  As you are well aware, we have not had time to document  large number of things. The nice thing is that the API is so simple, it is self documenting. You don't have to read docs to understand how it works.

Your concern is not based on any substantial technical requirements.  It is based solely on your personal opinion.  Especially since you do not plan on switching containers, there is no real argument against the abstraction API.  Consider your concern noted. However, this is the direction Prism is going and it's not going to change.

**Comment by Haukinger** [comment]
> Absolutely zero quality is being sacrificed with the new abstraction API.

 

An intuitive API (you get an `UnityContainer`, do your unit stuff with it, you get an `DryIocContainer`, do your Dry-Ioc stuff with it) is replaced with one that surprises the user, to say the least (you get an `IContainerRegistry`, but it might behave like unity or it might behave like Dry-Ioc). That’s a reduction in quality, although I admit that it may also bring a reduction in maintenance and support effort.

 

> Pointing out one unorthodox registration behavior difference between containers does not support your position.

 

I see services with two interfaces regularly. I’d be interested to hear how you register them as singleton in a less unorthodox way.

 

> Which by the way, if you use the container directly would still have the same registration behavior difference.

 

Agreed, but the containers do not pretend to be interchangeable, while a common interface does. That’s the point of having an interface in the first place…

 

> As you are well aware, we have not had time to document large number of things. The nice thing is that the API is so simple, it is self documenting. You don't have to read docs to understand how it works.

 

No, it does not. Obviously, it does not describe the expected behaviour of `Resolve` after `Register`ing with two interfaces before, and you can understand that only if you know the implementation.
