### ISSUE TITLE
Is it any workaround for make {Binding XXXCommand} intelligence working while AutoWireViewModel set to True ?

### ISSUE THREAD

**Issue by GreatFireWall** [PrismLibrary/Prism#1671]
Now I'm using `prism:ViewModelLocator.AutoWireViewModel="True"` and not declarate explicit ViewModel in xaml. Intelligence for {Binding xxx} not work.

**Comment by bartlannoeye** [comment]
Please have a look at the samples, because with Prism you don't have to declare the ViewModel explicitly in XAML. You could set a breakpoint in your ViewModel's constructor to see if it gets instantiated (which should if it's named correctly). Binding should work out of the box.

[Xamarin.Forms](https://github.com/PrismLibrary/Prism-Samples-Forms)
[WPF](https://github.com/PrismLibrary/Prism-Samples-Wpf)
[Windows 10](https://github.com/PrismLibrary/Prism-Samples-Windows)

**Comment by GreatFireWall** [comment]
Yes, Binding is work out of the box. But no intelligence tips for member of the DataContext.

**Comment by hvaring** [comment]
You can set `d:DataContext="{d:DesignInstance <yourviewmodel>}"` on your control to make IntelliSense work.

**Comment by GreatFireWall** [comment]
@hvaring thanks, it works.
