### ISSUE TITLE
Should INavigatingAware be changed?

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#1724]
### Description

When support for INavigatingAware was added, the intent of the API was always about ViewModel initialization. This later bloomed into some support that is counterproductive such as trying to support OnNavigatingAware when Navigating back to a given View. This is beyond the scope of the API's original intent, and cannot be fully supported particularly in cases where Navigation has occurred outside the context of the NavigationService such as from the Hardware Back Button.

In the next release of Prism the behavior will be fixed to restore the original intent of this API. This leaves the question of whether the Prism team should leave the API named INavigatingAware.OnNavigatingTo or whether we should rename this to make it easier to understand the intent.

https://twitter.com/prismlib/status/1101535125534208001 

Also worth noting that we are looking at adding Async support either way.

#### Spec

```cs
public interface INavigationInitialize
{
    void OnInitialized(INavigationParameters parameters);
}

public interface INavigationInitializeAsync
{
    Task OnInitializedAsync(INavigationParameters parameters);
}
```

**Comment by sb34000** [comment]
Hi Dan,
I Wonder why on the rework of INavigationAware, the logic of the suspending bool disapeared.
We intensively used it in our LOB UWP app to unsubscribe to event handlers and other specific contexts to prevent memoryleaks. This bool was used to apply different logic when leaving a page on a normal navigation (in that case we clean all the handlers) but when the navigatedfrom is called by lifecycle events, we need to keep all handler subscriptions because the constructor will not be called on resume. 
What is the proposed logic in remplacement ?
I'm afraid it means a lot of breaking changes if we try to migrate from Prism 6.3 to 7.x ?
Thanks for your help
Seb

**Comment by bartlannoeye** [comment]
Hey Seb, thank you for your feedback.

There will be breaking changes for UWP between 6.3 and 7.x, that's why it's a new major version, but we have our own large LoB apps to test the release on and will do our best to keep functionality and document all changes.

We also notice the difference in UWP (desktop) and XF (mobile), even though you can do UWP with XF. It's something we're currently looking into and discussing with Microsoft and some partners.

**Comment by sb34000** [comment]
Hi Bart,
Thank you for your answers. I understand the need of breaking changes. Will the Adventure works sample updated with 7.x to help us understand how to deal with new behaviour. Do you have any doc or sample for UWP ? The sample in the sandbox are so basic...
Thanks,
Best regards,
Seb

**Comment by bartlannoeye** [comment]
The samples and documentation will be rewritten once we land on a v7 release.

**Comment by brianlagunas** [comment]
We changed it
