### ISSUE TITLE
OnNavigatedFrom

### ISSUE THREAD

**Issue by angelru** [PrismLibrary/Prism#1751]
Hello,

I am using the latest version and I have the masterdetail page.

When I click on a section of the menu for the first time, it does not enter the event OnNavigatedFrom (correct), but if I open the menu and give it to the same page, enter the event OnNavigatedFrom and then OnNavigatedTo (correct), because you enter OnNavigatedFrom the second time if I call the same page ?, this does not happen if I have a page and I call a different one to the menu, it does not load the event OnNavigatedFrom (correct), only if I call from the menu to the same page 2 times once It's loaded.

I think it's not the right behavior, or am I missing something?

**Comment by dansiegel** [comment]
How To questions belong on StackOverflow…

**Comment by angelru** [comment]
@dansiegel Under my humble opinion, I think you did not understand what I said, 

if on my master page I am going to see A, OnNavigatedFrom is not activated (all correct) if I open my master page again and return to the viewA, OnNavigatedFrom of the view is activated, it should not (I think it is bug)

**Comment by dansiegel** [comment]
@angelru we have issue templates for a reason. We do not want questions posted here, and we do not have time to try to reproduce your issues. If you believe you have come across a bug you need to follow the issue template and include a sample that demonstrates the issue you are reporting. Otherwise you have a question which should be posted on StackOverflow.
