### ISSUE TITLE
Experience error in bootstrapper after upgrading to Unity 4.0.0

### ISSUE THREAD

**Issue by HansKrJensrud** [PrismLibrary/Prism#176]
Upgrading to Unity 4.0.0 result in an error in bootstrapper/createshell: 

return Container.Resolve<MainWindow>(); 

The error message ask for referencing version 3.5. Uninstalling Unity 4.0 and Prism.Unity, and re-installing Prism.Unity (incl. version 3.5.1404) resolves the error.

Anyone else experiencing this?

**Comment by bartlannoeye** [comment]
I checked with Unity and they changed to signed assemblies, and [v4 is thus a 'breaking change'](https://github.com/unitycontainer/unity/commit/4fc7c789aecf4415db2688753dabe18421296222). Not totally sure why they decided to do that, as there aren't any other real additions in over a year.

Guess we'll have to push a new release if we want to support Unity 4.0.0

**Comment by brianlagunas** [comment]
We are looking into signing our assemblies too, so we may consider upgrading our support for Unity v4 at the same time.

**Comment by brianlagunas** [comment]
Just so you know, Unity was always signed, but the new owners had to sign it with a new key file.  This means any assemblies that referenced an earlier version of Unity (pre v4) was built against a different signing key, and will not work against v4 because it is using a different key.  So, we would have to release an update that references Unity v4 in order for that to work.  Right now, there is no functional difference with v4, so we don't see a benefit of changing our support Unity version just yet.
