### ISSUE TITLE
how to make it Unity Interception works with Prism 7.1.0.431 together ?

### ISSUE THREAD

**Issue by GreatFireWall** [PrismLibrary/Prism#1789]
how to make it works with Prism 7.1.0.431 together ?

I had add nuget packet `Unity.Abstractions`, but get same error result:
```
CS0012  C# The type 'IUnityContainer' is defined in an assembly that is not referenced. 
You must add a reference to assembly.
```

![image](https://user-images.githubusercontent.com/4510984/57180776-bde12000-6ebe-11e9-9ca9-bc27672ea50a.png)

![image](https://user-images.githubusercontent.com/4510984/57180787-c6395b00-6ebe-11e9-8a0a-b946424b7bab.png)

**Comment by dansiegel** [comment]
This is not an issue with Prism. Ask your questions on Stack Overflow

**Comment by Pretasoc** [comment]
I know it is not prism related, but since errors like theese can occur with other Unity packages as well i'll give an short answer here.
Unity changed its signing key somewhere between 3.3X and 5.0. Prism References Unity.Abtractions 3.3.1 for compatibility reasons. Unity.Interception 5.10.1 References Unity.Abstraction 4.3.1. Theese Versions don't share a common public key, so binding redirects will fail. The latest Unity.Interception Version, that uses the old public key is 5.5.6.

**Comment by GreatFireWall** [comment]
Thank you. @Pretasoc 
So, I need to install `Unity.Interception 5.5.6` and which version of `Unity.Abstraction` ?
