### ISSUE TITLE
Prism in 2019, is it dead?

### ISSUE THREAD

**Issue by wize1** [PrismLibrary/Prism#1801]
Hi,

after XLabs made their rep as read-only, I finally decided to change to new MVVM framework, after reading couple of reviews on the net I found that Prism has good reputation for large scale apps.

And what do I see:
The project is 8 years old, yet it still doesn't have detailed and clear documentation for most current version of framework release. It feels like it never even had complete documentation for any of the versions.

Yet, the README.MD is filled with stuff like $10k to get on site support and we will call you "Corporate Sponsor".
Links to Patron subscription and tip of iceberg links to tutorials from author, where he explains how to use very basics of the OLDER version of his framework, but yet you must pay to watch them.

Which raises few questions:

1. Is this project is dead? From my understanding the author is handed over this project to open source community. Yet he is still main and almost only participant in this project.

2. Is this project commercial project? With all these requests on almost forced contributions, is this really still open source?

3. Is this project managed? Are there any management going of this project, because from what I see. The request for documentation has been opened, four times for version 7, and every time it is marked duplicate and to original ticket author responded he hasn’t time to do it.

4. Is this project still advisable to use in 2019? Looking at who is main participants and the way this project is managed, is it still advisable to adopt it in 2019, or will it follow route of XLabs.

I think, if we clarify this now, it will help a lot new users which thinking of adopting this framework to make their decision, if it is right way to go.

**Comment by Coder-Nut** [comment]
@wise1: How long have you been following prism? A day? Two maybe? I have been following and using prism for over five years and if there's one thing I can tell you, it most certainly is not dead. Instead of criticizing something you know nothing about, try doing a bit more research and check ask the recent changes. They have been super busy adding new features and porting much of the code to prism.core for cross platform support. They do this in there spare time as they all have fulltime jobs to pay the bills. I am a Prism Patreon because it helps to compensate them for their hard work. Even that would not be enough to keep me doing it if I received comments like yours all the time. It is open source which also means that the community can update the docs too, and some have, and eventually they will be updated. The code is fairly easy to follow and there are examples and videos available and they do out all in their spare time. Don't be so quick to judge!

**Comment by dansiegel** [comment]
@wize1 sorry but your comments are straight up laughable. Is Prism dead? Dude we're regularly shipping updates. @brianlagunas and I just did a stream on the new features for Prism.Forms 7.2 last week, and he's doing a stream this morning on the new Dialog Service for Prism.WPF today.

It is of course open source, you can see it here on GitHub, you can open issues, submit PR's, or just plain fork it altogether. Is the project managed, yes we do manage it. Frankly I find your comments on "Looking at who is the main participants" to be quite offensive. I do a lot for both the Prism and Xamarin Community, including making sure that developers will have a world class event to help you make major leaps forward in your Xamarin development.

Last but not least, yes we are asking people for contributions for a variety of reasons. 

- We maintain this project in our spare time. Often times when we have to deal with issues for the community this is a direct impact to our personal finances.
- When we take time to come and speak at Meetups, Code Camps or Conferences it is out of our own pockets.
- We receive a lot of support requests from people, many of which work for Fortune 100 companies making hundreds of millions a year with software they use Prism in. Some of these people have made demands on us like we owe them something.

I could continue but I think you should hopefully get the point by now.

**Comment by wize1** [comment]
Well I'm glad I amused you guys, but I think you missed whole point.
You can get all defensive about it and hate me for it, but I did share my opinion and maybe even provoke you for reason.

Maybe, if I also followed this project for FIVE years (in that time I would probably know every line of code and I will not need documentation), I would be super excited about it. But that is whole point, I don't have five years to invest to realize all the benefits of this project, and I do understand that it mostly two guys this whole time is contributing at their spare time. Which makes my question even more valid, is it worth investing in project which mostly dependent on just two guys. 

Another and main thing, that I was trying to get at, is that maybe instead of working on next great technology update, you need to document properly and have easy entry for new guys to what you currently have. That way you will get more guys to join on project and new blood will keep this project more involved. And you will have more contributions from other people, and you guys do more management of direction of the project then spending all your spare time on writing code.
It is nice to build greatest plane in world, but if it takes five years (overexaggerated) to learn how to fly it. 

Then it is not very useful and puts people off from using it.

Whichever way take my criticism or ignore it, I said what I said.

**Comment by brianlagunas** [comment]
@wize1 Prism has over 6.2 million downloads since its first release. We don't have a problem with people using the project. What we have a problem with is the entitlement of the OSS "consumers" that expect an OSS project to be run like a well financed company.  Your position is one of selfishness. You are telling us what we should do better to help you under the guise of trying to foster more community involvement. That's not how it works.

I don't think this is the project for you. You should find another option or roll your own.

**Comment by wize1** [comment]
No problem, to be honest I didn't think you guys would be happy with my post.

But my thought was it would give you something to think about. Good luck with your project.

**Comment by VagueGit** [comment]
You asked a reasonable question @wize1 and didn't deserve the vicious responses. I too looked at Prism and found it too hard to get started as the docs seemed out of date. I too was ridiculed by the maintainers. Their attitude more than anything was the greatest barrier to entry. Perhaps I too am lazy and selfish for not updating the docs on a project I do not understand.
