### ISSUE TITLE
[Bug] INavigationAware methods of view-model requesting navigation are invoked

### ISSUE THREAD

**Issue by moci** [PrismLibrary/Prism#1831]
### Description

A view-model performing a navigation request has its INavigationAware implementation invoked.
The corresponding view (of the view-model performing the request) does not have it's INavigationAware implementation invoked (= correct behavior).

### Steps to Reproduce

See repro link.

### Expected Behavior
INavigationAware implementation is not invoked on both the view and view-model for the class requesting the navigation.

### Actual Behavior
INavigationAware implementation is invoked on the view-model, not the view

### Basic Information

- Version with issue: 7.2.0.1347-pre
- Last known good version: n/a
- IDE: Visual Studio Community 16.1.3

### Reproduction Link

https://github.com/moci/PrismNavigationAwareBehavior

**Comment by brianlagunas** [comment]
Works for me
![image](https://user-images.githubusercontent.com/835562/59616174-24be3f80-90e1-11e9-8e73-01b1c78be71c.png)

**Comment by moci** [comment]
Maybe I'm just not understanding how the INavigationAware interface should work.

To me the INavigationAware interface's on both the View and the ViewModel should either both be invoked or not at all. So I'm expecting either no logging from the shell or always a pair of logs 'Shell V:' and 'Shell VM:'.

But, since you've closed the issue, you are saying that the INavigationAware implementation on a view is treated differently than one on the ViewModel (and that the ViewModel is invoked more often than the View)?

**Comment by brianlagunas** [comment]
It's working exactly how you coded it to work. First off, you aren't doing any navigation "From" or "To" the Shell. The shell is the host of the region, it does not participate in navigation at all.  Since you didn't provide any VM's for VIewA or ViewB, it is inheriting the DataContext from the Shell which is the Shell VM. So where you see 

A V : On navigated to
Shell VM: On navgated to

Shell VM is actually the A VM since it is inheriting the DataContext from it's parent, the Shell.

**Comment by moci** [comment]
Ah, exactly. Thank you!
