### ISSUE TITLE
Is UWP support drop permanent?

### ISSUE THREAD

**Issue by MartinZikmund** [PrismLibrary/Prism#1835]
Seeing the UWP support issues has been closed few days ago, I just want to have a clarification of whether the drop of UWP platform support is permanent or just temporary measure.

**Comment by brianlagunas** [comment]
It's more like indefinite. Maybe one day we will get to it, but not any time in the foreseeable future.

**Comment by robv8r** [comment]
@brianlagunas - What does that mean for those of us who've invested heavily in UWP+Prism applications?  We've tried porting to Xamarin.Forms, but it looks awful and is a pain to work with.

It's unfortunate (not to mention confusing) that you'd drop support for Microsoft's Primary Development Platform.

**Comment by MartinZikmund** [comment]
@robv8r it also matters as Uno Platform is becoming a very attractive and viable alternative to Xamarin.Forms, which means having support for UWP = Uno is quite important.

**Comment by dansiegel** [comment]
@robv8r you have to understand that there is no motivation for us to do this. Neither @brianlagunas or I have clients looking for this. While I understand there are people who would like to see it the simple reality is that it would mean spending hundreds of hours to properly implement Prism for UWP properly. That's not a commitment that either of us can really afford to do without one or more companies stepping up with a large financial contribution to help us deliver this for the community.

@MartinZikmund I completely understand and believe me nothing would make me happier than to see a Prism for Uno/UWP

**Comment by MartinZikmund** [comment]
@dansiegel That's absolutely reasonable 👍 .  I hope sufficient support will come in the future and it will make this possible.

**Comment by brianlagunas** [comment]
@robv8r It means you can either take the code base for Prism for Windows, fork it and maintain it on your own, or move to something else.  Currently their UWP platform does not meet the architectural requirements for Prism to support it. Everything from their threading model, to their navigation, it just isn't built to properly write clean and maintainable applications.

Also, Microsoft does not pay us to support their platforms. We do this in our free time and work on what we are passionate about, enjoy, and actually use in our day to day work. UWP does not fit into any of those categories

@MartinZikmund I am not concerned with trying to support Uno or any other platform out there. We are not a company that gets paid to support everything and everyone.

**Comment by robv8r** [comment]
@brianlagunas @dansiegel - I'm confused.  UWP was supported until version 7.  In fact, the first words on the first page of the [Prism website](https://prismlibrary.github.io/) are:

> Build easily applications in WPF, Windows 10 UWP and Xamarin Forms.

The first sentence of the first paragraph is:

>Prism is a framework for building loosely coupled, maintainable, and testable XAML applications in WPF, Windows 10 UWP, and Xamarin Forms.

Until recently, Prism supported UWP.  Why discontinue an existing codebase?

**Comment by bartlannoeye** [comment]
Prism 6 had support for UWP which grew out of Prism for Windows 8. While that was good enough for most cases, it had a few shortcomings. Patching this wasn't enough. In the early days of 7, we tried to bring in Template10 code, but after a while it was clear that over the years Prism and Template10 had grown apart too much and the approach taken (eg lots of static code) was not something we wanted to keep in Prism, hence everything got stripped again.

As @brianlagunas and @dansiegel said, it's a lot of effort to do it right and it's all free time effort. They're both very occupied with Xamarin.Forms and I haven't been able to put in the time required for a full rewrite of the UWP part. As Brian said, it's not final, but don't expect to see something tomorrow either. We want to be sure we're on the right path before making anything public.

**Comment by brianlagunas** [comment]
@robv8r thanks for letting me know I need to update that text.

**Comment by dansiegel** [comment]
@robv8r 

> Until recently, Prism supported UWP. Why discontinue an existing codebase?

Because it was truly that bad. It required a full rewrite.

**Comment by MartinZikmund** [comment]
@bartlannoeye When the plans change, I would be willing to help out too if my schedule allows.

**Comment by robv8r** [comment]
This is an open source project, so you make the rules.  You're under no legal or moral obligation to me or anyone else who uses your software.  

I've been bragging about Prism since Version 5.x when it was a [Microsoft download](https://www.microsoft.com/en-us/download/details.aspx?id=42572) and then Version 6.x when this project was created.  I've encouraged many people to use Prism (including those who write UWP apps.)

Fast forward to today:

I hope you understand why I feel like your project has abandoned me, our company, and everyone else I've encouraged to use Prism.  Now we have to rip out Prism (which is like ripping out my own heart). 

@brianlagunas advised me to

> ...take the code base for Prism for Windows, fork it and maintain it on your own, or move to something else.

Forking the repo and maintaining Prism for UWP **isn't an option** according to @dansiegel.  

> Because (the existing UWP code) was truly that bad. It required a full rewrite.

This leaves me with one option from @brianlagunas: 

> ...move to something else.  

Rather than rant, I'll move on.  Unfortunately, due to the way UWP was abandoned without warning, as well as @dansiegel stating the UWP codebase was "truly that bad", I can't (in good conscience) continue to recommend Prism to colleagues.

**Comment by dansiegel** [comment]
@robv8r what I'm referring to is the Template 10 merge. We would like to see UWP supported and we've put a lot of work into it. The simple reality is that the effort to provide the community something that we would recommend would be more than we can do without financial support from the companies that are demanding it. Frankly the way your comment reads, comes across very arrogant and entitled. 

You can use whatever you feel is right for you. For WPF and Xamarin.Forms apps Prism continues and will continue to be the best MVVM Framework available to developers. We don't want to put something out that kinda works but really isn't top notch for UWP. If you can't understand that you're welcome to roll your own Framework.

**Comment by brianlagunas** [comment]
@robv8r
> I hope you understand why I feel like your project has abandoned me, our company, and everyone else I've encouraged to use Prism.

I am curious what have you, your company, or the people you encouraged to use Prism have contributed back to the Prism community.

> Now we have to rip out Prism (which is like ripping out my own heart).

I understand your frustration, and appreciate the sentiment. However, this is the risk to every single open source project in existence that does not have any major financial backing.  If you use open source, the licenses clearly says use at your own risk. You are relying on the work of people volunteering their time, expertise, and personal financial resources. At any time, they can change their mind and move on. If you, or your company, does nothing to ensure the projects you rely on are sustained, then you have zero place to complain when those projects no longer exist or are maintained.

Since UWP is so critical to your business needs, I invite you, and your company, to join the Prism team and take the lead on the UWP effort. Help us finally provide full support for UWP. Let the entire Prism community benefit from the work of you and your company.
