### ISSUE TITLE
Exception thrown in OnNavigatingTo is not caught in NavigateAsync

### ISSUE THREAD

**Issue by mrbelk** [PrismLibrary/Prism#1844]
### Description

In a view model that implements INavigationAware with an async OnNavigatingTo method, an exception thrown in that method is not caught in the navigationService.NavigateAsync() call from the calling view model. This results in an unhandled exception and an app crash. It's possible this issue was introduced as a result of upgrading to XF 4 from 3.6.

This behavior is observed on both iOS (12.3.1) and Android (6.0.1)

### Steps to Reproduce

1. navigate to a view model that implements INavgationAware and has an async OnNavigatingTo implementation
2. throw an exception in the OnNavigatingTo method of the target viewmodel

### Expected Behavior

The INavigationResult returned from "await"ing the NavigateAsync should have its "Success" property set to false and its "Exception" property set to the exception thrown in the target view model

### Actual Behavior

The exception thrown in the target view model is unhandled and the app crashes

### Basic Information

- Version with issue: 7.1.0.431
- Last known good version: 7.1.0.431
- Xamarin.Forms version: 4.1.0.555618
- IDE: VS for macOS v8.1.3 (build 19)

### Reproduction Link

https://github.com/mrbelk/PrismOnNavigatingToTest

**Comment by mrbelk** [comment]
This also occurs using Prism 7.2.0.1038-pre

**Comment by dansiegel** [comment]
This is expected behavior. When you have `async void` the async process is not actually awaited so the Navigation Service cannot catch any exceptions there. This is your responsibility to catch exceptions and handle them. When you use IInitializeAsync in 7.2 I would expect an exception there to bubble up and return an unsuccessful NavigationResult but if you again did async void with IInitialize you would continue to see unhandled exceptions in your code would not be caught by the Navigation Service.

**Comment by mrbelk** [comment]
OK. Fair enough. I guess it was just a very happy accident that it worked up until XF4, then. So if I change my INavigatingAware.OnNavigatingTo (and in the future IInitialize) and INavigationAware.OnNavigatedTo to handle their own exceptions, how do I leverage the INavigationResult that's returned in the NavigateAsync call to pass those exceptions back to the caller?
