### ISSUE TITLE
Dialogs in Xamarin Forms can't RequestClose without a handler first being given to Show() [Bug] [XF]

### ISSUE THREAD

**Issue by UnreachableCode** [PrismLibrary/Prism#1883]
### Description
Hi everyone. I've been trying out the new dialog service in 7.2.0.1367 for Xamarin Forms. I've been able to get it working but only when providing a callback handler. Otherwise I get a vague null reference exception.

This isn't explained in the [release notes](https://github.com/PrismLibrary/Prism/releases/tag/v7.2.0.1367) or the [spec](https://github.com/PrismLibrary/Prism/issues/1814) or [PR](https://github.com/PrismLibrary/Prism/pull/1825) but I think it should be. I think it should also be possible to not provide a handler and for the dialog to just dismiss.

### Steps to Reproduce
1.  Create a dialog View and ViewModel as outlined in the [release notes](https://github.com/PrismLibrary/Prism/releases/tag/v7.2.0.1367).
2. Open your dialog when the app is running using `dialogService.ShowDialog("MyDialog")`
3. Fire your close command which should call `RequestClose(null)`.

### Expected Behavior
Dialog should close.

### Actual Behavior
Program crashes with null reference exception. If a callback is provided, then this doesn't happen, like so: `dialogService.ShowDialog("MyDialog", CloseDialogCallback)`.

### Basic Information
- Version with issue: Prism 7.2.0.1367
- Last known good version: N/A, new feature.
- Xamarin.Forms version:  4.1.0.618606
- IDE: Visual Studio for Mac Community 8.2.3

**Comment by brianlagunas** [comment]
Closing as no reproduction app provided.

**Comment by UnreachableCode** [comment]
I'm afraid this doesn't fix it

<img width="771" alt="Screenshot 2019-08-21 at 17 39 42" src="https://user-images.githubusercontent.com/1167553/63446583-c2fcb780-c43a-11e9-8ca6-6f526d06b937.png">

**Comment by brianlagunas** [comment]
We'll need a repo app then

**Comment by UnreachableCode** [comment]
On it

**Comment by UnreachableCode** [comment]
It's going to be a little longer until I can reproduce this on a repo app.

**Comment by hro-it** [comment]
> I'm afraid this doesn't fix it
> 
> <img alt="Screenshot 2019-08-21 at 17 39 42" width="771" src="https://user-images.githubusercontent.com/1167553/63446583-c2fcb780-c43a-11e9-8ca6-6f526d06b937.png">

Would like to second that I'm receiving the exact same `NullReferenceException` at the exact same line. Only solution is to provide a callback handler even if unnecessary.

**Comment by hro-it** [comment]
This issue needs to be reopened as I may have discovered the issue to it.

It appears that there is an extension helper interface known as `IDialogServiceExtensions` that aids the developer in offering overloads for a multitude of scenarios. However, they are merely call the original method signature `ShowDialog(string name, IDialogParameters parameters, Action<IDialogResult> callback`. 

The trick is that in this particular implementation of the interface `IDialogService` the callback is always assumed to be valid instead of a null argument.

Implementation of method signature `ShowDialog(this IDialogService dialogService, string name)` in `IDialogServiceExtensions` shows that you are deliberately just passing a null value. A check needs to be implemented into the `DialogService` class to ensure that the callback is valid prior to call when executing `void DialogAware_RequestClose(IDialogParameters outParameters)`.

I do not want to perform a pull request as I do not have an extremely thorough understanding of all the code in this new feature yet, but hope that this will send everyone down the correct path in regards to debugging.

**Comment by dansiegel** [comment]
@hro-it if you'd like to provide a sample that reproduces the issue I'd be happy to reopen the issue

**Comment by hro-it** [comment]
> @hro-it if you'd like to provide a sample that reproduces the issue I'd be happy to reopen the issue

https://github.com/hro-it/PrismDialogIssueApp

Sorry that took so long. Had some issues with Android emulation and the new Windows Sandbox interfering with one another. This problem is reproducible on both Android and iOS.

**Comment by dansiegel** [comment]
@hro-it thanks for providing a sample. I'll look into this as soon as I get a moment.
