### ISSUE TITLE
[Enhancement] Use XamlBehaviors for WPF

### ISSUE THREAD

**Issue by tibel** [PrismLibrary/Prism#1897]
## Summary

Currently for WPF a private version of _System.Windows.Interactivity.dll_ is included. For supporting WPF on .NET Core a migration to [XamlBehaviors for WPF](https://github.com/microsoft/XamlBehaviorsWpf) is needed.

## API Changes

None. But it is breaking as the assembly and namespace (including XAML namespace) have changed.

## Intended Use Case

Having one behaviors library only.

**Comment by brianlagunas** [comment]
I'm on that team, and unfortunately we are not getting the support from Microsoft that we need. The actual .NET Core 3 PR hasn't even been merged yet because we can't get a CI/CD build process setup by MS.  If they give the community full control, they'll want to remove the "Microsoft" name from it.  So, there are some decisions that have to be made by MS first.

Besides being a major breaking change, I am not confident in this package's future yet.  I'm not even sure if keeping this issue open is worth it or not.

**Comment by tibel** [comment]
Is there anything we can do to push MS to make that decision? As the current situation is quite disappointing.

Thanks for your fast reply and feel free to close this issue if you think it is not worth keeping it open.

**Comment by brianlagunas** [comment]
Unfortunately it's one of those "wait until someone at MS has time for it" kind of things. I'll leave it open for now. I can always close it later 😄

**Comment by brianlagunas** [comment]
It seems we are targeting a Nov 4th ship date for the behaviors with .NET Core 3 support. Let's hope we meet our goal.

**Comment by brianlagunas** [comment]
We met our goal! We shipped a new update to the Behaviors. Now I just have to decide if I am going to force a breaking change in order to make the switch.

Note: The WPF behaviors has Prism's EventToCommand so we can now remove it from Prism 😄

**Comment by tibel** [comment]
I think a breaking change now is hurting less than in a few month when more apps are on .NET Core already.

**Comment by brianlagunas** [comment]
Fixed
