### ISSUE TITLE
[Bug] NullReferenceException navigation to TabbedPage when CurrentPage is null

### ISSUE THREAD

**Issue by kimbirkelund** [PrismLibrary/Prism#1959]
### Description

Navigating to a `TabbedPage` which doesn't initially have a CurrentPage set causes a `NullReferenceException` in [PageNavigationService.OnNavigatedTo](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L750) when it attempts to `tabbedPage.CurrentPage.BindingContext`.

### Steps to Reproduce

1. Create a new blank Prism app
2. Change `MainPage` to inherit `TabbedPage` without specifying any tabs
3. Run Android project (running the iOS project gives another exception)

### Expected Behavior

An empty app.

### Actual Behavior

A swallowed exception in the `NavigateTo` call in `App`.

### Basic Information

- Version with issue: latest version as of writing
- Xamarin.Forms version: latest version as of writing

### Reproduction Link

[BlankApp1.zip](https://github.com/PrismLibrary/Prism/files/3916117/BlankApp1.zip)

While this is a pretty contrived example, I have an app where the list of tabs is populated asynchronously from the view model.

**Comment by dansiegel** [comment]
Your sample works as expected. Your code however is the cause of the "Swallowed Exception". The Prism NavigationService catches all exceptions by design and return them as part of the NavigationResult. Since you ignore the result your code will continue as if nothing is wrong. Update your code as follows and you'll see you hit the breakpoint which is what we expect would happen when you encounter an exception in the Navigation.

```cs
var result = await NavigationService.NavigateAsync("NavigationPage/MainPage");
if(!result.Success)
{
    System.Diagnostics.Debugger.Break();
}
```

**Comment by HanRuibin** [comment]
view it on github



---Original---

**Comment by kimbirkelund** [comment]
Fair enough that the swallow is my fault, but don't you consider the exception itself an issue?
