### ISSUE TITLE
[Bug] [XF] OnNavigatedFrom not called when using absolute navigation

### ISSUE THREAD

**Issue by Peseur** [PrismLibrary/Prism#1974]
### Description

Hi, I think there has been such a bug in the past but it seems it is back.
My OnNavigatedFrom callback in my view model does not get called when I NavigateAsync using absolute syntax.
Navigating using relative syntax (i.e. basically without the trailing '/') makes the OnNavigatedFrom callback get called.

I have uploaded a minimal project in this repo to reproduce the issue:
https://github.com/Peseur/PrismNavigationTest

### Steps to Reproduce

1. Put a breakpoint inside OnNavigatedFrom of my ViewModels PrismContentPage1ViewModel and MainPageViewModel.
2.  Change page using the MasterDetailPage menu (you can see page has changed because different texts are written on them)
3. OnNavigatedFrom is not called.

### Expected Behavior

OnNavigatedFrom get called.

### Actual Behavior

OnNavigatedFrom is not called.

### Basic Information

- Version with issue: 7.2.0.1367
- Last known good version: can't remember but I do not use OnNavigatedFrom for a longtime
- Xamarin.Forms version: 4.4.0.991265 but was not working in 3.6.0.344457 either
- IDE: Microsoft Visual Studio Community 2019 Version 16.4.2

### Reproduction Link

https://github.com/Peseur/PrismNavigationTest

**Comment by brianlagunas** [comment]
This is working as expected. The OnNavigatedFrom is getting called. However, it is getting called from the PrismMasterDetailPage1ViewModel, because this is where the navigation is occurring. If you were expecting it to be called on the DetailPage, you must navigate from the detail page.

Also, I hope this sample was used just to demonstrate the issue you thought you had and not how you are actually trying to implement your MDP navigation.  This is NOT how you would perform MDP navigation in a production application.

**Comment by Peseur** [comment]
Hi @brianlagunas , 

Thanks for your response.

> Also, I hope this sample was used just to demonstrate the issue you thought you had and not how you are actually trying to implement your MDP navigation. This is NOT how you would perform MDP navigation in a production application.

It seems I haven't understood very well how to do MDP navigation.
You said that I shouldn't implement MDP navigation like this in a production app. Could you explain how am I supposed to do, then ?

**Comment by brianlagunas** [comment]
@Peseur please review the Prism for XF samples https://github.com/PrismLibrary/Prism-Samples-Forms
