### ISSUE TITLE
Why the support for UWP was dropped?

### ISSUE THREAD

**Issue by mklemarczyk** [PrismLibrary/Prism#2025]
Hello there is no clear message why support for UWP was dropped.
The documentation states that UWP platform is supported while there is only way to use Xamarin to have Prism embedded into UWP application. This creates strong dependency on the Xamarin library.

Does anybody provides support for Prism.Unity library for UWP platform?

If non is answered I will provide support for my own which will cause fragmentation of Prism. 

The UWP was just removed: https://github.com/PrismLibrary/Prism/commit/6d23d45b2e7689a7475ec1d7377e17405b526e73

**Comment by dansiegel** [comment]
@mklemarczyk actually it was not "just dropped" see issue #1745

**Comment by mklemarczyk** [comment]
Can it be pick up by the community and carried on?
Will you release if community port the library for UWP?

**Comment by dansiegel** [comment]
Note that Brian and I have put this out there for all of the companies that love Prism and want to be able to use Prism for their UWP apps. Given the large effort in developing, maintaining, producing samples, docs, and trainings for it... we are fully willing to take on the effort if we can find one or more companies that are willing to financially fund the effort. Since neither of us currently have customers demanding UWP there is no way that we can otherwise justify the effort. 

As for it being a community effort I'm not going to say it's never going to happen but I will say it's very unlikely. People often forget that I myself came from the community and everyone that uses Prism could potentially join the Prism team in time as I did. That said it takes a commitment beyond submitting a few PR's and neither Brian or I are really interested in accepting a PR for UWP support that we merge and then get stuck having to maintain.
