### ISSUE TITLE
[Breaking] Remove the IsActiveChanged event

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#2042]
## Summary

Prism does not use the IsActiveChanged event in IActiveAware at any point. There is no real reason for this to be part of the API and is a cause of questions for how to use it, when there aren't really reasons for it to be part of Prism...

## API Changes

Remove: IActiveAware.IsActiveChanged

**Comment by Jesus805** [comment]
Hi Dan,

I am interested in implementing this issue. IActiveAware.IsActiveChanged is implemented in CompositeCommand which subscribes to each Command's IsActiveChanged (if monitorCommandActivity is true). When IsActiveChanged is fired, the CompositeCommand requeries CanExecute. Removing IsActiveChanged will remove this functionality, is that okay?

**Comment by brianlagunas** [comment]
Great find @Jesus805 . I will have to look into this. If CompositeCommand relies on this event, then this will not be removed.

**Comment by d3fkn1ght** [comment]
Why does the CompositeCommand register for the Command's CanExecuteChanged event, while also having the ability to be configured, via the _monitorCommandActivity property to subscribe to a Command's IActiveAware.IsActiveChanged event (provided the event implements IActiveAware)?  I only ask because it seems to be redundant though I a sure there is a good reason for it.

**Comment by brianlagunas** [comment]
@d3fkn1ght because the CompositeCommand listens for IActiveAware value changes and then raises the CanExecuteChanged event for commands.

The IActiveAware.IsActiveChanged will not be removed.
