### ISSUE TITLE
NuGet package versions accross all Prism packages

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#212]
Are we planning to keep the version of all packages in sync (and thus pushing unnecessary patch updates on some packages) or can we have multiple versions within the same minor? Like:

Prism.Core 6.0.1
Prism.Unity 6.0.2
Prism.Autofac 6.0.2-prerelease01 (and 6.0.1 stable)

If we allow this, do we sync on minor (6.1.0) or major versions only?

**Comment by brianlagunas** [comment]
Good question.  I think we should update a package for sake of keeping version numbers the same.  Practically speaking, there will be some assemblies that don't receive any updates, while others (like WPF or XF) will receive a lot of updates.  We should only update a package version if it needs it.  I'm not sure about syncing on major versions or not.  I guess we can ask that question again when we get to v7 :)

**Comment by brianlagunas** [comment]
Okay, we only need to sync the assembly versions when either we are releasing a new major version of Prism (like Prism 7), or if all assemblies get modified with the same minor feature.  For example, I just incremented all the Prism for WPF assemblies to Prism 6.1, because I changed all of them to have the assemblies signed during the Release-Signed build configuration.

Going forward, we only increment the assembly that was changed.  So if only Prim.Wpf.dll got new features/bug fixes, then only that assembly's version will be modified.

I am going to implement the use of the AssemblyInformationalVersion attribute too.  This should help us keep things straight.

I hope that makes sense.
