### ISSUE TITLE
[Bug] NavigateAsync removes back button after pushing new screen into view

### ISSUE THREAD

**Issue by tbaggett** [PrismLibrary/Prism#2162]
### Description
The Back button disappears after pushing a new screen onto the app's root NavigationPage when it already contains a child TabbedPage.

I have an app with the following screen structure:

- App Root (Custom class derived from NavigationPage)
    - TabbedPage
        - NavigationPage
            - ContentPage
        - NavigationPage
            - ContentPage
        - NavigationPage
            - ContentPage
        - NavigationPage
            - ContentPage

I have a button on the last tab's content page. It is expected for users to be taken to a screen without the tab bar being visible. 

To achieve this, I push the new screen as a child of the App's root navigation page. The push occurs as expected but the back button disappears once the transition is completed, leaving the user with no way to go back to the tabbed view.

Performing the same steps in Xamarin Forms without Prism works as expected. A repo that demonstrates this is available at https://github.com/Jfcobuss/HideTabbarExample/tree/master/HideTabbarExample/HideTabbarExample.

### Steps to Reproduce
1. Build the provided repro project and launch on iOS
2. Switch to tab 4, the last tab on the right
3. Tap the button labeled "Tap to Push Page Onto App Root Page"
4. The "App Root Child Page" will be pushed onto the screen by the TabPageChild4ViewModel's bound command. It locates the AppRootPageViewModel from the App's MainPage, then calls its public NavigateAsync method to push an instance of AppRootChildPage onto the root page's stack.

### Expected Behavior
The AppRootChildPage instance should be pushed onto the app's root navigation page's stack. A Back button should be available for the user to return to the previous child, which is the tabbed page.

### Actual Behavior
The AppRootChildPage instance is pushed onto the screen but the Back button is removed once the transition is completed. The user has no way to return to the tabbed page.

### Basic Information

- Version with issue: Prism.DryIoc.Forms 7.2.0.1422
- Last known good version: NA
- Xamarin.Forms version: 4.5.0.725
- IDE: VS for Mac 8.7 (build 2037)

### Screenshots
Animated GIF recording of iOS Simulator running provided repro project with animations slowed down:
https://drive.google.com/file/d/1q3Oi9xNgjzrkLaUZtI4sBBPj_PDbENTB/view?usp=sharing

### Reproduction Link
https://drive.google.com/file/d/1u3e1p0mZq46yOp9O3B20747P4xo0M5t8/view?usp=sharing

**Comment by dansiegel** [comment]
@tbaggett there is so much wrong in your sample, to be blunt I don't know where to start. Your sample is full of bad practices, and I highly suggest that you spend some time reviewing samples and docs.

Besides the method name and curly braces, there isn't one line here that didn't completely violate the MVVM pattern, and ignore Prism's guidance. Not to mention the fact that you've navigated from the wrong page which is why you're getting the result that you are.

```cs
private void PushPageOntoRoot()
{
    if (Prism.PrismApplicationBase.Current?.MainPage is AppRootPage appRootPage &&
        appRootPage.BindingContext is AppRootViewModel vm)
    {
        var result = await vm.NavigateAsync(nameof(AppRootChildPage));
    }
}
```

![image](https://user-images.githubusercontent.com/3860573/91194356-ec36d000-e6ac-11ea-9694-95474102e601.png)

From what you've described you want to Navigate from your TabbedPage which is what I've done and you see the result in the image here. I suggest you look at CompositeCommands, and while that's all you really need for your issue I might also suggest that you look at the IEventAggregator which could be another approach to solve these sorts of issues.

**Comment by tbaggett** [comment]
Hi Dan,

Thank you for looking into my issue and replying. The sample I provided was a quick example based more or less on the vanilla XF sample that I shared. It wasn't meant to show best practices and isn't how I would implement this in production code. I agree that the code you highlighted is awful. :-)

I would've used an event aggregator to do this normally. I think the end result would've still been the same since I was navigating from the wrong VM, as you pointed out. 

I haven't used CompositeCommands before, so I will look into that. It seems better suited to this based on a quick review of the Prism documentation.

Thanks again for looking at this, and all the work you and others have put into Prism.
