### ISSUE TITLE
IActiveAware.IsActive called twice when composing with .RegisterViewWithRegion

### ISSUE THREAD

**Issue by erikbarke** [PrismLibrary/Prism#2197]
### Description

This happens when a view (ViewA) with a viewmodel implementing `IActiveAware` is registered with `.RegisterViewWithRegion` and a second view (ViewB) is registered with the first view's regionname.

Possibly related issuse: #1030

### Steps to Reproduce

Using the repro provided:

1. Set a breakpoint in the `IsActive` setter in `ViewAViewModel`
2. Run the app
3. `IsActive` gets hit twice
4. Comment the line `.RegisterViewWithRegion("ViewARegion", typeof(ViewB))` in `MainModule`
5. Run again
6. `IsActive` gets hit once

### Expected Behavior

IActiveAware.IsActive should get called once

### Actual Behavior

IActiveAware.IsActive is called twice

### Basic Information

- Version with issue: Prism.Core/Prism.Unity/Prism.Wpf 7.2.0.1422
- IDE: VIsual Studio 2019

### Reproduction Link
[IActiveAwareRepro.zip](https://github.com/PrismLibrary/Prism/files/5273538/IActiveAwareRepro.zip)

**Comment by brianlagunas** [comment]
This is by design. You are injecting ViewB into a region in ViewA. You have not set a DataContext for ViewB. Therefore, ViewB.DataContext is inherited from it's parent ViewA which is ViewAViewModel. You're using the same VM for 2 different views, each of which get IActiveAware called on them separately.

**Comment by erikbarke** [comment]
By design, why... I have quite a few views with no viewmodel that only serves as a visual container, do I have to use dummy viewmodels for each and every view to disable this behavior? Or is there an option or attribute I can use to tell Prism that I really, really don't want a viewmodel/datacontext for a specific view? You'd think that _not_ setting the attribute `prism:ViewModelLocator.AutoWireViewModel="True"` would suffice.

Anyway, end of rant, thanks for your swift reply!

**Comment by dansiegel** [comment]
@erikbarke Prism is designed to help you architect an MVVM application. The assumption should ALWAYS be that you want a ViewModel attached and as a result AutoWireViewModel should always be assumed to be true if you didn't set it since this is the norm for apps developed with Prism. It's a complete edge case where you do not want this and it's in those cases that you should be opting-out. An opt-in just doesn't make sense.

**Comment by brianlagunas** [comment]
@erikbarke I already explained why this is happening. This has nothing to do with Prism at all. This is property inheritance. The DataContext of your ViewB is inheriting the parent context of ViewA. This is how WPF works

**Comment by erikbarke** [comment]
@dansiegel, that's exactly what I said, I want to opt out and is there a way to do it other than using a dummy viewmodel?

**Comment by erikbarke** [comment]
@brianlagunas, now you've explained it, thanks 👍

**Comment by dansiegel** [comment]
Setting ViewModelLocator.AutoWireViewModel to false will keep Prism from adding a ViewModel for you. However regardless of the platform you should expect any element that does not have a Binding/DataContext set to automatically inherit the ViewModel of its parent once it's been parented.

**Comment by erikbarke** [comment]
Then what's the purpose of setting autowiring to true in the first place? If a viewmodel is always assumed? Shouldn't this just be default behavior in Prism?

This is still (from the eyes of a programmer, not a seasoned Prism dev) kind of quirky, unpredictable behavior: if I set autowiring to true, I get a viewmodel as datacontext. If I set it to false or don't set it at all, all bets are off, I might get a viewmodel or I wont, that's kind of flaky... What I'm asking for is a way for Prism to somehow circumvent this wpf platform behavior by setting autowiring="false" (or autowiring="noway") and then Prism makes sure the datacontext is null, for example.

**Comment by brianlagunas** [comment]
@erikbarke As I said earlier, this is not a Prism issue. This is how WPF works. Prism does not require a VM. If you want to use one, Prism gives you an easy way to do that with the ViewModelLocator. A DataContext can be anything in WPF. It's just the source of your data. Prism is not going to try to change the default behavior of WPF, even if that was possible. That would be a horrible thing for Prism to try and do, and would definitely result in a truly quirky and unpredictable behavior.

**Comment by erikbarke** [comment]
>  and would definitely result in a truly quirky and unpredictable behavior.

Agree.
However, I still think that Prism calling its own api twice on the same viewmodel is an issue that should be fixed in Prism. I'm proposing checking if autowiring is set to false on a view before triggering IActiveAware.IsActive, or if that would wreak havoc on too many existing applications, introducing a third option for the autowiring attribute.

**Comment by brianlagunas** [comment]
Your understanding of the problem is not correct. Therefore, your proposed solution is not correct. This is something you need to fix within your own app architecture and how you are creating/composing your views. This is not a Prism issue.

**Comment by erikbarke** [comment]
> Your understanding of the problem is not correct.

@brianlagunas, It's called "thinking outside the box", try it, you'll like it 😉

**Comment by dansiegel** [comment]
@erikbarke You clearly don't understand how these application frameworks work. WPF has no way of knowing magically what you want. It's default behavior is to assign a DataContext to a child element that does not have a DataContext. This is why for instance you can bind to a command in your ViewModel on a button that's you've added to the View. When you add the Button to a parent it will inherit the DataContext allowing it to see the ViewModel of the parent View. This will happen any time that a DataContext is null. 

Prism simply helps you to assign a ViewModel to the DataContext allowing you to do less work. When you opt out of this behavior from Prism it doesn't affect how WPF will behave. Xamarin.Forms, UWP/WinUI/Uno also do the same for the same reasons.

**Comment by erikbarke** [comment]
Umm, could you guys please stop with the constant barrage of WPF tutorials and telling me I "clearly don't understand"? Yes, I know that injecting ViewB into ViewA will give me the same instance of ViewModelA as datacontext on both ViewA and ViewB due to WPF property inheritance, we clear on that one now? This is not what I'm trying to discuss here, I'm trying to _discuss the fact that Prism, not WPF, calls IActiveAware several times on the same instance of a viewmodel_ and I'm brainstorming to find a solution, work with me here please.

Now, poking around in the source code the problem actually seems easy to fix:

https://github.com/PrismLibrary/Prism/blob/261790736d7f73491d6baffcd35de6afee27f97b/src/Wpf/Prism.Wpf/Regions/Behaviors/RegionActiveAwareBehavior.cs#L69
https://github.com/PrismLibrary/Prism/blob/261790736d7f73491d6baffcd35de6afee27f97b/src/Forms/Prism.Forms.Regions/Regions/Behaviors/RegionActiveAwareBehavior.cs#L61
(and a handful more places in Prism.Forms as far as I can tell)

Why don't just check in the `Action` body if `IsActive` is already set to the target value before setting it again? It seems there are plenty of unit tests covering those parts of the code, so this probably wont break any existing functionality.

**Comment by brianlagunas** [comment]
Property inheritance is just the first part of this. The second part is the fact that you are injecting another view into a different regions using that same viewmodel instance. Prism is doing exactly what it is supposed to. When a view in added to a region, it calls all required interfaces. IActiveAware isn't the only one. If you added other Prism interfaces those would get called too, because Prism is working exactly how it should. Prism does not, nor can it, track instances of view models. It only works against the DataContext of a view being injected into a region.

Even your proposed "fix" isn't actually a fix. Prism will still call the IActiveAware interface, but it will do an extra call to the getter, invoking any code in that code body, before setting the value. Which is even worse. It is your responsibility to check incoming values of your properties before setting them.

Also, your requested changes can most definitely break existing apps. You're only thinking of the unit tests but not of all the code that has been written for Prism apps in production over the last 13.2 million downloads. Some apps actually expect IActiveAware property to be called regardless of its current value.

If you don't want your second view to have a dataContext, nor inherit its parent DataContext, then in the code behind just set it to 'DataContext = this'. Thats it. You fixed it.

We will not be changing the behavior of Prism to avoid setting the IActiveAware property. This is not a Prism issue, its an issue with your app structure.

**Comment by erikbarke** [comment]
We've finally discussed the implementation of the IActiveAware interface and the implications of trying to change anything on it, that's all I wanted. Thanks  @brianlagunas.

**Comment by erikbarke** [comment]
> When a view in added to a region, it calls all required interfaces. IActiveAware isn't the only one. If you added other Prism interfaces those would get called too, because Prism is working exactly how it should.

So it's not only IActiveAware that's broken, that whole part of the abstraction over WPF is.

> Even your proposed "fix" isn't actually a fix

I had another proposal that was ignored by you.

>  You're only thinking of the unit tests but not of all the code that has been written for Prism apps in production over the last 13.2 million downloads.

You're assuming things about me and my competence, again. Please don't do that.
