### ISSUE TITLE
Add an .editorconfig file

### ISSUE THREAD

**Issue by frogger3d** [PrismLibrary/Prism#22]
to standardize on tab size and reduce line ending whitespace.

http://editorconfig.org/

**Comment by brianlagunas** [comment]
This looks like spam to me.

**Comment by frogger3d** [comment]
Not spam, just a suggestion. The dotnet/corefix team also uses it if that means anything to you.

**Comment by brianlagunas** [comment]
What benefit does this provide to this project?

**Comment by Michael-DST** [comment]
And/or a ReSharper.DotSettings file we can use ensure code is compliant with this repo would be nice, too.

You can also [vote for my feature idea](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7066885-enable-abstract-syntax-tree-source-files-via-rosly) so things of this nature become an antiquated, obsolete thing of the past... as they should be.:smile:  :innocent:

**Comment by brianlagunas** [comment]
Reopening, because this is not spam.

**Comment by omares** [comment]
The usage of editorconfig is very limited. Mostly there is no IDE supporting it by default, most of them need a plugin to enable it. So questioning here what advantages do we expect from that? Consistent formatting cannot be an option because you have no way in enforcing it.

So i would vote against it.

**Comment by brianlagunas** [comment]
I tend to agree with @omares, but I will leave this issue open just in case the community would like to elaborate.

**Comment by sgrassie** [comment]
>Consistent formatting cannot be an option because you have no way in enforcing it.

You've never used Stylecop or FXCop then?

editorconfig solves the very real problem of some people preferring to use tabs and some people preferring to use spaces in the settings for their editor. This can cause an adverse effect with well intentioned contributions and patches messing up the source code because their tabs/spaces are inconsistent with the implicit defaults in the rest of the project, and nobody likes messy source code.

Examples in other projects
  - [Roslyn](https://github.com/dotnet/roslyn/blob/master/.editorconfig) 
  - [corefx](https://github.com/dotnet/corefx/blob/master/.editorconfig)

**Comment by Michael-DST** [comment]
> editorconfig solves the very real problem ...

This is indeed a very really problem, but I would just like to emphasize that in no way does a tool truly "solve" it (yet).  What it does is force the preferences of an arbitrary subset of collaborators (or maybe just one) -- and their definition of "style" -- upon a repository.  This is a very narrow, limiting, and confining approach.  And while it is a "solution," it could be greatly improved (and I yearnnnnnnnnn for the day it is.!).  Stylecop should be a file format if anything.  "Style" is in the eye of the beholder, after all, and no one ever agrees on what _that_ is ... or even if Stylecop is "right."

With all that said, this approach _is_ currently the best way of addressing this (very real) issue (unfortunately).  The best the rest of us can do is bitch about it (I have to provide value _somehow_ :innocent:) until some clever bunnies start working some magic w/ Roslyn.

**Comment by bartlannoeye** [comment]
@Michael-DST people are already working with Roslyn on this subject: [how about a test that fails if your usings aren't sorted or you're using tabs for indents](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/tests/OmniSharp.Tests/CodingGuidelinesFacts.cs). Maybe it's a first small step to the ultimate tool. Then again ... anyone using tabs instead of spaces for indents shouldn't be given a keyboard :wink: .

I think some general coding guidelines are very useful, but forcing a code style that regulates everything might be a step to far and scare away some contributors.

**Comment by Michael-DST** [comment]
Hahaha... I'm squarely in Team Tabs, so you can appreciate my desire for such a tool. :sunglasses: This is one of those things that if I had all the time in the world, I would make it myself.  Style discussions (that more times than not always end in arguments) are just the worst, and just thinking about how they could be completely unnecessary with the right tooling makes it all the more so.  But, Roslyn is here now.  Maybe there's only just a few more years of this left to endure (one can hope!). :)

**Comment by Michael-DST** [comment]
Wow, guess I am not in as much of a minority as I thought:
http://stackoverflow.com/research/developer-survey-2015#tech-tabsspaces

Go Team Tabs. :wink:

(But really, go "[Team .ast](http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7066885-enable-abstract-syntax-tree-source-files-via-rosly)" -- wherever they may be.)

**Comment by brianlagunas** [comment]
This is not a high priority for us, and probably not worth the effort at this time.
