### ISSUE TITLE
[Enhancement] Support FlyoutPage from Xamarin.Forms 5

### ISSUE THREAD

**Issue by dm-CaT** [PrismLibrary/Prism#2239]
## Summary

It's planned to rename MasterDetailPage in Xamarin.Forms 5 to FlyoutPage. It will great if aligned version of PrismLibrary be released (pre-released).

[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-pre3#masterdetailpage-renamed](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-pre3#masterdetailpage-renamed)
## API Changes
Add support for new MasterDetailPage naming: FlyoutPage.Flyout

## Intended Use Case

This feature will be needed after migration to Xamarin.Forms 5

**Comment by pasha-o** [comment]
With forms 5.0 out, would this name change be supported in prism?

**Comment by dansiegel** [comment]
I don't have time to deal with it personally right now. However it is open if someone from the community would like to propose the API changes and then submit a PR once the proposed API changes are approved.

**Comment by eltra-ch** [comment]
It looks like, this is not only the name change issue, since update to 5.0 I get the warning "Warning: An Unknown Page type ProjectA.Views.MainView was found walk walking the Navigation Stack. This is not supported by the DialogService" - and the dialog doesn't pop up any more (MainView is of course the brand new FlyoutPage).

**Comment by dansiegel** [comment]
The FlyoutPage is not supported by Prism 8. It is planned for 8.1, but we haven't updated it yet. This is something that is in the works.
