### ISSUE TITLE
[Enhancement] NullReferenceException Handling For ContainerLocator.Current

### ISSUE THREAD

**Issue by ArdentLogician** [PrismLibrary/Prism#2293]
## Summary

The new `ContainerLocator` has effectively no exception handling in it, which allows a `NullReferenceException` to be thrown by `ContainerLocator.Current` from within Prism itself. Because Prism ensures this is always initialized properly, this cannot happen at runtime of an application, but it can happen in integration and unit testing scenarios, especially when attempting to test modules. I would suggest something as simple as throwing an `InvalidOperationException` with an appropriate message in the `.Current` property when a provider has not been set.

## API Changes

No API changes should be required.

## Intended Use Case

An example case where this currently causes a problem is an integration test looking to test that a module has registered everything expected of it and that the registrations can be properly resolved (i.e. all dependencies are in place etc.). In the case I've found, using Prism's `IRegionManager.RegisterViewWithRegion(...)` methods can encounter a null reference exception which cannot be diagnosed without downloading and examining the Prism source code.

**Comment by brianlagunas** [comment]
This would be a great enhancement. It's the small things that are really helpful.  Thanks for this suggestion.

**Comment by dansiegel** [comment]
While I appreciate your issue around Unit Testing, I do not want to introduce a breaking behavior change. This really is operating as designed. Let's say that you have some code that has already set the delegate and you choose to set it again, but nobody has called ContainerLocator.Current yet... The second delegate wins... 

This is designed intentionally so that you can check to see if it has been configured yet or not like:

```cs
if(ContainerLocator.Current is null)
    ContainerLocator.SetContainerExtension(CreateContainerExtension);

var container = ContainerLocator.Current;
```

I believe a more useful thing here is to ensure that the docs reflect the information you need.
