### ISSUE TITLE
[Enhancement] Add Virtual Method Supporting Scoped Regions to RegionNavigationContentLoader

### ISSUE THREAD

**Issue by ArdentLogician** [PrismLibrary/Prism#2294]
## Summary
Enhance the `RegionNavigationContentLoader` to be inheritable with hook points for adding scoped manager functionality. 

Currently, when attempting to do scoped managers, the recommended solution includes copying the entire class for the existing loader (and previously the container specific loader (i.e. `UnityRegionNavigationContentLoader`)) and then modifying the code to suit. This was fine as long as the code was stable, but the changes for Prism 8 have resulted in a change in this piece of code, effectively potentially breaking every application that uses scoped regions. 

Further, the newest version of the code references `internal` members for the automatic viewmodel wireup functionality. This means the code cannot be copied verbatim; a situation which would be resolved by an inheritance based solution.

## API Changes
No breaking changes to the API would be expected, but there would be the addition of a protected member method to `RegionNavigationContentLoader`.

The `LoadContent(...)` method would be altered to extract the `region.Add(view);` line at the end into a virtual method potentially called `AddContentToRegion(IRegion region, object view)`. This would allow inheritors to add logic to determine the call that would be made in place of `region.Add(view)` such as using `region.Add(view, null, true)` when the logic has determined that a scoped region is required.

## Intended Use Case
While an edge case, part of the recommended solution for dealing with scoped region managers is (or at least was) to customize Prism by re-writing the `RegionNavigationContentLoader` class and registering the replacement during the startup of the application. Providing this hook method would dramatically improve the maintainability of these solutions, as well as actually making it possible to use the current `RegionNavigationContentLoader` code without modification of other parts (i.e. view model wireup). This would be simpler and more maintainable if `RegionNavigationContentLoader` were inheritable with the appropriate hook method available for override. The Pluralsight videos for Mastering the Tab Control and Displaying Multiple Shells dating back to Prism 5 provide the full details and context for this problem and solution.

**Comment by brianlagunas** [comment]
fixed! Thanks for the suggestion

**Comment by Sampapi** [comment]
I noticed that Prism 8.0 now supports scoped regions, but I cannot find the documentation in order to use Scoped Regions. Where would this be found? 
Thanks,
           Richard Lavallee

**Comment by dansiegel** [comment]
@Sampapi I believe you're confusing Scoped regions with Container Scoping

**Comment by Sampapi** [comment]
Yes, you are right. I was hoping that I could find recent documentation on Scoped Regions. I followed the Pluralsight courses on this subject but did not manage to implement Scoped Regions as the course is a few years old and the material did not correspond to the version 8 of Prism. Is there a place where I could find the documentation on this so that I could resolve this issue with version 8 of Prism. 

Thanks,
       Richard Lavallee

**Comment by brianlagunas** [comment]
There are no conceptual differences in Prism 7 and Prism 8 for WPF. The only big thing would be the removal of ServiceLocator being replaced with ContainerLocator.  Everything else should work.

**Comment by Sampapi** [comment]
The Lesson that you gave on ScopedRegions was in Prism Problems & Solutions: Showing multiple Shells, chapter 2 section "The Solution - Scoped Regions". The version on Prism is 6.1.0. I could not get that to work using this course as it did not seem to fit with the latest Prism version.
      Richard

**Comment by Sampapi** [comment]
Thanks Dan & Brian,
         I finally managed to make the Scoped Regions work with Prism 8 and WPF on  .net 5.0.
 Thanks again
      Richard Lavallee

**Comment by Sampapi** [comment]
However, there is one problem remaining with your solution for ScopedRegions. The Region manager for a given viewModel is not available in the constructor of the viewmodels. It is null and so I cannot use it. But this is ok as I moved code requiring the RegionManager to the OnNavigated to method.

I did notice however a remaining problem with the ScopedRegions when going to a deeper level:
 Shell --> viewa -> Collection of Tabbed views -> viewc.

On first invocation of the tabbed view, the viewc is created in its associated region correctly.

But on on the invocation of a second tabbed view that contains viewc, I get an ArgumentException:
Region with the given name is already registered: PersonDetailViewCRegion.

It would be great if this logic on ScopedRegions was included in Prism to keep it simpler to use, instead of providing a solution to this infrastructure problem.

Thanks,
    Richard Lavallee

**Comment by brianlagunas** [comment]
The region manager in a WPF app is never null. The RegionManager is a singleton, therefore if you inject the IRegionManager into any ctor, you'll get the same instance. If you have a null RegionManager, you are doing something wrong.

If you are following my Pluralsight course, then you must use the code I provided in my course to access the correct scoped region manager for your specific view. Otherwise your navigation will not work as expected. Check out the Mastering the TabControl as an example.

Scoped regions are a very advanced feature and not a one size fits all. The solution I provided in my course is just one way to do it, and the approach will be different depending on the situation of your app requirements and structure. Any type of advanced scoped regions will not be included in Prism.

**Comment by Sampapi** [comment]
Thanks Brian,
              I shall look at the Mastering Tab control course.

Richard

**Comment by Sampapi** [comment]
Hi Brian,
            I went through both courses (Prism Problems & Solutions: Showing Multiple Shells & Mastering TabControl).
Everything works perfectly except the "Child Navigation" section of the Mastering TabControl course.
I was not too keen on modifying the ScopedRegionNavigationContentLoader but did it anyway. I had to make a few assumptions when modifying your code as version 8.0 is not quite the same as version 6.1. 

I added the  following registration to the App.xaml.ca file to incorporate it in the solution
containerRegistry.RegisterSingleton<IRegionNavigationContentLoader, ScopedRegionNavigationContentLoader>();

I managed to build my solution and tried it out but to no avail.

I get a SystemNullReferenceException on the _container object in the CreateNewRegionItem method. Thus my alterations to this method are wrong.
