### ISSUE TITLE
[Bug] Prism.Forms.Regions in xaml not working when content view in top child

### ISSUE THREAD

**Issue by albilaga** [PrismLibrary/Prism#2415]
### Description
prism:RegionManager.RegionName="" not working when the contentview is in the first child
This is working and region manager can find it:
```
<Grid RowDefinitions="*,40">
    <Label Text="Tab 1" Grid.Row="1" VerticalTextAlignment="Center" HorizontalTextAlignment="Center"/>
    <ContentView prism:RegionManager.RegionName="ContentRegion" />
</Grid>
```

This is not working and region manager can't find it:
```
<Grid RowDefinitions="*,40">
    <ContentView prism:RegionManager.RegionName="ContentRegion" />
    <Label Text="Tab 1" Grid.Row="1" VerticalTextAlignment="Center" HorizontalTextAlignment="Center"/>
</Grid>
```
Happened also with `StackLayout`, `ContentView`, and `Frame`.
For `ContentView` and `Frame` I do it like this
```
 <Frame>
    <ContentView prism:RegionManager.RegionName="ContentRegion" />
</Frame>
```

### Steps to Reproduce

1. In the `MainPage.xaml`, comment the top label and uncomment the bottom label 

### Expected Behavior
RegionManager should still can find ContentRegion

### Actual Behavior
RegionManager can't find ContentRegion

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: -
- Xamarin.Forms version: 5.0.0.2012
- IDE: VS for mac 8.9.7

### Reproduction Link
[PrismRegion.zip](https://github.com/PrismLibrary/Prism/files/6374401/PrismRegion.zip)

**Comment by dansiegel** [comment]
Thanks for the report.... from the code that you've provided I don't see anything obvious as it should work just fine. I'll add this to my list of things to look.

**Comment by rssllgrrtt** [comment]
Hey @dansiegel and @albilaga 

Hope you don't mind my jumping in here. I've been wanting to learn a little more about how regions actually work for a while, so when I spotted this I jumped on and had a read through the code. 

Like I said, the Region code is new to me, so please forgive me if I've missing something here.

The crux of the issue seems to be the exception thrown from RegionCollections indexer. Specifically line 40 "GetRegionByName".

I compared the call stack for the example that worked, and the example that didn't. 

The code seems like it's falling down in the RegionManager class, line 110, "DesignMode.IsDesignModeEnabled". In the example that works, the bool is false and CreateRegion executes. In the example that doesn't work, it's true.

I've got absolutely no idea why simply commenting out one label and uncommenting another will cause this bool to trip, but removing that check seems to fix the issue. 
That said, I've

**Comment by dansiegel** [comment]
I've added this issue as a test to the Prism test suite in the Region Updates PR

https://github.com/PrismLibrary/Prism/blob/2c90cfc9fbfb1447d619e772c6369a9ce4ef6652/tests/Forms/Prism.DI.Forms.Tests/Mocks/Views/Issue2415Page.xaml#L1-L14
