### ISSUE TITLE
[Enhancement] Factory method registrations improvements

### ISSUE THREAD

**Issue by Chippychap** [PrismLibrary/Prism#2447]
## Summary

#2076 introduced various container abstraction enhancements, including the very helpful factory method registrations.
These registrations however do not include a named variant while both Unity and DryIoc both support these.
Additionally the factory registry extensions would be able to deduce the type if the accepted factory method was of type `Func<T>`.

## API Changes

For `IContainerRegistry` include the following overloads:
```C#
IContainerRegistry Register(Type type, Func<IContainerProvider, object> factoryMethod, string name);
IContainerRegistry Register(Type type, Func<object> factoryMethod, string name);
IContainerRegistry RegisterScoped(Type type, Func<IContainerProvider, object> factoryMethod, string name);
IContainerRegistry RegisterScoped(Type type, Func<object> factoryMethod, string name);
IContainerRegistry RegisterSingleton(Type type, Func<IContainerProvider, object> factoryMethod, string name);
IContainerRegistry RegisterSingleton(Type type, Func<object> factoryMethod, string name);
```

For `IContainerRegistryExtensions` include the following overloads:

```C#
public static IContainerRegistry Register<T>(this IContainerRegistry containerRegistry, Func<IContainerProvider, object> factoryMethod, string name);
public static IContainerRegistry Register<T>(this IContainerRegistry containerRegistry, Func<object> factoryMethod, string name);
public static IContainerRegistry RegisterScoped<T>(this IContainerRegistry containerRegistry, Func<IContainerProvider, object> factoryMethod, string name);
public static IContainerRegistry RegisterScoped<T>(this IContainerRegistry containerRegistry, Func<object> factoryMethod, string name);
public static IContainerRegistry RegisterSingleton<T>(this IContainerRegistry containerRegistry, Func<IContainerProvider, object> factoryMethod, string name);
public static IContainerRegistry RegisterSingleton<T>(this IContainerRegistry containerRegistry, Func<object> factoryMethod, string name);
```

## Intended Use Case

Prevent the need to get the underlaying container. `var container = containerRegistry.GetContainer();`

**Comment by dansiegel** [comment]
You are correct we don't do this... and that is by design. While we want to try to give you a solid API that gives the majority of developers what they need to develop apps, our intention is not for IContainerRegistry to provide every single possible registration API that you might ever need in advanced scenarios. For those scenarios we do provide access to the underlying container as you know. It is our guidance that in these scenarios you rely on that.

Alternatively if you want an approach decoupled from a specific container you can add your interface and extensions similar to what I had done for the Prism.Container.Extensions and what we do internally with IContainerInfo.
https://github.com/PrismLibrary/Prism/blob/411ff88c9fb38d382d5cbddc13649b011bda791e/src/Prism.Core/Ioc/Internals/IContainerInfoExtensions.cs#L19-L25
