### ISSUE TITLE
[Bug] TabbedPage crashes Xamarin.Forms iOS app when navigating away for it

### ISSUE THREAD

**Issue by marcberman14** [PrismLibrary/Prism#2494]
### Description
When navigating back from a TabbedPage, the app crashes with the following Stack on Xamarin.Forms iOS:

- System.Exception: Cannot destroy Xamarin.Forms.NavigationPage.
- System.Exception: Cannot destroy TabbedPageTest.Views.MyTabbedPageView. 
- System.NullReferenceException: Object reference not set to an instance of an object

### Steps to Reproduce

1. Launch attached Xamarin.Forms iOS sample app
2. Tap "Navigate to Tabs"
3. Tap back arrow top left
4. App will crash on iOS

### Expected Behavior
Should return to the previous page without crashing
### Actual Behavior
Crashing the app when returning to previous page
### Basic Information

- Version with issue: 8.1.97
- Last known good version: 8.0.0.1909
- Xamarin.Forms version: 5.0.0.2012
- IDE: Rider, VS Windows, VS Mac

### Reproduction Link
[TabbedPageTest.zip](https://github.com/PrismLibrary/Prism/files/6707778/TabbedPageTest.zip)

**Comment by brianlagunas** [comment]
I am unable to test this on Mac since I don't have one, but after fixing some issues in your code such as removing the PageNavigationService registration, and fixing your navigation call in your MainPageViewModel (removed the extra NavigationPage you are adding to the stack) it works fine for me on Android.

@dansiegel when you get a chance can you check this out on your Mac?

Also, don't use `nameof(PageName)` in your ViewModels. You are completely breaking MVVM.

**Comment by marcberman14** [comment]
I have made the changes as per your suggestions, the same problem exists for iOS.
