### ISSUE TITLE
Why is OnPropertyChanged method in BindableBase protected?

### ISSUE THREAD

**Issue by sprengo** [PrismLibrary/Prism#253]
In my model objects it happens that i have to raise OnPropertyChanged on derived properties in other dependent objects. Which is not possible because OnPropertyChanged is protected.

**Comment by briannoyes** [comment]
I'd have to see some examples of where you need to do this and why it can't be encapsulated in the owner type of the property itself. OnPropertyChanged (and SetProperty) are protected because OO encapsulation principles would lean towards saying that external objects should not be able to tell the object when it should raise those events. If you are doing that in lots of places, it calls into question the design of your object model. If you just have a few specialized scenarios where you need to do it, why is it not better to expose a method or methods of your own on your model objects to enable outside objects to "request" firing property changed from inside the object?

**Comment by sprengo** [comment]
I have an aggregation class combining constructional parts to an assembly. Some properties of the assembly affect calculated properties of the (sub) parts and vice versa. For example if the length of a part changes the length of the whole assembly should change too because it is calculated from the parts' length's.

**Comment by brianlagunas** [comment]
It sounds like you should be subscribing to the PropertyChanged events in your aggregated class, and expose methods to "refresh" the values of the sub objects calculated (and I assume read only) properties.  Also, if values in the assembly effect calculated properties of the parts, it sounds like you should be setting new values of the subparts that would internally update the calculated values of that part.

**Comment by sprengo** [comment]
In fact it is not just an aggregation but a bidirectional composition where the parts have a reference to the assembly, because calculated properties of the parts directly use assembly properties in their calculations.
For simplicity reasons in the setter of an assembly property i would just stick with:

    set
    {
        SetProperty(ref this.assemblyPropertyBackingField, value);
        PartX.OnPropertyChanged(() => PartX.CalculatedPropertyThatInvolvesThisAssemblyProperty);
    }

Perhaps this scenario is too specific.

**Comment by brianlagunas** [comment]
Since the parts have a reference top the Assembly then the parts can hook into the assembly instance INPC event and listen for changes there.
