### ISSUE TITLE
WPF Dialog.WindowStartupLocation Not valid in version 8.1.97

### ISSUE THREAD

**Issue by l5624** [PrismLibrary/Prism#2535]
The following code is not valid in version 8.1.97, Always centered. But it Normal no problem in version 8.0.0.1909

```
 <prism:Dialog.WindowStyle>
        <Style TargetType="Window">
            <Setter Property="prism:Dialog.WindowStartupLocation" Value="Manual"/>
            <Setter Property="Left" Value="500" />
            <Setter Property="Top" Value="300" />
        </Style>
    </prism:Dialog.WindowStyle>
```

**Comment by brianlagunas** [comment]
That never worked, because Left and Top properties are not dependency properties and cannot be set in a style.  See https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.left?view=net-5.0#remarks
![image](https://user-images.githubusercontent.com/835562/129607172-4dfc82bb-c070-4cae-988c-49edea532388.png)
