### ISSUE TITLE
[Bug] Flyout page INavigationAware events incorect triggering

### ISSUE THREAD

**Issue by amaneshi** [PrismLibrary/Prism#2587]
### Description

Thank you for great framework, very like it! Found small bug in Flyout page events handling, but I really need to work right (made some ugly workaround).

So I have some simple root navigation page, e.g. `/NavigationPage/HomePage`. Then I navigate to Flyout page with some setting pages with path `/MainPage/NavigationPage/SomeDetailPage` ("MainPage" is Flyout page). Till now everything work as expected. After that when I navigate to other Flyout detail pages (with `NavigationPage/OtherDetailPage`) I use `INavigationAware` method `OnNavigatedFrom` inside detail page to cleanup state changes and event trigerred.

But then I try to return to HomePage with `/NavigationPage/HomePage` and this time method `OnNavigatedFrom` on last active detail page was not triggered. I made some additional checks - can add that same event, `OnNavigatedFrom`, in parent VM (for Flyout page itself) still triggered as expected, but not in detail page.

### Steps to Reproduce
1. Open App - Home page is root page
2. Press button to open Flyout page with 2 detail pages
3. On Flyout page switch between detail page to see in debug console 2 messages from `OnNavigatedFrom` in detail page and Flyout page itself
4. From side menu press button to return to home page and in debug console only message from `OnNavigatedFrom` in Fluout page (but nothing from detail page)
### Expected Behavior
Correct  `OnNavigatedFrom` method trigger on navigation from Flyout detail page
### Actual Behavior
 `OnNavigatedFrom` not triggered in detail page if navigate outside Flyout page
### Basic Information

**Platform**: UWP
**Prism**: 8.1.97
**XF**: 5.0.0.2125

### Reproduction Link
[Sample App](https://github.com/amaneshi/PrismSampleApp)

**Comment by brianlagunas** [comment]
Well, the issue here is actually that the OnNavigatedFrom only "appears" to be called on the FlyoutPage because the Detail's NavigationPage is inheriting the BindingContext of the FlyoutPage. Which means that OnNavigatedFrom actually isn't being called on the FlyoutPage. Its being called on the NavigationPage.

The design is only the Detail should have it's a OnNavigationFrom/To called during navigation, not the VM of the FlyoutPage.

I'll have to discuss with @dansiegel about how we should solve this one. I think it's weird that the Detail BindingContext is inheriting the FlyoutPage's BindingContext and not it's child's BindingContext.

**Comment by dansiegel** [comment]
In Xamarin.Forms, all Page's inherit from BindableBase. The way that this works is that when the BindingContext is not explicitly set then the element will default to use the BindingContext of the parent.

Given a navigation stack like `MyFlyoutPage/NavigationPage/ViewA` in which we do not have a ViewModel for the NavigationPage, the behavior of Xamarin.Forms is to have the NavigationPage inherit the ViewModel of it's parent `MyFlyoutPage`. In order to prevent this you can update your registration for the NavigationPage to be:

```cs
containerRegistry.RegisterForNavigation<NavigationPage, object>();
```

**Comment by brianlagunas** [comment]
Fixed
