### ISSUE TITLE
How to contribute Prism to add UWP support again?

### ISSUE THREAD

**Issue by soroshsabz** [PrismLibrary/Prism#2706]
ITNOA

As you can see in below comments, I want to know how to contribute Prism to add UWP support again? (not Uno or another third party framework)

@robv8r
> I hope you understand why I feel like your project has abandoned me, our company, and everyone else I've encouraged to use Prism.

I am curious what have you, your company, or the people you encouraged to use Prism have contributed back to the Prism community.

> Now we have to rip out Prism (which is like ripping out my own heart).

I understand your frustration, and appreciate the sentiment. However, this is the risk to every single open source project in existence that does not have any major financial backing.  If you use open source, the licenses clearly says use at your own risk. You are relying on the work of people volunteering their time, expertise, and personal financial resources. At any time, they can change their mind and move on. If you, or your company, does nothing to ensure the projects you rely on are sustained, then you have zero place to complain when those projects no longer exist or are maintained.

Since UWP is so critical to your business needs, I invite you, and your company, to join the Prism team and take the lead on the UWP effort. Help us finally provide full support for UWP. Let the entire Prism community benefit from the work of you and your company.

_Originally posted by @brianlagunas in https://github.com/PrismLibrary/Prism/issues/1835#issuecomment-517776280_

**Comment by soroshsabz** [comment]
related to #1835

**Comment by dansiegel** [comment]
Neither @brianlagunas or I have any intention of ever adding direct support for UWP particularly because Microsoft itself has (predictably) deprecated the platform in favor of WinUI 3. In short it would take a substantial financial contribution from one or more institutions that claim they are so heavily dependent on UWP, yet magically are willing to contribute exactly $0.00 collectively.

I can tell you that there are absolutely ZERO Enterprise Support clients for Prism who have a need for UWP directly, and we have no GitHub Sponsors currently asking for it, not that the level of Sponsorship would drive us to take on that challenge. On the flip side, we do have a large number of people who have a need for Prism to developer .NET MAUI applications.
