### ISSUE TITLE
[BUG] Android MAUI Absolute navigation creates new instance of application.

### ISSUE THREAD

**Issue by Pastajello** [PrismLibrary/Prism#2833]
### Description

Hello,

when creating a navigation with absolute navigation
`navigationService.NavigateAsync("/MainPage")`
MAUI application somehow creates new instance of application instead of resetting the stack as on X.F.

Also, MAUI app with startup navigation of NavigationPage/MainPage doesnt have NavigationPage?
![file](https://user-images.githubusercontent.com/28345098/222961290-cc789417-359f-4dc9-8887-fa514ec3abb4.gif)

### Steps to Reproduce

Create basic app from templates with X.F and MAUI(I used one from nuget as I have no template for MAUI in VS):

add command with navigationService.NavigateAsync("/MainPage")

invoke command.

Prims.MAUI: 8.1.191-beta
Prism.Core: 8.1.97

Prism.Fomrs: 8.1.97
Prism.Core: 8.1.97

### Platform with bug

.NET MAUI

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by dansiegel** [comment]
This isn't "relaunching the app" but it is opening a new Window which is a behavior that is specific to Windows and Android in the current public release because of a MAUI bug that when you reset the Window's Page it does not actually update the UI... as a work around we had to launch a new Window. This is resolved in .NET 7 and is available for Sponsors in the Sponsor Connect feed.

**Comment by BurkusCat** [comment]
Is Prism.Maui going to be exclusively .NET7? I take it when the next version of Prism launches (that includes Maui), it would also include this fix?

**Comment by dansiegel** [comment]
The next release will be net7 but it will ultimately be exclusively net8+

**Comment by SarthakB26** [comment]
Has anybody found workaround for this ?

**Comment by WilliamWatterson86** [comment]
@dansiegel - do you have a date in mind when this fix will be public?
