### ISSUE TITLE
[Enhancement] Extract EventAggregator to a separate NuGet package.

### ISSUE THREAD

**Issue by Tum4ik** [PrismLibrary/Prism#2866]
## Summary

There are some projects where it is not desired or not possible to use whole Prism library. But the usage of the Event Aggregator implementation is required.

## Intended Use Case

Any project which requires standalone Event Aggregator.

**Comment by Tum4ik** [comment]
If approved - I can do that.

**Comment by Tum4ik** [comment]
But even Core package has a lot of things which will remain unused.

**Comment by brianlagunas** [comment]
Core is only 88KB. Is creating and managing a separate package, while at the same time breaking the entire dependency graph for every existing Prism application worth it?

**Comment by Tum4ik** [comment]
Ok, I've gotten your point. 
What if I create a project which will contain the only EventAggregator source code copy? And that will have a name `Prism.EventAggregator`. I will also publish that as NuGet package. 
Do you have some objections about it?

**Comment by brianlagunas** [comment]
You won't be able to do that. We own the prefix Prism. So, you'd have to name it something different.  @dansiegel and I will need to talk about this.

Funny story, the EA use to be in a separate package, but the community hated that and wanted it brought into the core project. So that's why all the previous independent packages such as Commanding, EA, Regions, and Modularity were converted from individual packages to single packages.
