### ISSUE TITLE
App Crashes on Mobile (SettingPane is not register type)

### ISSUE THREAD

**Issue by CoderXpert** [PrismLibrary/Prism#290]
I am working on a Universal Windows 10 app, I am using Prism for store apps, its working find on when I run app on Desktop but it always crashing on Mobile devices withan exception "Requested Windows Runtime type 'Windows.UI.ApplicationSettings.SettingsPane' is not registered".

I tried to override GetSettingsCommands() to return empty commands list, but its giving me a compile time error 
"Error	CS0731	The type forwarder for type 'Windows.UI.ApplicationSettings.SettingsCommand' in assembly 'Windows' causes a cycle"

**Comment by bartlannoeye** [comment]
Prism for Store apps is an old release of Prism used for apps on Windows 8.1 / Windows Phone 8.1 RT.

You should use [Prism 6 for UWP](https://www.nuget.org/packages/Prism.Windows/) when creating an app for Windows 10 UWP as SettingsPane is indeed no longer supported, as you can read under the breaking changes on our [readme](https://github.com/PrismLibrary/Prism/blob/master/README.md). Take special note of following breaking changes when moving to the latest release for UWP:

* Changed namespaces to remove Microsoft namespaces
* Removed SettingsPane functionality from PrismApplication because it is deprecated in UWP
* Visual State management parts of VisualStateAwarePage were removed and it is now renamed to SessionStateAwarePage.

**Comment by CoderXpert** [comment]
So we should not use Prism.StoreApps any more (as I am building  windows store app), guys from Microsoft virtual academy recommended Prism.storeApps ...?

**Comment by bartlannoeye** [comment]
Prism.StoreApps is for 8.1 only, not for 10. Can you link the session on MVA please?

**Comment by CoderXpert** [comment]
Thanks, below is the link to Video Lecture
https://mva.microsoft.com/en-US/training-courses/developing-universal-windows-apps-with-c-and-xaml-8363?l=aUjZ7DGz_2304984382

**Comment by bartlannoeye** [comment]
That's an 8.1 course indeed (although you'll be able to use nearly all concepts on Win10 so the course is no lost time).

**Comment by CoderXpert** [comment]
Thanks, I thought it might be specific to store apps, is there any other resoucrece for windows 10.

**Comment by bartlannoeye** [comment]
I'd say 95% what's said in that 8.1 course also counts for 10. If you want a specific Win10 course, you could check https://mva.microsoft.com/en-US/training-courses/a-developer-s-guide-to-windows-10-12618.
Happy coding !
