### ISSUE TITLE
No modal navigation in TabbedPage

### ISSUE THREAD

**Issue by DaveDaBrave** [PrismLibrary/Prism#2912]
### Description

Navigation via Navigation.NavigateAsync(“NewPage”) only shows the NewPage as a modal, if not called from a within a TabbedPage.
If called from within a TabbedPage the navigation happens, as if it is called via Navigation.NavigateAsync(“/NewPage”).

Also the Navigation.NavigateAsync(“NewPage”, useModalNavigation = true) overload is not available in the MAUI-project.

Repo: https://github.com/DaveDaBrave/PrismTest
(@brianlagunas @dansiegel I hope you don't mind I added you as a collaborator because I had to create this repo as private first)

### Steps to Reproduce

1. Start the app
2. Click “Login” Button
3. Modal page opens as modal
4. “Continue” or “X” button closes the modal
5. App navigates to the tabbedPage
6. Click “ShowModal” button on any of the four tabs
7. “ModalPage” does not open as modal, it gets navigated to via push

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

**Comment by dansiegel** [comment]
@DaveDaBrave can you make the sample public

**Comment by DaveDaBrave** [comment]
@dansiegel changed to public

**Comment by dansiegel** [comment]
@DaveDaBrave there are a number of issues that you have with the code provided in your sample app which are giving you the various issues that you are running into including the "sometimes null INavigationParameters".

By default Prism Maui gives you both a NavigationPage and TabbedPage for Navigation out of the box you do not need to provide your own unless you are trying to uniquely style them based on the route context. While Prism internally uses the PageBehaviorFactory to set Page Behaviors, you can also do things like set platform specifics like the TabBar position on Android, or you can do this through implicit styling for your app.

Your NavigationPage should inherit from the PrismNavigationPage otherwise you will need to wire up a bunch of additional functionality, and it should NOT have a constructor argument that takes a Page.

You may want to consider using the NavigationBuilder which will make it clearer what you are trying to do. Also keep in mind calling a Page "ModalPage" but not actually specifying that you want it to be modal when you are navigating to it from a page that is the child of a NavigationPage will NOT result in the correct Navigation.
https://github.com/PrismLibrary/Prism/blob/2ff1836d048ca94af3c7d7341f3f8431fed00d99/tests/Maui/Prism.Maui.Tests/Fixtures/Navigation/NavigationBuilderFixture.cs#L176-L195
