### ISSUE TITLE
Nested regions are not activated, when outer region gets actived

### ISSUE THREAD

**Issue by tiesmaster** [PrismLibrary/Prism#293]
When an outer region gets actived, and that contains some nested regions, then the `IsActive` is changed to `true`. However, since the active views of the nested regions were already active, they don't get activated. Usually you want them to be activated as well, or at least know that the "ancestor region" got activated. A use case for this, is to get the latest data from a webservice, but probably, there are many more use cases for this.

I created a test project where that behavior is reflected (it's [here](https://github.com/tiesmaster/NestedRegionsInPrism)), and created a proof of concept behavior that does this, but probably needs so improvements ([NestedRegionActiveAwareBehavior](https://github.com/tiesmaster/NestedRegionsInPrism/blob/master/NestedRegionsInPrism/NestedRegionActiveAwareBehavior.cs)).

Is this something that can become part of PRISM, or are we doing something wrong here?

**Comment by brianlagunas** [comment]
I don't really understand your issue.  What are you expecting to happen?  You only load MainView once (Which IsActive = true), and then navigate within that view to NestedView (IsActive becomes true).  Next, if you click the Navigate button, you navigated View2 into the NestedRegion.  NestedView is now IsActvie = false, and View2 becomes active.  Although, you do not have View2 implementing IActiveAware, so you don't get notifications there.

From what I can tell, your region behavior doesn't do anything because the IsActive values are already true, and your behavior is just setting them to true again.

**Comment by brianlagunas** [comment]
Ohhh... I get what you mean now.  Your behavior was throwing me off, because it is always setting IsActive to true, so the NestedView.IsActive was always true, even when you meant to be false.

When you navigate away from MainView you want NestView to be IsActive=false too.  So when you come back to MainView, NextView.IsActive becomes true again along with MainView.

Is this correct?

**Comment by tiesmaster** [comment]
Yes, indeed, that's the main gist of it. Sorry for the unclear issue description, I was hoping that my sample project would clarify things, but maybe it only confused you :(

Anyway, the problem, as I see it, is indeed that when the MainView becomes inactive, the inner active views stay active, even though they're really not. And when you go back, they don't get "re-activated", so you can't handle that (or handle the event that they're becoming inactive).

Maybe the inner active views should become inactive, when a containing active view becomes inactive, however, that might bring another problem with it: when you go back to the MainView, the previously active inner views should become active again, so you need to know which ones should become active. How do you know that? Since an inner region might have different views, and you don't know which one was active previously, so you should start recording that, which you probably don't want to do. So that's how I got to the behavior in the sample project.

**Comment by brianlagunas** [comment]
This is the expected behavior.  When a nest view is active, and it's parent becomes inactive, the nested view is still active within the context of the parent.  So if you need specific functionality to have a nested region go inactive with the parent, then you are using the correct approach of a custom region behavior.
