### ISSUE TITLE
Conflicting Unity versions with new 4.0 strong name

### ISSUE THREAD

**Issue by headsphere** [PrismLibrary/Prism#298]
Hi guys - As I understand it, the latest version of Prism 6 is now tied to Unity 4 which has had a key change as per this issue: #193 

My problem is that now the strong name is different I cant re-use any of my existing business logic DLLs which are tied to an older version of Unity as the binding redirect does not work:

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Unity" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.505.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```
Gives me:

```No way to resolve conflict between "Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f" and "Microsoft.Practices.Unity, Version=2.1.505.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". Choosing "Microsoft.Practices.Unity, Version=4.0.0.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f" arbitrarily.```

As I see it, as upgrading to Unity 4 for my dependencies is a non-starter, the only options available to me are:

- Recompiling from source and downgrading to an older Unity version
- Using your latest version before you did the upgrade
- Using MEF instead of Unity for module resolution, and using ServiceLocator to resolve my module's dependencies manually

Is there a simpler option here, or perhaps something I'm just missing?

Thanks a lot

**Comment by briannoyes** [comment]
If you are making changes to your app to integrate the latest versions of Prism, why is it such a non-starter to recompile the libraries that depend on Unity to take Unity 4.0?

If that is the case, I'd saying compiling against source with the dependency switched back to whatever version of Unity you are stuck on is your best bet. 

We are stuck between a rock and a hard place because some customers want Prism strong named because they are strong naming their assemblies, but strong names immediately lock down versioning like this in ways that are totally opposite the kind of agile approach we want to have with Prism moving forward.

**Comment by headsphere** [comment]
The reason I can't upgrade my business logic libraries is because they are dependent on another team's framework libraries from which we then derive our Unity V2 dependency. I'm not actually planning on changing our business logic libraries at all; I was attempting to just put a GUI wrapper around existing logic. It could be quite painful forcing the other team to upgrade their framework, but that's my problem! In the meantime I'll just have to compile a custom version of Prism targeting the old Unity version. 

Thanks for your quick response Brian.

Cheers
Nick
