### ISSUE TITLE
[BUG]  Navigation from tabbedPage, clear stack

### ISSUE THREAD

**Issue by michal-ziolkowski-dev** [PrismLibrary/Prism#3015]
### Description

Problem is related to navigation from TabbedPage.

When we crate tabbed page and navigate deeply from one tab into e.g. details, Prism will open Page as new(no into content of tabbed page) and will clear stack and we canon't go back to tabbed page. According to my check, prim will clear backstack.

Github: https://github.com/michal-ziolkowski-dev/maui_tabbed_page_navigation

### Steps to Reproduce

1. Run app
2. Go to TabbedPage
3. Go to Details Page

Page should be open into content of tab page and back button should be visible

### Platform with bug

.NET MAUI

### Affected platforms

iOS, Android

### Did you find any workaround?

Yes, use native .maui navigation

**Comment by brianlagunas** [comment]
This is not a bug. You have a number of issues with your code. First off, stop doing this
```
BindingContext = ContainerLocator.Container.Resolve<HomeDashboardTabeViewModel>();
```
Use the built-in VIewModelLocator instead.

Since you are creating your tabs in code, you need to register them with the ViewModelLocationProvider. For example:
```
ViewModelLocationProvider.Register<HomeDashboardTabePage, HomeDashboardTabeViewModel>();
```
You also have code where you are hiding the navigation bar that contains the back button with this:
```
NavigationPage.SetHasNavigationBar(this, false);
```
You have other issues, but I'll leave that to you to work through.

With those changes it works as expected.

<img width="539" alt="image" src="https://github.com/PrismLibrary/Prism/assets/835562/fc55eac0-3490-4c67-aef1-4bd1cf8ca98d">

**Comment by michal-ziolkowski-dev** [comment]
@brianlagunas thanks, built-in VIewModelLocator was the key, now working as expected.
