### ISSUE TITLE
[UWP] UnitTests with Prism

### ISSUE THREAD

**Issue by Rhywden** [PrismLibrary/Prism#313]
Yes, I know about issue #140 . However, it seems to have been fixed for pure apps in the meantime, as I can run unit tests on UWP apps as long as I don't add Prism into the mix. Without having to pull my Models or ViewModels into a separate project which, by the way, would be a major pain for me to figure out because I also want to use Azure Mobile Services with offline sync and Sqlite.

What I did:

1) Created a blank UWP app
2) Created a class with a method to test
3) Added a Windows 10 UWP Unit Test project
4) referenced the blank app in the unit test project
5) added a unit test method for the class method from 2)
6) Ran "Run all" and succeeded

Whereas with Prism added into the mix the unit test methods don't even need to access anything to crash.

**Comment by Rhywden** [comment]
Maybe a short follow up: I *did* try to pull the stuff I wanted to unit test into a class library. That approach worked for the models.

When I tried the same with the ViewModels, the app *silently* fails. The View is constructed but the ViewModel is never instantiated. I tried to use `Container.RegisterType(...)` but that didn't work out as well. Simply nothing happens and I don't even get a error message so I'm not really able to figure out what is going wrong there.

The namespace is unchanged, my ViewModels reside in `AppName.ViewModels` and I can access them programmatically, independent of their location.

**Comment by Rhywden** [comment]
Okay, this here does work, regardless of where the VM in question resides:

    var x = Container.Resolve(typeof(ExamplePageViewModel)) as ExamplePageViewModel;

So the container can find the ViewModels. Seems to be a problem with the AutoWireViewModel.

**Comment by brianlagunas** [comment]
This is not an issue with Prism or AutowireViewModel.  The app crashes because of limitations with testing Universal projects.  Actually, UWP testability really sucks right now.  The reason the test project fails is because you are using a custom application base class.  This would happen even if you used you own customer app base class.  This is th error that would be thrown:

Cannot deserialize XBF metadata type list as 'PrismUnityApplication' was not found in namespace 'Prism.Unity.Windows'. [Line: 0 Position: 0]

You need to add the BindableAttriute to your application class.

```
[Bindable]
sealed partial class App : PrismUnityApplication
{
    ...
}

Keep in mind, this will not be the only issue you run into trying to test a UWP app.

The other issue you are having when pulling your view and ViewModels out is due to the way UWP handles loading types from referenced assemblies.
