### ISSUE TITLE
Component Composition for Windows 10 mobile

### ISSUE THREAD

**Issue by suresh-s** [PrismLibrary/Prism#320]
We want to migrate Windows phone 8 project to Windows 10 Mobile. We are currently having Single project with MVVM architecture. The project consist of 7 different features. We want to segregate as 7 different modules while migration.

I can't find out ModuleCatalog, Region, RegionManager, Shell classes in Prism.Windows library. 

1.Why are these classes been removed? 

2.Is the Shell, Region and ModuleCatalog based Architecture not suitable for Windows 10 mobile projects?

3.Why should i use Prism 6.0 since "Composite application from loosely coupled components" is not supported? How can i create Composite application with different modules and components using Prism 6.0?

4.Should i create Infrastructure libraries "Module Catalog", "Module Loader", "Region Manager", "Logging", "Region Manager", "Region" and "Shell" to create Composite application?

**Comment by briannoyes** [comment]
Nothing has been removed from Prism for UWP, those features were never there in the first place. The Prism for WPF and Prism for UWP are different code bases. Prism for UWP is a port of the Prism for Windows Runtime project that never had modularity or regions by design. We would like to introduce those to Prism for UWP but haven't had time for that yet.
