### ISSUE TITLE
[BUG] Is DialogParameters really not supposed to allow null values in 9.0?

### ISSUE THREAD

**Issue by jmoleary** [PrismLibrary/Prism#3245]
### Description

I don't know if this is a bug or a by-design breaking change in 9.0

In my Prism 8.1 dialogs, I sometimes return `DialogParameter` objects containing values that are null.  This is expected.   For example, the following code built under 8.1 but not under 9.0

```
void DialogParameters GetParameters()
{
     return new DialogParameters
     {
         { "type",    SelectedTargetType },  // THIS COULD BE NULL
         { "serial",  Serial },
     };
 }
 
 public TargetType? SelectedTargetType { get; set; }
 
```

Under 9.0 I get error `CS8600: Converting null literal or possible null value to non-nullable type`

Is this truly by design?

### Steps to Reproduce

Try to put a nullable value into DialogParameters

### Platform with bug

WPF

### Affected platforms

Windows

### Did you find any workaround?

I can check any value for null and then just not put it in `DialogParameters` it but I want to be able to return null values.  And I used to be able to do this under 8.1

### Relevant log output

```shell
CS8600: Converting null literal or possible null value to non-nullable type

(I get this for every time I try to put a possibly null value as a DialogParameter value)
```

**Comment by dansiegel** [comment]
Sorry I realized that your issue is that you're trying to pass in a nullable value to the parameters. In Prism 9.0 we have started the process up adding nullability to the API. As you will see all parameters both INavigationParameters and IDialogParameters are `<string, object>` and not `<string, object?>` as a result this expects that if you're adding a key that there is actually a value.

You should update your code to check if the value is null before you add it to the parameters.

```cs
void DialogParameters GetParameters()
{
     var parameters = new DialogParameters
     {
         { "type",    SelectedTargetType },  // THIS COULD BE NULL
         { "serial",  Serial },
     };

     if (SelectedTargetType is not null)
         parameters.Add("type", SelectedTargetType);

     return parameters;
 }
```

Keep in mind that when retrieving a value you can do any of the following:

```cs
var value = parameters["type"]; // return object?

// OR
var value = parameters.GetValue<Type?>("type");

// OR
if (parameters.TryGetValue<Type>("type", out var type))
{
    // Your code here...
}
```

**Comment by brianlagunas** [comment]
Prism 9 is encouraging better developer practices which includes proper handling of nullability. Instead of passing nulls you should either have a value that represents an invalid object or not add the parameter at all and use the ContainsKey off the parameters to see if you have a value. 

Are you a Commercial Plus account holder?

**Comment by jmoleary** [comment]
No sorry I am not a Commercial Plus account holder.  I did not even know there was such a thing.  Should I not have posted?

**Comment by dansiegel** [comment]
@jmoleary you are of course always welcome to post about any issues you encounter, or enhancement requests and the Discussions are always open to any questions you may have. If you were not aware that Commercial Plus was a thing, please be sure you are in compliance with the updated Prism license as Prism 9.0 ships under a new license which may require you to have a paid license for use.

**Comment by jmoleary** [comment]
Ah I get it now.  Well then my problem is solved for the moment.   I have not ideaif we qualify for not so I will keep our code on 8.1 for now and consult with management.
