### ISSUE TITLE
[Enhancement] Improved Release Notes / Changelog

### ISSUE THREAD

**Issue by mark-monteiro** [PrismLibrary/Prism#3252]
## Summary

The current release notes appear to be just a list of all PRs that have been merged since the last release. This makes it quite difficult to see what meaningful changes have been made in the latest version. I would like to consider upgrading to the v9 release but I don't have time to read through 144 PR titles/descriptions in order to determine how to do so, or whether I will benefit from any of the changes.

Some improvements that could be made:
- split updates into categories **breaking changes** (important!), new features, changes, bug fixes, infrastructure, dependency updates, etc
- Add a short hand-written introductory paragraph summarizing the main theme or highlights of the release

**Comment by brianlagunas** [comment]
Thank you for your feedback! We understand how detailed release notes can be overwhelming at times. However, we follow a similar process to MAUI, where the release notes are generated from merged PRs. However, we do not have someone dedicated to writing detailed blogs or summaries. At this time, we're not planning to change that process, but we do appreciate your input and will consider ways to improve clarity in future releases where possible.

**Comment by dansiegel** [comment]
Generally when we make a major version bump it is because there is something that we've needed to break. How impactful this will be for you depends a lot on what API's or platforms you may be using.

I will tell you that there were a number of breaking changes around namespaces which are easily resolved by removing Prism namespaces from your code and enabling Implicit Namespaces. There were also some API breaks with the Dialog Service but it's generally pretty easy to resolve.
