### ISSUE TITLE
[UWP] Write unit tests for IoC containers

### ISSUE THREAD

**Issue by bartlannoeye** [PrismLibrary/Prism#342]
As discussed with the team, we should replace the current validation of IoC containers for UWP (done with a small sample app) by real unit tests like it's done for WPF.

**Comment by jorisdebock** [comment]
How would you propose to test these IoC Containers? Since you can't simple do something like this in UWP:

```
        public void ContainerDefaultsToNull()
        {
            var bootstrapper = new DefaultAutofacBootstrapper();
            var container = bootstrapper.BaseContainer;

            Assert.IsNull(container);
        }
```

I think its not possible to create more than one "Application" in an unit test project?

Trying to do this will throw an Catastrophic failure exception when creating another Application in the testmethod.

**Comment by brianlagunas** [comment]
At this time, unit testing UWP apps is not support.  I'm closing this issue until MS decides to realize that devs need to test their apps and add support for testing.  Related to #140
