### ISSUE TITLE
Memory leak with Prisms's DelegateCommand

### ISSUE THREAD

**Issue by mmalek06** [PrismLibrary/Prism#345]
My application is experiencing a memory leak when I set up Button control CommandParameter binding to reference one of my ViewModels. You can find sample code here:

https://stackoverflow.com/questions/34188671/prisms-delegatecommand-memory-leak

**Comment by brianlagunas** [comment]
Button holds two references to a command one through the Command binding, and it holds a second as a Delegate reference when it subscribes to CanExecuteChanged. And since it never unsubscribes, even though tearing down the view makes the binding one go away, the delegate ref lingers.

We used to have code in our DelegateCommand that made use of WeakReferences, but it was removed because other platforms would collect the weak reference too soon and the command would stop working altogether.  We will see what we can do about this.

**Comment by brianlagunas** [comment]
Just so you know, this is a known issue with WPF:

http://blogs.msdn.com/b/nathannesbit/archive/2009/05/29/wpf-icommandsource-implementations-leak-memory.aspx

**Comment by mmalek06** [comment]
Thanks Brian. It seems that I found a solution for this problem (in my app at least) - I stopped binding directly to a ViewModel instance, and instead I'm binding CommandParameter to one of my ViewModel properties. Then I'm just going through Items collection and removing item that has a matching property value. Now VS diagnostic tools are not showing any objects which should have been GCed and therefore memory leak is gone.

**Comment by brianlagunas** [comment]
This seems to be an issue with the WPF framework and how it manages ICommand.  Since in your scenario you had a collection of child VM's all with their own command, which used a data template to data bind the Button's Command and CommandParameter, you were creating a reference from the Button to the bound child VM, which held on to it after the child VM item was removed from the collection.  Once your View would have been destroyed these child VMs would have been released.

I have reached out to Microsoft to see if this is something they can address.

**Comment by brianlagunas** [comment]
Good news!  Well for Prism anyways... This is an issue with WPF's automation peer framework.  In this case, the TabItemAutomationPeer is holding on to the objects.  So no matter what ICommand implementation you use, you would have a leak.  I am working with Microsoft to see what can be done about this.

**Comment by mmalek06** [comment]
Great! Can't wait to hearing from you.

**Comment by brianlagunas** [comment]
After all these years, Microsoft has finally gotten back to me on this. They have fixed this. The fix will be in .NET 4.8 and is already in .NET Core 3. Better late than never I guess.

**Comment by mmalek06** [comment]
You won't be surprised that I totally forgot about this a long time ago. However it's good to know that maybe opening this issue caused MS people to make the framework better :)

**Comment by brianlagunas** [comment]
I totally forgot too until MS emailed me with the news. LOL
