### ISSUE TITLE
[XF][WPA8.1] Page content doesn't render when navigating

### ISSUE THREAD

**Issue by tomcrusader** [PrismLibrary/Prism#354]
I'm trying to figure out if this is an issue with XF, Prism navigation or WPA 8.1:

When navigating the page content only partially renders; mainly graphics missing (buttons).

The second time I navigate the same page it renders more but still not all.

I've tried reloading app resources after page init but there are still issues.

Ideas?

**Comment by brianlagunas** [comment]
I q think this is a Prism issue as Prism does nothing with rendering of Pages.  The navigation service simply creates a page as you would normally and then calls XF's Navigation.PushAsync/PushModalAsync.  If you have custom resources I would start by removing them completely.  Remove everything and then add everything back one at a time until you duplicate it.  

I'm closing this for now since we don't know what it is exactly, but if we find out that it is related to Prism, I will open it back up.

Let me know what you find.
