### ISSUE TITLE
Start new project with Prism 6?

### ISSUE THREAD

**Issue by jan-schubert** [PrismLibrary/Prism#36]
Next week I will start a new project. Should I use Prism 5 and migrate the project if Prism 6 is released or it is possible to start the project with Prism 6?

**Comment by brianlagunas** [comment]
Well, there is only NuGet packages available for Prism 5 right now.  When Prism 6 is released, we are going to evaluate how we can make the upgrade path seamless.  If you start with v5, and upgrade to v6, there will be breaking changes with the namespaces.  If you start with v6, you will have to manually add the references until we release NuGet packages for it.

**Comment by briannoyes** [comment]
Another path depending on how risk averse you are is to pull down the current Prism 6 librarys from this repo and include them in your solution. Then when the release happens and the NuGets are available, it will just be a matter of removing the projects and adding the nugets and you wont have to deal with the namespace and type name changes later. Of course it is not released yet and we have a little ways to go before we will be ready for the first Prism 6 release, so that does mean you might deal with a little bit of change volatility there, but I wouldn't expect any breaking changes to existing core features of Prism, just the namespace and project changes which are mostly done at this point.
