### ISSUE TITLE
RegisterViewWithRegion is not scoped

### ISSUE THREAD

**Issue by Qwin** [PrismLibrary/Prism#360]
HI,

I just wanted to say that in my project I had many issues related to this. The RegisterViewWithRegion method which uses internally a IRegionViewRegistry is not being scoped when creating a new scoped regionmanager. Solutions that might be good to think about is as follows: 

- Create a new instance of the RegionViewRegistery per RegionManager
- Create an unregister method to be able to unregister a view from a region
- Add another identifier to the RegionViewRegistery that makes it unique per RegionManager used (at the moment view + region is not sufficient) 

Now I know I can customize prism to do this, however shouldnt one of these be default instead of registertoregion being global ? 

Kind regards,
Robert

**Comment by brianlagunas** [comment]
I think you have a slight misunderstanding of how scoped regions work.  When you create a scoped region, you must use the scoped region manger that is created instead of the globally registered region manager.  So when you have the scoped region manager, when your call RegisterViewWithRegion the view will be registered with the proper region manager and injected into the proper region when ready.  There is no need for an unregister method.

https://github.com/PrismLibrary/Prism/blob/master/Documentation/WPF/50-ComposingtheUserInterface.md#creating-multiple-instances-of-a-region

**Comment by Qwin** [comment]
So is it correct for me to say that whatever I register to the Parent Region Manager all child (scoped) region managers will inherit the same registrations ? Because that is happening now :/

**Comment by brianlagunas** [comment]
Oh..... now I understand what you mean.  Yes, this is the expected behavior, and by design.  This is actually because of the AutoPopulateRegionBehavior.  If you don't want this behavior you need to use view injection or navigation.

**Comment by Qwin** [comment]
Ah I see now I was searching for that code. So it was in a behavior. Would be great if it was also documented. Thanks again you saved me a million! :) :+1:

**Comment by brianlagunas** [comment]
If you have time it would be great of you could make a note in the docs and submit a PR :)

**Comment by Qwin** [comment]
Will do that np, actually I am writing a "How To" for the people in my company on these parts.  I will do a couple of PRs. Also I always wondered but why did you never add the IRegionManagerAware (And the behaviors etc) just to the framework. I find it a key part for prism :)
