### ISSUE TITLE
[XF] Parent page view model OnNavigatedTo() not being called

### ISSUE THREAD

**Issue by INRIX-Eric-Hargitt** [PrismLibrary/Prism#366]
Hello,

I'm having an issue in XF where a page view model  `OnNavigatedTo()` is not being called when a child calls `INavigationService.GoBack()`. The parent view model implements `INavigationAware`. In fact, `OnNavigatedFrom()` isn't being called either, nor are `OnAppearing()` or `OnDisappearing()`. Is there anything I need to do differently to get these to work? Thanks.

Eric H.

**Comment by brianlagunas** [comment]
This is expected in some cases.  For example, if you are navigating to a navigationPage and then another page, then only the final target will invoke those methods.  For example:

```
NavigationService.Navigate("MyNavigationPage/ViewA");
```

Then only ViewA will have those methods invoked.  It doesn't make sense for the navigation page to invoke those methods.  For the same reasons that the OnAppearing or OnDissapearing methods aren't being called by XF.

Can you provide more details on your exact navigation scenario?

**Comment by INRIX-Eric-Hargitt** [comment]
One of the scenarios is a login page. When my app starts, I will navigate to the main view of the app, then push a login page on top of that if they aren't signed in. I don't want them to be able to navigate back without being signed in, and I wanted to control this using `CanNavigate()`.

Another scenario is when a user is on the main view and they navigate to a page that will modify data of the main view. When the user is finished modifying and navigates back to the main view, I'd like to invoke `OnNavigatedTo()` for the main view to do some update logic.

**Comment by INRIX-Eric-Hargitt** [comment]
From what I understand, calling `GoBack()` will actually navigate back to the previous view.

**Comment by brianlagunas** [comment]
Navigation is always relative to the current view.  So if you navigate to "MainPage" at app startup, the OnNavigatedTo will invoke on the MainPageViewModel.  So from there if you navigate to "LoginPage" then OnNavigatedFrom will invoke on MainPage and OnNavigatedTo will invoke on the LoginPage.

Although the INavigationAware methods will work with logic based navigation, it currently does not work with the hardware buttons.  So if you press the hardware back button on WinPhone or Android, those methods will not invoke because currently there are no hooks in XF for Prism to hook into.  Also, there is no ability to prevent a back operation when invoked from a hardware button.  I am working with Xamarin to see if this is something that they can provide in their framework.

You are correct. GoBack will pop the current view and go back to the previous page.

INavigationAware methods will only work when using the INavigationService method calls.

**Comment by brianlagunas** [comment]
By the way, your second scenario is fully supported and will work as expected.

**Comment by INRIX-Eric-Hargitt** [comment]
Using the preview version, I was able to make this work. I'm having a different issue, but I'll open a new thread when I have more info. Thanks for being so responsive and for your work on Prism!

**Comment by brianlagunas** [comment]
Ahhh, yeah I was assuming you were using the latest preview with the nav improvements. As you can see the current stable version has some limitations and issues.

**Comment by brianlagunas** [comment]
I just checked in some navigation improvements with the GoBack method call.  Be sure to check them out.
