### ISSUE TITLE
Create viewmodel with navigation parameters (instead of updating it)

### ISSUE THREAD

**Issue by Haukinger** [PrismLibrary/Prism#367]
When navigating between views, I need to pass around information. The viewmodels cannot work without that, so I have to transfer it from the viewmodel that issues the navigation request to the one that's created for the view. What's the best way to do it with prism?

I see these options:
* the viewmodel implements INavigationAware, and get's its info in OnNavigatedTo -> this has the problem that the viewmodel is in uninitialized state until OnNavigatedTo is called, which makes the code more complicated
* modify RegionNavigationService or RegionNavigationContentLoader to call a viewmodel factory that passes the navigation parameters to the viewmodel's constructor if necessary

If I go for the second option, how should it be done to have a chance of being accepted as a pull request?

**Comment by bartlannoeye** [comment]
What platform are we talking about? Navigation parameters are typically passed around in the OnNavigatedTo method.

Personally I postpone loading any data that requires these parameters until the OnNavigatedTo method. In fact, I postpone all async data loading until that point, I never start these processes in the constructor. You typically want snappy navigation and then a loading indicator instead of waiting an extra second before navigation is done.

**Comment by Haukinger** [comment]
I'm on windows desktop, i.e. WPF. Delay is not a problem for me, as I pass the (rather small) model around in the navigation parameters. If the viewmodel doesn't need to handle the uninitialized state, I can keep the code simpler.

**Comment by brianlagunas** [comment]
Thanks for the question.  As @bartlannoeye pointed out, guidance from Prism is not to pass parameters via construction of your objects but rather during the navigation process using the INavigationAware.  What happens when you want to navigate to this view again?  Well, now you are forced to keep recreating it or duplicate your code.  Also, you are dealing with a container so just to pass a parameter via ctor is adding more complexity to your code base as you have to add infrastructure in place just to provide this functionality with your DI container.

We do not recommend passing parameters via the ctor.  If you wish to have this functionality, you can extend Prism to achieve your desired functionality.  We will not be adding this to the Prism code base.
