### ISSUE TITLE
Create a CompoundCommand For Chaining Commands

### ISSUE THREAD

**Issue by Shayon** [PrismLibrary/Prism#383]
I would like to have a `CompoundCommand` where I can chain multiple commands to all be fired on one execute.  This would be similar to `CompositeCommand`, but without all the cross ViewModel stuff.

**Comment by brianlagunas** [comment]
How is this different than having a single command call multiple methods?

**Comment by Shayon** [comment]
Okay. So from what I understand about your question, I would do something like:
```
public ctor()
{
     _saveCommand = new DelegateCommand(_Save);
}
readonly ICommand _saveCommand;

public ICommand SaveCommand { get { return _saveCommand; } }

void _Save()
{
    // Do save stuff
    _Exit();
}

void _Exit()
{

}
```
I see a dependency here that I don't want to have. I don't want my `_Exit` method inside of my `_Save` method, but I do want one command to chain into the other.

What are your thoughts on an implementation like this?https://gist.github.com/Shayon/39e4042dfa32c77831fb

**Comment by brianlagunas** [comment]
Well, that's not a dependency.  That's just logic.  Methods call other methods in code.  If your logic requires and Exit method call, then it needs to have an Exit method call.  Essentially all you are doing is making your method calls via an ordered list of methods.  They have to be defined in a specific order or it breaks.  What happen if one command's CanExecute delegate returns false, while the others return true?  What if that occurs in the middle of your logic chain?  Very prone to bugs.  You can accomplish the same thing by adding a method to your VM that takes in multiple delegate methods instead of commands.

Thanks for the idea, but this is not something we will be adding to Prism.

**Comment by brianlagunas** [comment]
By the way, what you would really want to do is something close to this:

```
void Save()
{
    if (PerformSave())
         Exit();
}

bool PerformSave()
{
    ....
}

void Exit()
{

}

```

You remove your "dependency" and still keep your logic separated into their proper concerns.
