### ISSUE TITLE
IView for testing scenarios

### ISSUE THREAD

**Issue by Crio1979** [PrismLibrary/Prism#403]
Having to implement IView was a pain. Good job for changing that. However, in testing scenarios it would be good to have an IView or something similar that could replace the actual view (typically a UserControl). Otherwise it is hard to integration test PRISM based GUIs because there is really no way to mock the View unless we use mocks for PRISM itself.

**Comment by brianlagunas** [comment]
What are you testing in your View?  Are you only checking to see if a DataContext was set to a VM?  If so, that might not be worth testing since the VIewMOdelLocator is already covered with the Prism tests.  Also, most unit test libraries support testing views, like MS Test, which is what all tests are written in for Prism.Wpf, including testing the views.
