### ISSUE TITLE
Notify View-Model when View.Loaded and View.Unloaded events raise.

### ISSUE THREAD

**Issue by Jalalx** [PrismLibrary/Prism#41]
I think this is a good Idea to notify View-Model when associated View.Loaded/View.Unloaded event raise. Sometimes you (from inside a View-Model) need to know if View is loaded or not. For example when View still not loaded, if you call `RegionManager.RequestNavigate` it does not works. 

1. One idea is using Triggers and notify view model that view is loaded or unloaded.
2. The second Idea is adding two virtual methods (`Loaded` and `Unloaded`) to `BindableBase` and call them when view loaded or unloaded.
3. Or using a behavior, check if View-Model implements an interface like `ILoadAware`, call `Loaded` and `Unloaded` methods properly.
4. Also it can be implemented in `ViewModelLocationProvider` class.

What's your Idea?

**Comment by briannoyes** [comment]
While I think it is trivial to handle this on a view by view basis with a CallMethodAction wired up in the view, I would agree that it is a common enough requirement that it would be good to have Prism just do this for you.

The only challenge is this: Prism can't do this for you unless Prism is in the loop on View/ViewModel construction. That means we could do it for any Region containment scenario, and we could also do it for any use of the VML. But we could not do anything if a developer news up their own V/VM and marries them with View-First or ViewModel-First patterns that don't involve Prism, which is also fairly common in a lot of Prism apps today.

I like the interface approach since it is consistent with other contracts that Prism goes looking for on Views/ViewModels - like IActiveAware, INavigationAware and so on.

So my only question is - does anyone have any hesitation with us supporting this if it would only be invoked if the view were constructed by a region or uses ViewModelLocator?

**Comment by brianlagunas** [comment]
I am wondering if the use-case is large enough for an app to have this built directly into Prism region functionality.  I would think that having this as a behavior would be better since it allows a view to opt into the Loaded/Unloaded events without having the logic checked every time in the region lifecycle.  I don't see a lot of views in a single app needing this functionality, but rather maybe just a few.  I personally have never had this need, so I am curious how common this really is.

Thoughts?

**Comment by briannoyes** [comment]
Good point, I would say I need it less than 10% of the time, and then a quick drag and drop in Blend and declaration of the method in the ViewModel and I have it wired up with a Behavior in less than a minute, so may not be worth putting "in the box"

**Comment by bartlannoeye** [comment]
In Windows 8 I used to solve this with a Behavior, but only needed it on a few screens (over a span of 2 years+).

**Comment by brianlagunas** [comment]
I haven't tried this yet, but shouldn't you be able to use the InvokeCommandAction to execute a command on the loaded and unloaded events?

**Comment by briannoyes** [comment]
Sure, that would work too, but this is one of those places where commands feel a little heavyweight to me, since there is no explicit user interaction that triggers this and there is no enable/disable that would apply to this scenario. So I always use CallMethodAction instead for a direct method invocation on the VM.

**Comment by brianlagunas** [comment]
Good points

**Comment by Jalalx** [comment]
So if you all agree that this is not a "common enough requirement", let's close this issue.
