### ISSUE TITLE
Is there any implementation of ProjectionManager and Prism together?

### ISSUE THREAD

**Issue by tjones0808** [PrismLibrary/Prism#418]
I am trying to implement the projectionManager to project views to different monitors. The microsoft implementation completely implements this without using mvvm and so my question is has anybody implemented projectionManager with prism and uwp?

**Comment by brianlagunas** [comment]
Well, this is definitely an interesting question.  I think this question my be better placed on our StackOverflow tag so that you get a wider range of eyes on your questions.  I would also recommend not limiting this to Prism but rather MVVM, because MVVM really doesn't have a lot to do with Prism in general.
