### ISSUE TITLE
Cancel in IConfirmation

### ISSUE THREAD

**Issue by buldo** [PrismLibrary/Prism#430]
I think that nullable Confirmed property in IConfirmation can be very sutable for cases like Yes-No-Cancel dialog. Or boolean property Canceled.

I can implement this feature if You will approve this issue.

**Comment by brianlagunas** [comment]
Not a bad idea, and I can see where that could be useful.  I'm not sure we should change the current IConfirmation interface as that would be a very large breaking change.  But we could possibly create a new interface called something like IConfirmationCancelable (need to think of a good name), that would support this.

If we did this then I have some concerns around it being confusing since the default ConfirmationWindow has a "Cancel" button, yet sets the Confirmation = false.  If we were to add this new confirmation type, then it's cancel button would either set a new nullable Confirmation property to null, or an additional Cancel property = true.  This confused me just writing it down.  I guess if we created a separate interface and then had the default Confirmation dialog inherit that one as well, and then modify it to set the new Cancel property on the new interface on the "Cancel" button, then maybe it wouldn't be so bad.

@briannoyes and @bartlannoeye , what do you guys think of this addition?

**Comment by buldo** [comment]
@brianlagunas, in our project I created interface ICancelableConfirmation that inherits from IConfirmation an have property boolean property Canceled. Cancel button still sets thr Confirmation = false, but it also sets the Canceled = true.

**Comment by brianlagunas** [comment]
I am closing this and including it in the discussion for a compete overhaul of the popup behavior in #864
