### ISSUE TITLE
TemplatePack for WPF 

### ISSUE THREAD

**Issue by chr1sk0n** [PrismLibrary/Prism#436]
There is a minor bug in the template pack when using it for WPF projects. After selecting the project  (module) template for WPF by using a name like PDFReader.UI the module class will not generated correctly and an error will be shown.

**Comment by brianlagunas** [comment]
Yeah, I just found this one too.  It's because of the "." that is in the name.  I haven't figured out a way to detect that in the template, so I'm not sure of a fix yet.

I am thinking that I could just create a standard Module file name and use that every time, but I personally don't like that idea.  I'm busy with my full time job right now, but I will investigate how to address this as soon as I can.

**Comment by chr1sk0n** [comment]
Great. Thanks a lot.

**Comment by brianlagunas** [comment]
This should be fixed in the next update.
