### ISSUE TITLE
BackPressed on top should not exit application

### ISSUE THREAD

**Issue by ceee** [PrismLibrary/Prism#437]
Hi!

The Prism.Windows.PrismApplication handles the `GoBackRequested` event from the `DeviceGestureService` like the following (in [OnGoBackRequested](https://github.com/PrismLibrary/Prism/blob/fe456fc5604cdf70514613f7fbae4f66ac9cf94d/Source/Windows10/Prism.Windows/PrismApplication.cs#L375)):
1. Check if `CanGoBack`. If yes, go back.
2. Check if hardware buttons are present and the event was triggerd by the hardware back button. If yes, **exit**/terminate the application.

The navigation guidelines for modern apps say that you should not terminate the application. This is the case since 8.1. (see Application.Exit method [remarks](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.application.exit.aspx))

By using exit for the back button you successfully prevent Windows from managing the app lifetime and usage of automatic suspension/termination.

My suggestion is to remove the current implementation and don't handle it by default.
If an application really needs this behaviour (for whatever reason) they can opt-in by adding this code in a `DeviceGestureService.GoBackRequested` event listener.

Problem with the recommended changes is that it would lead to unexpected behaviour in existing apps. However I would not recommend some sort of opt-out functionality for the reason I've mentioned above.

What are your opinions on this?
And what I am really interested in is, what were your reasons to handle it that way? _(PS. I couldn't mention the user who commited the code as he isn't on github anymore afaik)_

If you think this is a good idea I would be happy to create a PR.

**Comment by brianlagunas** [comment]
@briannoyes and @bartlannoeye what are your thoughts?

**Comment by briannoyes** [comment]
When we added this I checked on the Windows Platform MVP list whether there was still explicit guidance like there was in 8.1. What I got back was similar to most of those UX guidelines that were pretty rigid in 8.1. - in UWP the answer is generally "do what makes sense for your app and your users". There is not a "you should always do this" mentality to any of the UX in UWP (because that was a lot of what turned developers off to WinRT).

So I think probably the right approach is leave what is there as is, but add a property somewhere that you can set to make it not exit the app if that is the desired behavior.

**Comment by brusMX** [comment]
Hey guys in Windows Phonw (UWP win 10) this issue is very present.
I have noticed that you guys have a pull request to solve it on Mobile.
Can yo merge this pull request to master so we can have it on the last version?
https://github.com/PrismLibrary/Prism/pull/477/files

**Comment by brianlagunas** [comment]
Fixed with the new merge of Template10
