### ISSUE TITLE
Navigation service in Xamarin Forms forces modal navigation

### ISSUE THREAD

**Issue by ciprianjichici** [PrismLibrary/Prism#439]
Hello,

I have the following scenario: one NavigationPage (MainNavigationPage) that has in its root a MasterDetailPage (MainPage). I start from MainPage/Detail1 (MainPage has Detail1 as its detail page).
From MainNavigationPage, I want to go to MainPage/Detail2/Content1. Basically, I want to change the detail of MainPage to Detail2 and then advance the entire navigation stack to Content1, so that when Content1 is displayed, it has a back button that sends me back to MainPage/Detail2.

At the moment, the navigation logic forces the display of Content1 to be modal which is not what I want (this happens because Detail2 is not a NavigationPage). If my starting point is MainPage/Detail2 and I want to go to MainPage/Detail2/Content1, everything is ok and it behaves as expected.

I think that the check
`newDetail is NavigationPage ? false : true`
that happens in PageNavigationService - ProcessNavigationForMasterDetailPage is too restrictive and it blocks the kind of scenarios presented above.

Is there something fundamental about the navigation engine that I am not getting here?

Thanks a lot,
Ciprian

**Comment by brianlagunas** [comment]
Yes, there is a fundamental concept you are missing about navigation in Xamarin.Forms in general.  You don't wrap a MasterDetail in a NavPage in order to get a back button for a detail page navigation operation.  You set the MainPage as the MasterDetail, and wrap the Detail page in a NavigationPage.

Essentially you set the MasterDetailPage.Detail = new NavigationPage(new MyView());  Then you can call Navigate from MyView and it will behave as you expect.

In order to do that with Prism, assuming your app is launching for the first time, simple call `NavigationService.Navigate("MyMasterDetail/MyNavigationPage/MyView")`.  Then you call Navigate in the MyViewViewModel to any other view and it will be inside the NavigationPage as you expect.

Now, there is a bug in the latest version of Xamarin.Forms in this scenario in which the back button never turns into the hambuger button again when you navigate to another Detail page.  It has been logged here:

https://bugzilla.xamarin.com/show_bug.cgi?id=38105

This should be fixed soon.
