### ISSUE TITLE
[XF] creating Master Detail application and questions

### ISSUE THREAD

**Issue by WarBorg** [PrismLibrary/Prism#448]
I like the new navigation system you implemented but I have a few questions about it:

1) is there a way to use viewmodel navigation with the deep linking features ?

2) I have an app I am working on and it has a masterdetail page at one point which works but not exacly how I want it, to explain:

- the app has a login page and a main page which don’t require a masterdetail page
- after selecting something in the main page I need to go to a masterdetail page, the master page is a menu with a list and the details page is a navigation page which will have different other content pages as children depending what is clicked in the master page, and this is where I get confused:

3) first off the layout gets all messed up since the app dosen’t know I swiched to a master/detail
so the navigation goes something like this:

- app strat :

```C#
protected override void OnInitialized()
{
  InitializeComponent();
  NavigationService.Navigate(“MainNavigationPage/LoginPage”);
}
```

- click on login button:

```C#
_navigationService.Navigate(“MainPage”, navParams);
```

- click on a button in the main page

```C#
_navigationService.Navigate(“MyMasterDetailPage/MyNavigationPage/MyDetailsNewPage”);
```
please check screenshots here https://drive.google.com/folderview?id=0BxnHizQV5zzKX0gzU29QLVdUbDQ

4) you specified in the other blog post that the navigation system is smart and will know that I am in a master page and change the detail page but still keep the master (menu) page, I tried with different configurations but this is not happening :
- this is from the master viewmodel command (tried all possibilities)

```C#
_navigationService.Navigate(“MyMasterDetailPage/MyNavigationPage/MyNewDetailsNewPage”);
_navigationService.Navigate(“MyNavigationPage/MyNewDetailsNewPage”);
_navigationService.Navigate(“MyNewDetailsNewPage”);
```

all the code above will bring up a new page over the previous one and not just change the details page (see screenshots above)

5) how should the four pages (masterdetail, master, navigation and detail) look like in XAML and be linked from a viewmodel perspective ?
- for the example above the xaml page in the masterdetail page looks like:

```XAML
<MasterDetailPage.Master>
    <local:MyMasterPage />
</MasterDetailPage.Master>
```

should I add a default details page as well ? and if so should it be contained in a navigation page ? something like:

```XAML
<MasterDetailPage.Detail>
    <local:MyNavigationPage>
      <x:Arguments>
        <local:MyDetailsPage />
      </x:Arguments>
    </local:MyNavigationPage>
</MasterDetailPage.Detail>
```

6) related to the one above, should there be a viewmodel for the masterdetail page ?

7) is there a simple way to communicate with the viewmodels of the master and detail pages from the masterdetail viewmodel ?

8) should the navigation be made from the masterdetail viewmodel or the master viewmodel ?

9) I know you mentioned in a comment that pressing the back button in a masterdetail configuration will not cycle back throght the detail pages, can this be overriten ? because the master (menu) page links will be kind of a history of the detail pages that were open, when you hit the back button the one you are in gets deleted and you go to the previos one

those are a lot of questions and maybe in the future I can help you add some documentation about it or an app example would be very nice

I have made a demo app you can access it here and see what I am talking about in more detail

https://drive.google.com/open?id=0BxnHizQV5zzKWDM4MzNPdnVJTmM

thank you in advance

**Comment by brianlagunas** [comment]
1) Yes, anytime you navigate with multiple page ids in the Navigate method, it uses deep linking
3) You don't put a login screen in a NavigationPage. You log in using a modal login, then pop it after success, then navigate to you intended target.  Otherwise, your users can always get back to the loging screen by hitting back.  You also don't want to put a MasterDetail in a NavigationPage.  Now you have too many navigation elements in your view, and it's a very confusing user experience.
4) Yes, it smart enough to now if you are navigation from a MasterDetail.  So make sure you are navigating from a MasterDetail, and not the MasterDetailPage.Master, or the MasterDetailPage.Detail.  Navigation is always relative to where you are calling Navigate.
5) No, you don't need to set a Detail if you use the NavgationService to get there.  The buttons in your Master need to call the Navigate command from your MasterDetailPage.
6) Yes, definitely.  Otherwise you are not navigating from a MasterDetailPage.  You are navigating from somewhere else.
7) Not sure what you mean here.
8) As mentioned above, if you want to change the Detail, then the navigation must come from the MasterDetailPage.  Navigation is relative to where you are calling Navigate.
9)  No, and you don't want it to be.  That would make for a very confusing navigation paradigm.

**Comment by WarBorg** [comment]
2) ok, the login page was besides the point the problem was how do I navigate from a normal page with navigation to a masterdetail one cause I can have like 3 normal content pages and then a master detail ? I have seen examples on the net where they would have to change the App.MainPage from the initial navigation page to the new masterdetail page, is there a easier way ?

7) I ment, how do I communicate from the master viewmodel to the masterdetail viewmodel to send the cutton command ? should I use messanging ? or am I missing something basic on how these could coummunicate ?

**Comment by brianlagunas** [comment]
2) Just call Navigate("target").  If I am on ViewA and want to navigate to a MasterDetail, from viewAViewModel, simply call Navigate("MasterDetailPage/DetailPage").  If your detail page needs to be in a navigationPage then Navigate("MasterDetailPage/NavigationPage/DetailPage");
3) Just bind the buttons in your Master to the MasterDetailPage's ViewModel Commands.  There should be no messaging required.  From your MasterDetailPageViewModel you simply navigate to your target. Navigate("DetailPage"), or if it needs to be wrapped in a NavigationPage use Navigate("NavigationPage/Detail");

**Comment by WarBorg** [comment]
3) yes I got that,  but how do I get a hold of the masterdetail page view model from the master page xaml? do I need to do the command binding with something like parent data context or... ?

**Comment by brianlagunas** [comment]
Depends on how your have your pages structured.  However you have it structured, you have to call the command from the MasterDetailPage BindingContext.  If you can rely on BindingContext inheritance great, if you need to make the call more explicitly then do that.

**Comment by ahmedhasanmotiwala** [comment]
I am facing a problem, its related to above conversation,.. In my case when user login successfully I navigate like this NavigateAsync("MainMasterDetailPage/MainNavigationPage/HomePage"), when click on menu button and then want to go to the profile page I just say NavigateAsync("ProfilePage") or I can say NavigateAsync(new Uri("ProfilePage", UriKind.Relative)... ok .. ? but in this case the navigation bar for the "back" button is not showing.... but if I give the uri like this NavigateAsync("MainMasterDetailPage/MainNavigationPage/HomePage/ProfilePage") the navigation bar or default back button for ios is showing.... but when I click on back button it always go to the HomePage ... thats not right because I have multiple tabs on home page like Contact Page ... if I go to contact page then click on ProfilePage from menu then It goes to ProfilePage after that when click on back button I goes to "HomePage" but It should go to contactPage ..... Kindly help...

**Comment by ahmedhasanmotiwala** [comment]
Summary: If I am not wrong .. 

- when I say NavigateAsync("ProfilePage")  I am giving the relative uri and I am not getting navigation bar or back button which is needed,

- when I say NavigateAsync("MainMasterDetailPage/MainNavigationPage/HomePage/ProfilePage") I am giving the absolute uri  and getting the back button but I always go to the home page, which is not correct.

- I have tried to place a custom button on ProfilePage and say navigationService.GoBackAsync();
It works perfectly with this navigation NavigateAsync("ProfilePage") but I don't want my custom button I just want default back button for IOS.

**Comment by brianlagunas** [comment]
* In Xamarin.Forms, the only way to get the navigation bar is to wrap your pages in a NavigationPage
* This is correct.   You are on the ProfilePage, then you hit back and it goes HomePage.  You are now at the root of the navigation Page which is the Detail of the MasterDetailPage.  You would need to hit the hardware back button again in order to get back from the ProfilePage since that appears to be a modal navigation
* You should study up on how navigation works in Xamarin.Forms.  Prism uses the XF navigation APIs directly, and does nothing special or different.

**Comment by ahmedhasanmotiwala** [comment]
Hmmm.. Thanks much Brian.... I am trying..

**Comment by pcastilho** [comment]
**Hi Brian, how are you?**

My name is Paulo I'm from São Paulo - Brazil, I'm starting to use prism with xamarin and I have a doubt, I have marterdetail in it I have a menu of pages, the photo and the username of the logged in user.

I need to pass to masterdetail the Model that contains these data to treat it in the viewmodel, how can I perform this process, could you give me a hint how to do it?

**I'm sorry I barely confused the understanding. my English is not very good.**

Thanks!
