### ISSUE TITLE
Suggestion: Provide ValidateableBindableBase for WPF

### ISSUE THREAD

**Issue by HerrLoesch** [PrismLibrary/Prism#45]
I like the three view model types in Prism for WinRT. Unfortunately in WPF we only have BindableBase. Even ViewModelBase is not really needed in WPF, I guess that ValidateableBindableBase would be an appreciated extension.

**Comment by briannoyes** [comment]
You might want to check out my article here for a head start on that: http://blog.pluralsight.com/async-validation-wpf-prism

**Comment by briannoyes** [comment]
FYI - will be working on porting the validation support from Prism for Windows Runtime to Prism for UWP in the next week or so. There are a couple of changes I would like to make in that process including making the validation mechanism more pluggable, and intend to try to make it so as much of it as possible can go into the base Prism PCL so it will support all Prism platforms.

**Comment by znakeeye** [comment]
My custom ViewModelBase has this validation stuff (actually, I think I got it from Brian's article). Do you want me to create a PR or is this feature already in the workings?

**Comment by briannoyes** [comment]
I've already got a specific design in mind, just need to find time to get to it. To me it would be inappropriate to put it on ViewModelBase because just as often it is the model objects that need the validation support and it would be weird to put a ViewModelBase base class on a model object. But one of the deficiencies of the original design in Prism for WinRT was that you needed the ViewModel(Base) class on your ViewModels for the navigation and state persistence support, but often wanted to have the validation support on the ViewModel properties as well, but could not achieve that with single inheritance in .NET. The other things we want to do include: put as much of the implementation in the Prism.Core PCL to avoid total duplication in the platform specific libraries, and have a pluggable mechanism for the specifics of how validation is performed so that you can either use the default strategy of Data Annotations (which are not supported in a PCL) or be able to plug in something else (i.e. the FluentValidation framework).
