### ISSUE TITLE
Support for some lightweight  IoC container

### ISSUE THREAD

**Issue by YehudahA** [PrismLibrary/Prism#457]
Right now, prism [WPF] supports Unity, MEF, AutoFac, StructureMap and NInject.
All these containers are heavy or medium on the scale, and no even one lightweight.

Benchmarks:
https://github.com/danielpalme/IocPerformance
http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison

I suggest to add a provider for some lightweight container, like LightInject or [preffered] SimpleInjector. 

SimpleInjector is a popular, well documented and active open source project with a large ecosystem and people contributing to it.

**Comment by bartlannoeye** [comment]
SimpleInjector was added in #335 and you can find a pre-release package on this feed: https://www.myget.org/F/prismprerelease/api/v3/index.json
We haven't had any positive/negative feedback on the package since then, so feel free to test it, give us feedback and then we'll promote it to nuget.

**Comment by YehudahA** [comment]
Thanks, but it's for UWP...
I will try do it for WPF.

**Comment by bartlannoeye** [comment]
Aha I overlooked the WPF tag, sorry. Feel free to submit a PR :)

**Comment by christiannagel** [comment]
What about adding Microsoft.Extensions.DependencyInjection? This should be lightweight. https://github.com/aspnet/DependencyInjection

**Comment by YehudahA** [comment]
The main job is with ```RegionNavigationContentLoader```.
The default loader resolves content by key, while as default SimpleInjector doesn't support registration by key, as descripted [here](https://simpleinjector.readthedocs.org/en/latest/howto.html#resolve-instances-by-key).

Q: why prism navigation is made using ```Uri``` instead of natively using of ```Type```?

**Comment by brianlagunas** [comment]
Because you shouldn't be referencing View types in your ViewModel.  If you rely on View types, then you have violated MVVM.

**Comment by brianlagunas** [comment]
Since SimpleInjector does not have the features required to work with Prism, I am closing this issue.

**Comment by Haukinger** [comment]
There's a difference between using a type as a type, to reference an instance or reflecting or whatever - I understand that's wrong, because you make the viewmodel untestable - and using the type as a refactoring-safe and type-safe way to express a text constant, that is, the type's name. It won't interfer with tests, because using "typeof(MyView).Name" ist just a better way of saying "MyView". Anyway, as soon as you navigate to a view in a viewmodel, you're referencing the view in the viewmodel, whether by string or by type.

**Comment by brianlagunas** [comment]
> Anyway, as soon as you navigate to a view in a viewmodel, you're referencing the view in the viewmodel, whether by string or by type.

No, you're not.  You are providing a key or unique identifier, which may or may not be related to a view object.  When objects are registered for navigation, their class name is not always used as the navigation key, but rather some other value is provided instead.  Using a key also removes a dependency on assemblies and object types which further supports the modularity, and dynamic assembly loading aspect of Prism.

**Comment by YehudahA** [comment]
On the other hand, using literal string as navigation identifier is a very big complication.
It's not maintainable, and not testable.

**Comment by brianlagunas** [comment]
Once again, you are incorrect.  It is easily maintainable when you don't use magic strings, but rather constants, and it is especially easy to test because you aren't dealing with view objects or types.

**Comment by YehudahA** [comment]
So, Instead of constants we can use with abstraction, and replace the typeof(MyView).Name with typeof(IMyView).Name.

**Comment by brianlagunas** [comment]
If you don't mind creating empty marker interfaces for every view in your app for the sole purpose of using a strongly typed name; then sure, go for it.  If that's the case you are better off creating extension methods for both registering your views for navigation with your container, and for RequestNavigate to use a generic instead.  Then you don't even need to pass in a name at all.

**Comment by YehudahA** [comment]
OK, I will fix it. Meanwhile, I'm reading all your blog..

**Comment by Haukinger** [comment]
> If that's the case you are better off creating extension methods for both registering your views for navigation with your container, and for RequestNavigate to use a generic instead. Then you don't even need to pass in a name at all.

Why does provide Prism one of them and not both (or none of them)?

Also, Brian, I'm with you that one shouldn't reference assemblies just for the typeof-navigation. But the reasoning behind that is more along the lines of "views should be internal" than "don't reference view types in viewmodels". If the navigated-to assembly is in the same assembly as the navigating viewmodel, it doesn't apply.

Many times you're navigating to a related view that resides in the same assembly (or module), and then I still think typeof-navigation has only advantages over string-navigation.

**Comment by brianlagunas** [comment]
> Why does Prism provide one of them and not both (or none of them)?

Because we aren't going to encourage referencing view types in ViewModels.  Now, we have something similar for Xamarin.Forms, but we restrict the generic from being a view type.  Basically, you can't use a View type as the strongly type key to prevent you from trying to reference view types in your VM.

> If the navigated-to assembly is in the same assembly as the navigating viewmodel, it doesn't apply.

This isn't an accurate statement.  There is no situation in which you should be referencing your View types from within your ViewModel.

**Comment by Haukinger** [comment]
> There is no situation in which you should be referencing your View types from within your ViewModel.

Except in case where the view is known to the viewmodel anyway, because they sit side by side in the same assembly and the reference is used to avoid a string-reference (which implies that no other information besides the name is used).

We can move to email for this discussion if you like (because I guess, we're going beyond the scope of this issue), but I really would like to fully understand this. _Why is it more important to not reference a known and accessible type for its name only than to remove the maintainability impact of using a weakly type string reference?_

Perhaps my imagination is too limited, but I cannot come up with a situation where this would impact testability. And testability after all has to be the reasoning behind "viewmodels shouldn't reference views", as views aren't testable and viewmodels are conceptually designed to be testable. The view's name, though, can be used in tests - as a string, if the view is not known to the test - to check that the correct navigation is performed, whether or not the viewmodel references strongly or weakly to the view.

**Comment by brianlagunas** [comment]
Just because a view and ViewModel exist in the same assembly doesn't mean the view is known to the ViewModel.  If you want to create a coupling between your View and ViewModel, then go for it.  The pattern police will not come to arrest you.

The great thing is that Prism doesn't care how you do it.  It is flexible and extensible enough to allow you to do anything you want.  So pick your poison and build great apps.

**Comment by YehudahA** [comment]
I think that I have a good solution to navigation by key.

I created a simple service:

``` cs
public interface ITypeLocatorService
{
    void Register(string key, Type type);
    bool TryGetType(string key, out Type type);
}
```


Configuration in the ```Bootstrapper```:
``` cs
typeLocator.Register(MyKnownTypes.SomeViewKey, typeof(SomeView));
```


Resolving in ```RegionNavigationContentLoader```:
``` cs
private Type GetTypeCandidateByContract(string candidateTargetContract)
{
    Type type;
    var resolved = typeLocator.TryGetType(candidateTargetContract, out type);

    if (resolved)
        return type;

    type = Type.GetType(candidateTargetContract);
    return type;
}
```
