### ISSUE TITLE
Unsigned dlls

### ISSUE THREAD

**Issue by joelweiss** [PrismLibrary/Prism#472]
Please consider releasing an unsigned version as well, for those who don't require it, and don't want to deal with the pain that signed assemblies bring with it.

See structuremap/structuremap#450

**Comment by jeremydmiller** [comment]
Hey guys, instead of inflicting strong naming pain and punishment on folks that don't need/want the friction, have you considered recommending StrongNamer usage instead?

**Comment by brianlagunas** [comment]
StrongNamer looks great, but we are not able to remove strong naming from Prism for WPF.  Prism has been signed ever since its creation in the Microsoft P&P team.  There are too many critical apps that rely on the strong naming that would break if the string naming would be removed.  Trust me, we've tried before.  StrongNamer is a cool solution but does not fix the problem of breaking a majority of WPF apps without a reliable way to provide guidance for those broken apps to use StrongNamer assuming that some companies will even allow it in the first place.

**Comment by brianlagunas** [comment]
Basically, if you don't need strong naming, then fork the repo and build it unsigned.  The beauty of OSS.

**Comment by brianlagunas** [comment]
Also, we do not have the time or resources to support managing separate builds and duplicate NuGet packages for the purpose of having unsigned assemblies.  We already have 14 packages, I don't want to make that 28.

**Comment by joelweiss** [comment]
Valid point, but when it was a Microsoft project it only supported Unity and MEF, now you support a lot of other containers which makes it not that simple.

Either way, there is no point in having the StructureMap [package](https://www.nuget.org/packages/Prism.StructureMap/) signed if we wont be able to upgrade StructureMap ever.

Might I suggest just having this package unsigned (or maybe only sign the Unity and MEF packages)

**Comment by brianlagunas** [comment]
Hmmm... If we could automate that, then that may be an option.  We already have a **Release** (which is unsigned) and a **Release-Signed** build configuration, so it should be easy to switch in a script.  So far, StructureMap is the only container that is unsigned.

**Comment by joelweiss** [comment]
I don't see any build script. what are you using to build and create the nugget packages?

**Comment by bartlannoeye** [comment]
If I'm correct, only the Prism.WPF.StructureMap assembly has to be unsigned as this one is referencing the unsigned StructureMap, all libraries below (Prism.Core and Prism.WPF) can stay signed. I wouldn't bother switching between both configurations to build, but only switch the Prism.WPF.StructureMap to build its release instead of release-signed configuration in the solution configuration.

**Comment by joelweiss** [comment]
found it, can we just change the paths [here](https://github.com/PrismLibrary/Prism/blob/master/Source/nuspecs/Prism.StructureMap.nuspec#L27) and [here](https://github.com/PrismLibrary/Prism/blob/master/Source/nuspecs/CreatePrismNuGetPackages.ps1#L225)

**Comment by brianlagunas** [comment]
@joelweiss For now we do a manual build and then run this PS script

https://github.com/PrismLibrary/Prism/blob/master/Source/nuspecs/CreatePrismNuGetPackages.ps1

I have a task to automate the build process altogether, but just haven't found time to do it.

@bartlannoeye that makes sense.  I was just thinking that maybe it wouldn't make sense to have signed Prism and Prism.Wpf and an unsigned Prism.SturctureMap.Wpf, but that should work.

**Comment by brianlagunas** [comment]
Okay, we will just modify the Release-Sign configuration to build StructureMap unsigned, and then modify the NuSpecs to get the binaries from the correct location.

**Comment by joelweiss** [comment]
Will try to send a PR soon then.

**Comment by bartlannoeye** [comment]
Don't worry, I'm already on it :+1:

**Comment by joelweiss** [comment]
Thanks.

**Comment by joelweiss** [comment]
Thanks. When is the plan to update the nuget package?

**Comment by bartlannoeye** [comment]
Will have to check with @brianlagunas for that.

**Comment by brianlagunas** [comment]
I'll push out new packages when I have Prism for Xamarin.Forms ready for the next pre-release
