### ISSUE TITLE
Prism.Xamarin OnNavigatedFrom

### ISSUE THREAD

**Issue by grzegorzbojar** [PrismLibrary/Prism#492]
I am using Prism for Xamarin 6.1.0-pre3. I have A MasterDetail Page with Navigation Page as a Detail + few Views I want to navigate between (in that Navigation Page). I navigate between them using Navigate Command in MasterDetail (Menu in Master Page) using e.g.
`_navigateService.Navigate("NavigationPage/ViewA")`
It does work (with already mentioned bug https://bugzilla.xamarin.com/show_bug.cgi?id=39104).
Unfortunately, I found out that when Navigating from ViewA to ViewB there is no OnNavigatedFrom executed in ViewA. It is executed only when executing Navigate command in ViewA directly. Is this a bug? Is there any workaround?

**Comment by brianlagunas** [comment]
Actually, this is a scenario I didn't consider.  Essentially what happens is the NavigationPage is reused, but it's navigation stack is cleared (PopToRootAsync) and the new target page is place on the navigation stack, then the first Page on the Stack is removed (RemovePage).

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/PageNavigationService.cs#L191

I think I can just pass in the currentNavRoot into the DoNavigateAction here instead of the NavigationPage.  This makes sense when dealing with a MasterDetailPage scenario, but does it make sense when using the NavigationPage by itself?

Essentially, if I am on a NavigationPageViewModel and call Navigate, would I expect the same behavior that I get when reusing the NavigationPage in the MasterDetailPage scenario?

Good find.  I'll have to think about this one.
