### ISSUE TITLE
UWP app localization with ShellPage

### ISSUE THREAD

**Issue by senkia** [PrismLibrary/Prism#502]
Hi,

I'm using Prism for UWP apps in my application and I have a shell page created in the overridden CreateShell(Frame rootFrame) method in my app.cs so it acts as a frame around all of my pages with a SplitView control. I'd also like to localize my app and be able to override the user's default language by setting the ApplicationLanguages.PrimaryLanguageOverride property to the desired language's BCP-47 language tag. 

It actually works great on every page (although I have to reload the current page to use the new language) but the language of the shell page remains the same even after navigation. That's because the shell page is instantiated only once at the launch of the app so I have to restart the app manually to see the changes take effect on the shell. Is there any way to either recreate the shell page or set it's language at run-time or do You have any suggestions to solve this problem with a different approach. 

Thanks

**Comment by bartlannoeye** [comment]
This is not an issue of Prism, but how the localization in UWP works.

What I usually do for pages that should be reloaded on changing the language, like the 'Settings' page where you change the language (or your shell), is bind the localized text instead of using x:Uid and trigger a PropertyChanged event (like you used to do on the earlier versions of Windows Phone).
