### ISSUE TITLE
Bootstrapper sequence between InitializeModules and CreateShell

### ISSUE THREAD

**Issue by zzczzc004** [PrismLibrary/Prism#521]
I have a problem about why the **Bootstrapper** has been implement that **InitializeModules**() is called after the **CreateShell**()?
For my scene, some types are registered to container in IModule's Initialize methond depend on the configuration. However, this type need to be used in MainWindowViewModel to monitor it's change, so I will start to monitor the change event in the construction of MainWindowViewModel. But the CreateShell is call first, the type is still not been registered. In my opinion, the CreateShell() should be the last step in the Bootstrapper's run so that all the initialize is done.

**Comment by brianlagunas** [comment]
The bootstrapping process is correct.  If CreateShell as last the you would not be ablt to inject views in your modules, which would be a massive brak and limitation.  The issue is where you are defining and registering your dependencies.  You need to move your dependency registrations around so that the classes that require them can properly reslove the dependencies when needed.

**Comment by zzczzc004** [comment]
@brianlagunas Why do you think it can't inject views from within the modules when **CreateShell** was last step? I can't understand it.
I try to modify **Run** function's implement like this and it still can inject view in the modules.
```
public override void Run(bool runWithDefaultConfiguration)
{
    // ....
    if (this.Container.IsRegistered<IModuleManager>())
    {
        this.InitializeModules();
    }

    this.Shell = this.CreateShell();
    if (this.Shell != null)
    {
        RegionManager.SetRegionManager(this.Shell, this.Container.Resolve<IRegionManager>());

        RegionManager.UpdateRegions();

        this.InitializeShell();
    }
}
```

I can't move my dependency registrations to the **ConfigureContainer** function in my scene. Because my main program (A.exe) don't need to depend on both Module B (b.dll) and Module C (c.dll). The interface E is in Module D (D.dll). Now my program A need to use interface E, however the dependency registrations is in the Module B or Module C's **Initialize**. If I put the registration in the **ConfigureContainer**, my A.exe will depend on both b.dll and c.dll. 

Now, my deploy is (A.exe and B.dll) or (A.exe and C.dll), so that the A.exe is not depend on b.dll and c.dll explicitly.

**Comment by brianlagunas** [comment]
I know because you can't inject views into a region that doesn't exist.  If calling IRegion.Add(view) inside the IModule.Initialize before the Shell has been created, it will throw an exception.  You need to move your services out into a separate assembly so that all your modules and shell can use the same service without taking a dependency on each other.

**Comment by zzczzc004** [comment]
OK, I got it, thank you.
