### ISSUE TITLE
Really need some help set prism up with UWP

### ISSUE THREAD

**Issue by Brian-Ding** [PrismLibrary/Prism#550]
I am new to Prism. And it seems all the documents are about wpf, not uwp, except an example here. But i would really need some hello world example with some explanation so that i am possible to understand every line of code about prism. 

Here is my code
App.xaml.cs
![image](https://cloud.githubusercontent.com/assets/11363173/14643978/0e50a38c-0683-11e6-832f-89fd488892ed.png)
![image](https://cloud.githubusercontent.com/assets/11363173/14644046/45bfb434-0683-11e6-97fb-9b5ce216e391.png)
AppShell.xaml.cs
![image](https://cloud.githubusercontent.com/assets/11363173/14644152/a2d04404-0683-11e6-9882-d8a485351c92.png)

But i ran into this exception
![image](https://cloud.githubusercontent.com/assets/11363173/14644174/b938d468-0683-11e6-80e3-f5898a3aa375.png)

All kinds of help are appreciated!

Thank you guys

**Comment by briannoyes** [comment]
Oh no! Another Brian in the mix :) (Myself and Brian Lagunas are owners of Prism now)

In the future please ask this kind of thing on Stackoverflow as we would like to keep the issues here focused on bugs and feature requests.

But for now, here are a couple things to know:
The PrismApplication base class (base for PrismUnityApplication) already registers the NavigationService, SessionStateService, and EventAggregator, so your registrations in the initialize there are unnecessary and redundant.

The particular error you are calling out is because the default navigation service (FrameNavigationService) has a convention for naming views that it expects - that each view is named <yournamehere>Page and that it will be placed in the folder/child namespace from the root named "Views". Then the ViewModelLocator has a convention that it expects the corresponding view model to be named <yournamehere>PageViewModel and be located in a folder/child namespace named "ViewModels".

If you don't like those conventions there are several ways to override methods in the NavigationService and the ViewModelLocationProvider that establish those conventions.

What I would recommend for getting started is to check out my course "Building Windows Store Business Apps with Prism" https://app.pluralsight.com/library/courses/building-windows-store-business-applications-prism/table-of-contents. I created it for Windows 8/8.1, but almost everything in there is applicable to Prism for Windows 10 UWP because we created the latter by doing a direct port of Prism for Windows Runtime. A few namespaces and type names have changed, but the approach and usage is 95% the same.

You can also grab the official docs for the previous release in book form here:
https://www.microsoft.com/en-us/download/details.aspx?id=39042

HTH, Brian

**Comment by Brian-Ding** [comment]
Thank you for your patient answer!

And sorry for posting at wrong place(；′⌒`)
