### ISSUE TITLE
Types that inherit from BindableBase are not serializable by data contract

### ISSUE THREAD

**Issue by michaelnero** [PrismLibrary/Prism#57]
Would it be possible too add the [Serializable] and/or [DataContract] attributes to BindableBase? Without that, types that inherit from BindableBase are not serializable by data contract.

**Comment by brianlagunas** [comment]
Are you using BindableBase for your business objects too or just ViewModels?  Are you trying to serialize ViewModels or just business objects, or both?.  I think that [DataContract] is the attribute that is available in the PCL, so if we added an attribute it would most likely be that one.  But I would like to better understand the scenario.

**Comment by brianlagunas** [comment]
Also, which serializer are you trying to use?  The built-in .NET serializes are slow, but if you use a modern serializer like JSON.NET for instance, the policy there is to serialize everything public, unless it is marked as “not serializable”.  Meaning no attribute would be needed.  This is the approach other frameworks have taken since when you start adding one attribute, then requests for other attributes normally follow just to support inferior serializers.

**Comment by michaelnero** [comment]
I have an object that I serialize to an XML column in SQL Server, so that type is of course decorated with [DataContract]. I have an API endpoint that sends down that XML content as a property on a container object, and the phone app then deserializes the XML content sometime after it receives it. This is why my phone app has a type using the [DataContract] attribute.

I also propagate that deserialized object to various components throughout the app, and it's exposed via some view models, which is why it implements BindableBase.

Of course, I could rethink all of this if there's no desire to add [DataContract] to BindableBase. But at some point I _do_ have to serialize to XML because SQL Server doesn't support JSON like, say, postgres.

**Comment by brianlagunas** [comment]
Well, I'm a little hesitant on using the attribute to support explicit data contracts, because it's possible we break people that are using implicit data contracts.  One suggestion would be to use separate model types from your data contracts and to use something like AutoMapper to map the data back.

This is a good post to refer to regarding the implications of adding the DataContract attribute.

http://briannoyes.net/2014/09/29/be-aware-of-differences-in-explicit-and-implicit-deserialization-with-dcs/

**Comment by briannoyes** [comment]
The problem is that if we introduce [DataContract] on the base, it can break the serialization of anyone who has been using it as is as an implicit data contract. See my post here on some of the problems with doing this: http://briannoyes.net/2014/09/29/be-aware-of-differences-in-explicit-and-implicit-deserialization-with-dcs/.

Michael, are you using explicit data contracts in your serialization instead of implicit serialization that you can do with any public type with public properties? If so, is it so you can cherry pick which properties you actually serialize? If so, possibly a better solution instead of us introducing something that could be breaking change to a much larger audience than it solves something for, you could have separate objects you use for your serialization, and use AutoMapper as a simple way to transfer the data into those objects before you serialize. Then you are in full control of the types you are serializing.

**Comment by michaelnero** [comment]
Hey guys, I'm okay with a "no" on this one -- although a very helpful and polite no. ;-) -- because I can certainly understand the consequences of adding an attribute to a base class where it hadn't applied before.

I'll work around it by being a little smarter about what I send back through my API endpoint. Thanks for the time!
