### ISSUE TITLE
[XF] Feature Request: NavigationService expose the stack of pages  

### ISSUE THREAD

**Issue by tombby11** [PrismLibrary/Prism#581]
AS a developer for Xamarin.Froms  I would like to see a property in the navigationService, that tells me what is the active page and the previouse pages (the stack)  or at least the prevouse page . 

possible use cases

- Knowing the current active page , would help in determining what kind of behavior should be taken. An example can be to show the master page if the current page is a detail page and we invoked GoBackAsync()  
- The previous page property will show us that we are already back to the first page , so when I as a developer know that there are no pages to go back to , instead of calling GoBackAsync()  we could exit the app .

**Comment by brianlagunas** [comment]
Well, one thing is for sure; the INavigationService will **never** expose any Page objects.

I see problems with having/maintaining a CurrentPage property.  First, what would constitute a current page?  For example, what if I am on a MasterDetailPage, what's the current Page?  The master, the detail, or the MasterDetailPage itself?  What about a TabbedPage, or a CarouselPage?  What is the current page?  I think this changes depending on the scenario.  Knowing this, it would be extremely difficult to control this.  Besides, there would be a technical challenge since the INavigationService is instance based (each page gets its own instance), so maintaining a CurrentPage/PreviousPage property would be problematic given that we are navigating from one service to another VM that has a different service.  We would probably have to use a static property to manage that, and I really dislike that idea.

I don't think we should have a PreviousPage property, but I could possibly see adding a Boolean result coming from GoBackAsync.  So you can check the result of GoBackAsync and if it is false, then there is no Page to go back to, and you know to close the app instead.

**Comment by tombby11** [comment]
Well now GoBackAsync throws OutOfRange Exception when going back from the first page. but sure returning False can be cleaner. 

Regarding exposes pages and current page, I can see what you mean here. But how about instead of showing the pages , you could show the current ViewModel , and the previous viewModel , would that be possible ?

**Comment by brianlagunas** [comment]
What version of Prism.Forms are you using?  No exceptions should be thrown.  Do you have a repro?

I don't think showing a ViewModel will work either for a couple of reasons.  First you don't navigate to ViewModels.  You navigate to keys/ids.  So mixing the concept would be confusing and misleading.  Once again, we run into the problem of what constitutes the Current/Previous items if I'm in a MasterDetailPage, or a CarouselPage, or a TabbedPaged?

**Comment by tombby11** [comment]
You can download the solution with the bug from [here](https://we.tl/I6fcdGhwzd) . 

Regarding the viewmodel and navigation , my thought came from that you can make the viewmodel navigation aware , so i thought maybe it could know where was the navigation and the parameters are coming from , anyway i think this is minor for me now , so no need to implement that :)

**Comment by brianlagunas** [comment]
You're not using the latest version.  If you upgrade to pre-5 the exception won't occur anymore.

**Comment by tombby11** [comment]
Yup still throwing exception , [Here](https://we.tl/megnZsIorr) you go

**Comment by brianlagunas** [comment]
Ahhh, I see what you mean.  I thought it was related to a previous exception that was fixed.  This is actually an exception being thrown from Xamarin.Forms.  You would get this exception if you simply did this:

```
        private async void Btn_Clicked(object sender, System.EventArgs e)
        {
            var p = await Navigation.PopModalAsync();
        }
```

We can probably throw that in a try/catch for that scenario.

**Comment by tombby11** [comment]
Great! that would be good. 
One more last thing about this navigation service. Is it possible to have the option to clear all the pages stack ? 
A usecase for that is if the user decided, after a series of navigation to sign-out and go back to signing-in page. then there is no need to keep the stack of pages especially since then the user might sign-in as an admin so the pages' content would be different. Is that possible or is it also challenging ? Or is there a way to do that already ?

**Comment by brianlagunas** [comment]
For that you simply use an absolute URI.  That resets the Application.Current.MainPage.

**Comment by brianlagunas** [comment]
GoBackAsync now returns Task<bool>.  True if the go back was a success, false if it was not.
