### ISSUE TITLE
Navigation Service GoBack() improvements

### ISSUE THREAD

**Issue by cbordeman** [PrismLibrary/Prism#591]
I'd love to see `INavigationService.GoBack(numberOfPages)` and `GoBack<TPage>()` or `GoBack("MainPage")`.  This was discussed [in this YT comment thread](https://www.youtube.com/watch?v=DYRLcqG2BAY&google_comment_id=z13uynvigo2yjjs4u04ccrlgtyi1wdw5n2g) but I'll describe a couple of use scenarios.

1) An app reaches a customer view page by some means, which can vary.  They click "edit" and go to another page.  90% of the time, after completing the edit, going directly back to the customer view page is unnecessary and the desired behavior is to go backward two pages instead of one.  Bypassing the view screen avoids hitting the server to reload details that may have changed and improves the UX.  In this scenario, `GoBack(2)` is an easy solution.

2) A questionnaire consists of a starting page, a varying number of separate pages for selecting answers (varying enough that one page can't handle presenting all the questions), then a final scoring page.  After the scoring page is presented, the user pressed "Back" and expects to go back to the start.  The page might have no idea how many pages are between the starting page and here, so `GoBack(2)` is less useful than `GoBack("StartPage")`.

I'm aware that an absolute URI could be used to do this cleanly, but you'd lose history before that page.  The way I initially handled this was by analying the `OnNavigatedTo()` parameters and trying to deduce where we're coming back from, then using Dispatcher to call `GoBack()` again.  This is more work, kludgy, and prone to break.  Part of the problem is that pages don't know the back and forward history.

My eventual solution was to wrap NavigationService in one that stores the history itself and does the `GoBack()` repeatedly using Dispatcher.  This doesn't avoid the additional loads and is slow, but it does avoid wacky code in each page.  Pages never use NavigationService directly, and I have to replace all the system `GoBack()` calls to use my service.  It's a mess, really.

**Comment by bartlannoeye** [comment]
What I usually do is remove the intermediate page from the backstack (on UWP). For a wizard you should maybe consider a different solution than just plugging in into the general navigation (e.g a dialog frame with its own navigation)

I'm not too keen to adding this, not sure what the rest thinks about it.

**Comment by dansiegel** [comment]
I'm assuming @cbordeman is referring to a Xamarin Forms app. I can't help but notice people requesting more access to the navigation stack as a recurring theme (#581). It would seem like some enhancements are needed/wanted. If your navigation stack looks something like ```MainPage/ViewA/ViewB/ViewC/Foo```, I think a lot of developers want to be able to utilize that for number of navigation related tasks. 

I can certainly see some potential use cases especially for a ```GoBackAsync( "ViewA" )``` which would let me not care what's between whatever my current View is and ViewA or whatever came before ViewA. All I know/care about is that either I'm going back to the last instance of ViewA or I'm dumping the Navigation Stack and starting over at ViewA as my MainPage. 

If we're adding a ```GoBackAsync( string name )``` then we should also add something like ```NavigateFromAsync( string baseName, string newPath )``` as that could be useful if maybe you don't know/care what's between where you are now, and some other view, but you want to use ViewA as your base to get ```MainPage/ViewA/Foo/Bar```, I recognize that you could just do ```NavigateAsync( "app://MainPage/ViewA/Foo/Bar" )``` but that would involve both knowing and caring that MainPage came before ViewA.

**Comment by cbordeman** [comment]
I would expect the solution to work with Xamarin Forms, WPF, UWP, and any other Prism.

If this is going to be fixed by extending the API I don't like the idea of knowing or caring about the full navigation context.

Dan, I don't understand what `NavigateFromAsync( string baseName, string newPath )` does exactly.  Do you mean `OnNavigatedFrom(string baseName, string newPath)`?

**Comment by brianlagunas** [comment]
I'll start off by reiterating that INavigationService will **never** expose any Page objects.

The first step to recommending improvement to the INavigationService is to identify the best practice for solving these scenarios with normal XF code.  What would you do if you weren't using Prism?

GoBackAsync("Name") will not be easy and I am worried about performance.  Essentially we would have to go into a loop and PopModal/Async depending on what the parent was, until we could find the type that has been assigned the "Name" in the parameter.  Then what happens when we hit a MasterDetail, a TabbedPage, etc.

Right now I am thinking the best approach would be to improve the Absolute URI logic to reuse Pages in the stack instead of replacing them if they are the same.  This way no state will be lost, nothing is recreated, and you can get wherever you want to go.  Even this will be extremely complicated and I'm not sure if I can properly handle all the different Page scenarios.

Also keep in mind the intent of Prism is to provide guidance on how you should be building apps, and not necessarily give you every possible option to do what ever you want.  We try to limit the ability to shoot yourself in the foot.  I am also trying to keep the interface light, as I am hoping to leverage it in UWP too.  Not sure that's going to be possible though since UWP navigation is so different.

**Comment by brianlagunas** [comment]
One thing I think I can do right now is make the GoBack and Navigate methods virtual so it is easier to extend or customize.

Agree?

**Comment by cbordeman** [comment]
What I'm doing now is exactly what you describe, though I'm utilizing NavigationService instead of popping pages directly.  The GoBack(pageName) really isn't necessary since the app could keep track of the # of pages.  GoBack(n) would be sufficient.

**Comment by cbordeman** [comment]
Agreed, Brian.  Is it possible to replace the INavigationService instance globally with a subclass?

**Comment by dansiegel** [comment]
@brianlagunas if there was any confusion, I'm not suggesting exposing the actual Page object. I don't care if someone uses the name "foo" to register "ViewA", in the context of the navigation stack I would care more about the "foo" name than the actual Page object created. 

@cbordeman given the example above ```INavigationService.NavigateFromAsync( "ViewA", "Foo/Bar" )``` would be the context of what I was suggesting. Also Prism has different Navigation Services depending on the underlying platform.

**Comment by brianlagunas** [comment]
@cbordeman there is no global navigation service for XF.  Navigation in XF is dependent on the correct Page instance, so it is impossible to have a global navigation service.  It is possible to replace the Prism implementation with your own, but you'll have to update the ViewModelLocator using this as a guide:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs#L40

Because navigation is page specific, we have to make sure the navigation service instance is aware of the correct page.  I can make this easier by registering the INavigationService with a name that is used internally, and that you can then override with a simple registration instead of having to touch the VML.

**Comment by brianlagunas** [comment]
Okay, I checked-in the ability to more easily override the Navigation service.  First create your own navigation service and derive from the UNityPageNavigationService:
```
    public class MyNavigationService : UnityPageNavigationService
    {
        public MyNavigationService(IUnityContainer container, IApplicationProvider applicationProvider)
            : base (container, applicationProvider)
        {

        }

        public override Task GoBackAsync(NavigationParameters parameters = null, bool? useModalNavigation = default(bool?), bool animated = true)
        {
            //do what you want
            return base.GoBackAsync(parameters, useModalNavigation, animated);
        }
    }
```
Then in your App.cs, override COnfigurContainer and register your service with the container using the correct name:
```
        protected override void ConfigureContainer()
        {
            base.ConfigureContainer();
            Container.RegisterType<INavigationService, MyNavigationService>("UnityPageNavigationService");
        }
```
Now you're off and running

**Comment by cbordeman** [comment]
Very good, this should help with a lot of scenarios.  Thanks Brian.
