### ISSUE TITLE
Official WinForms support

### ISSUE THREAD

**Issue by mika76** [PrismLibrary/Prism#6]
How about adding official WinForms support?

**Comment by brianlagunas** [comment]
Actually, the is a similar library available for WinForms called CAB (Composite UI Application Block).  There is also the Smart Client Software Factory for WinForms.  Unfortunately, Prism will not be supporting WinForms.  The nature of Prism and it's features are tailored around the XAML platform, and do not fit well with the WinForms platform.

Thanks for the suggestion.

**Comment by mika76** [comment]
I know, but both of those project were abandoned by Microsoft years ago.

**Comment by brianlagunas** [comment]
Yeah, the same would have happened to Prism if we didn't take ownership of it.  Unfortunately though, WinForms is not on our roadmap.

**Comment by briannoyes** [comment]
But also because we are an open source project, we would also encourage people to create value-add forks of our code base. Back when we first release Prism 1, we had compositewpfcontrib on codeplex for those kinds of additions, and I was the one who ported the code to support modularity and CompositePresentationEvents for Windows Forms because I was still doing plenty of Windows Forms work then to see the value in doing so.

I'm there are others who would benefit from a current Prism fork making the features that make sense and are possible in Windows Forms available there, but as Brian Lagunas said, we have to draw some bounds for our roadmap based on our team and resources, and I'm afraid Windows Forms is a little too legacy to be on that roadmap.

**Comment by Michael-DST** [comment]
FWIW, I am really glad you guys took ownership of this, and shocked(!) to hear that they were considering abandoning this project.  Also, it does look like Windows Forms is still part of the [.NET roadmap going forward](http://blogs.msdn.com/cfs-file.ashx/__key/communityserver-blogs-components-weblogfiles/00-00-00-81-88-metablogapi/2502.image_5F00_thumb_5F00_4F13C10C.png), surprisingly.  But I am in agreement that it should prioritized as far as Prism goes and best relegated to external forks/contribs.
