### ISSUE TITLE
Application windows are expected to have a root view controller at the end of application launch 

### ISSUE THREAD

**Issue by StanleyBroo** [PrismLibrary/Prism#619]
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

Cant launch ios App

**Comment by brianlagunas** [comment]
Can you please provide more information about this issue? What version of Prism? What version of Xamarin Forms?  How do reproduce the issue?  Do you have a repo app?

**Comment by dansiegel** [comment]
@StanleyBroo I've typically seen this when there is a bug in your projects code. iOS is great at hiding the actual exception thrown. In my experience you have one of the following issues:

1. You forgot to register your View for navigation
2. You forgot to register a type with the DI container
3. You have a Null Reference or other Exception being thrown in your View or ViewModel. Note that the Exception could be thrown due to a custom control or other extension methods you are using in your View.

My recommendation to you at this time would be to try launching it on Android to try to get more information on what the actual exception is that is being thrown. For some reason the actual exception seems to actually surface about 50% of the time on Android and almost never on iOS. PR #613 should help you diagnose this type of issue in the next release.

**Comment by StanleyBroo** [comment]
No worries... simple mistake on my behalf ;O)

Used Stackpanel instead of StackLayout in ContentPage  ....took a while to figure out. No help whatsoever from debugger in "Visual Studio"

**Comment by brianlagunas** [comment]
Sweet! Glad you got it figured out.

**Comment by JeffB1** [comment]
@brianlagunas can the error handling for this be improved a bit? I've unfortunately spent a lot of time being subject to this error today. It's being caused by the page being 'bad' - usually malformed XAML. However, the error about why the page is being 'swallowed' and you get this error. I ended up having to get rid of the Prism navigation and manually set the application MainPage to the page I was working on. At least when it failed, I would get the actual error that occurred and I was able to immediately fix it. Prism wasn't giving me any clues at all :-(

**Comment by dansiegel** [comment]
@JeffB1 how could it be improved for you. The ILoggerFacade was added to the navigation service for 6.2, and will log the exception anytime a View fails to be created.

**Comment by JeffB1** [comment]
@dansiegel if I've got something so wrong with the form that it can't be created, I'd be happy for it just to crash :-) At least the IDE will show me the error. The ILoggerFacade may provide a way for me to intercept the message, even if it's just a place to set a breakpoint for the debugger. I'm only new to Prism. I had my own framework but figured something like Prism would provide more bells and whistles than my own. However, it seems to be a fast moving framework and I'm struggling to find info on various thing, e.g. 

http://stackoverflow.com/questions/40901962/best-place-to-load-data-when-navigating-xamarinforms-prism-6

http://stackoverflow.com/questions/40901883/how-to-navigate-master-of-masterdetailpage-in-xamarin-forms-prism-6
