### ISSUE TITLE
[XF] How to navigate to a NavigationPage

### ISSUE THREAD

**Issue by odedlevy** [PrismLibrary/Prism#64]
When I am required to navigate from within a certain page and want to use Xamarin NavigationPage option to display toolbar items, the initiator of the navigation needs to wrap his content page inside a navigation page.  When trying to navigate using prism (e.g. NavigationService.Navigate(“my_view_name”);) I have no control of the page initiation and cannot wrap the page with a NavigationPage.
I think that Prism should enable to provide a PageProvider when registering the page for navigation using RegisterTypeForNavigation method

**Comment by brianlagunas** [comment]
This is actually a good idea.  How do you envision the API working to enable this feature?  Using an attribute on the View, maybe something like a NavigationPageAttribute?  How about an overload of the NavigationService.Navigate method, something like Navigate("View", useNavigationPage: true)?  Any other ideas?

**Comment by odedlevy** [comment]
Hi Brian,

At first I though the same as what you recommended (Navigate("View",
useNavigationPage: true)) the problem is that there are currently 5
different page options and in the future they may be more.
[image: Inline image 1]

Therefore this lead to the option of defining an IPageNavigationProvider
let looks something like:
public interface IPageNavigationProvider
{
       Page BeforeNavigatePeek(Page pageToBeNavigatedTo);
}

and when defining the RegisterTypeForNavgation there will be an overload
option that will except the
IPageNavigationProvider.
Before navigation prism will call the  BeforeNavigatePeek enabling the user
to return the page wrapped in a NavigationPage or any other option.

The weak spot of this option is that it will require Prism to reference
Xamarin (assuming it is not already familiar with it) so that it will be
able to expose the "Page" object.
If required,  the Page can be replaced with an object. Not ideal but an
option:
public interface IPageNavigationProvider
{
       object BeforeNavigatePeek(object pageToBeNavigatedTo);
}


I must state that the Xamarin design does not feel right. The one that
should decide on the it's layout is the opened page and not
the opening page. In addition it is the opened page that defines the
toolbar items causing the NavigationPage logic to be split between 2 pages
instead of 1. Not the best design.

I'll be glad to hear your opinion.

Regards
Oded.


On Tue, Jun 23, 2015 at 8:36 PM, Brian Lagunas <notifications@github.com>
wrote:

> This is actually a good idea. How do you envision the API working to
> enable this feature? Using an attribute on the View, maybe something like a
> NavigationPageAttribute? How about an overload of the
> NavigationService.Navigate method, something like Navigate("View",
> useNavigationPage: true)? Any other ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-114583092>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
I'm curious if it would be easier to just create a class the derives from NavigationPage and just register that with the navigation framework.

public class MyNavigationPageA : NavigationPage {....}

Container.RegisterTypeForNavigation<MyNavigationPageA>();

Or something like that.  I haven't really thought this through, but it's just an idea that popped in my head.  Whatever the solution, it should not involve having the ViewModel know about a View type.

**Comment by odedlevy** [comment]
I already tried that unfortunately that does not work in Xamarin. You
cannot have a page of type NavigationPage. It compiles but crashes at
runtime. I also tries creating a NavigationPage (in XAML) that contains a
ContentPage but still no luck.

In any case it is not the viewmodel that knows about the type of view,
rather the IPageNavigationProvider which is part of the bootstrapper. It is
something that the application level decides on which feels reasonable to
me.

Note that currently using Prism eliminates the option of having anything
besides a ContentPage which is very limiting.

Can you think of a simple solution to overcome the problem within the
current version of Prism that does not require replacing the entire logic
of Prism's NavigationService?

Thanks

On Wed, Jun 24, 2015 at 7:38 PM, Brian Lagunas <notifications@github.com>
wrote:

> I'm curious if it would be easier to just create a class the derives from
> NavigationPage and just register that with the navigation framework.
>
> public class MyNavigationPageA : NavigationPage {....}
>
> Container.RegisterTypeForNavigation();
>
> Or something like that. I haven't really thought this through, but it's
> just an idea that popped in my head. Whatever the solution, it should not
> involve having the ViewModel know about a View type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-114936417>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
I'll have to think about this one.  Hopefully the community can come together to help solve this one.

**Comment by odedlevy** [comment]
Ok. Great talking with you. Please update if you reach any breakthrough.

Oded.

**Comment by tomcrusader** [comment]
I was just going to ask about this. Developing not only for mobile but full desktop systems will eventually require RegionManager style navigation. But being able to design a shell with NavigationPage is an absolute minimum.

Look forward to any progress with this.

**Comment by joacar** [comment]
One way could be to define the navigation options as enum and then add a factory interface as well as page presenter interface.

Rought sketch

`````c#
public enum class NavigationOptions { Push = 0, Modal = 1, ModalNavigationBar = 2, ... }

public interface IPageNavigationPresenterFactory {
    IPageNavigationPresenter Presenter(NavigationOptions navigationOption);
}

public interface IPageNavigationPresenter {
     Page Present(Page page);
}

public class CustomModalNavigationPagePresenter : IPageNavigationPresenter {
    Page Present(Page page) {
      return new MyCustomNavigationPage(page);
    }

````

For pages used interchangely as modal/pushed depending on the application state new issues will arise when trying to close the page. For example at application startup the MainViewModel launches and in ViewDidAppear we check if settings are valid.

If not the SettingsViewModel is navigated to modally and then login is pressed. When logged in the ClosePage() is called and in here the PopModal need to be called. But if navigated to from e.g a MasterDetailPage scenario then the ClosePage() should just call Pop.

Don't know if it is clear what I mean. If i have time I can implement a sample project to illustrate the issue

**Comment by brianlagunas** [comment]
My first stab at this will use an attribute on the view.  Something like [NavigationOptions(PageType.NavigationPage)].  Expect a PR for review soon.

**Comment by brianlagunas** [comment]
Okay, so after implementing this, I think it may be better to Provide an attribute that accepts an IPageProvider.  So something like [NavigationOptions(PageProviderType=typeof(ViewAPageProvider)].

Then it could be passed the view being navigated to so that properties can be set on it, then it could also return a different page to act as a wrapper/target page like a NavigationPage.

What do you think about that?

**Comment by odedlevy** [comment]
Hi Brian,

I see that you were quick in solving the issue which is great news.

From a design point of view I prefer to avoid attributes, even though your
solution that includes a provider enables the user to place logic when
required. The problem is that the provider will not be created by the
UnityContainer and therefore if the container is required, will need to
receive it using the ServiceLocator which is sometimes not a good solution
(in cases where there is more then one container in use). In addition the
provider may need access to the current state such as who navigated to the
window and such. Replacing the IProvider for testing will also be
problematic.
On the other hand , since I am not familiar with how Prism implemented the
Navigation, though I assume it relies on reflection, therefore the use of
the attribute one of the ways to pass out the logic required for the
navigation.

Regards
Oded.



On Fri, Oct 9, 2015 at 5:18 AM, Brian Lagunas <notifications@github.com>
wrote:

> Okay, so after implementing this, I think it may be better to Provide an
> attribute that accepts an IPageProvider. So something like
> [NavigationOptions(PageProviderType=typeof(ViewAPageProvider)].
>
> Then it could be passed the view being navigated to so that properties can
> be set on it, then it could also return a different page to act as a
> wrapper/target page like a NavigationPage.
>
> What do you think about that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-146738059>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
Actually @odedlevy, the container is used to create the provider.  So you would have no problem injecting dependencies into your provider class.  Prism navigation doesn't use reflection, but the addition of this attribute does require reflection to check for the attribute.  For this reason, we cache the result so we are not incurring the cost everytime.

Is it common to have a reference to the source page when navigating to another taregt page in order to configure properties on the target?  Testing the INavigationPageProvider should not be an issue at all.

Since you are not a fan of the attribute, how would you like to see the API?

**Comment by odedlevy** [comment]
There are 2 options that I can think of:


   1. If we assume that there is only a single page provider for the entire
   app - I would consider to register it on the INavigationService during the
   app bootstrap. (e.g. add a function to INavigfationService such as
   RegisterPageProvider(IPageProvider) or by implementing a default
   IPageProvider and only when user registers a different one on the container
   use his).
   2. A different option in case you prefer multiple providers is to add an
   overload to the INavigationService.Navigate that can accept the
   IPageProvider.

Note that I am not familiar with the solution you implemented and if
actually relies heavily on reflection , yet I assume that these options are
possible.

What do you think?

Oded


On Sun, Oct 11, 2015 at 12:14 AM, Brian Lagunas <notifications@github.com>
wrote:

> Actually @odedlevy <https://github.com/odedlevy>, the container is used
> to create the provider. So you would have no problem injecting dependencies
> into your provider class. Prism navigation doesn't use reflection, but the
> addition of this attribute does require reflection to check for the
> attribute. For this reason, we cache the result so we are not incurring the
> cost everytime.
>
> Is it common to have a reference to the source page when navigating to
> another taregt page in order to configure properties on the target? Testing
> the INavigationPageProvider should not be an issue at all.
>
> Since you are not a fan of the attribute, how would you like to see the
> API?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-147126535>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
We definitely need to consider the need for multiple providers.  I also thought of adding an overload to the INavigationService interface to accept an INavigationPageProvider.  This would remove the need for reflection to check the attribute.  Another benefit to placing it on the navigation service is that you can provide different providers even when navigating to the same type of view.  This is a tough one.

**Comment by tomcrusader** [comment]
So where we at, is there a branch where this can be tested yet?

I don't see any mention of a RegionManager, but as long as we can put content around a navigation page and have Prism target all navigation to that control (sorry, "view"..) then I'm good :)

**Comment by brianlagunas** [comment]
No regions, but there is an approach to wrapping the target page in a navigationPage or other type of page.  See PR #195 for details.  This PR has already been merged.  Now, I am trying to decide if this should remain an attribute, or become something you must provide in the NavgationService.Navigate signature.

**Comment by tomcrusader** [comment]
If it's only possible to use one NavigationPage per app, in reality, then the KISS principle should apply :)

**Comment by brianlagunas** [comment]
Well, you can actually return any type of Page from this interface, such as Master/Detail.  Also, you can have multiple XF.NavigationPages per app.  So I think I am going to remove the attribute and rely on the parameter on the Navigate method.

**Comment by brianlagunas** [comment]
Now I have an issue.  If I do that, now the ViewModel will know about INavigationPageProvider (which relies on the XF.Page type in its members).  Is this a big deal?  I wanted to keep all references of XF.Page out of the ViewModel and any class that the ViewModel needs.

Thoughts?

**Comment by odedlevy** [comment]
My first thought is to replace the 4-5 page options with an enum. I dont
see too many options for additional page types in the future.
An alternative is to  return a .net "object" instead of a page and you can
try to safely downcast it.

**Comment by brianlagunas** [comment]
@odedlevy there is no need for an Enum.  Please see the implementation here:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/INavigationPageProvider.cs

And here:

https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/NavigationPageProviderAttribute.cs

You can see the code snippet here for an example of how it would be implemented with some small changes since this PR is outdated now:

https://github.com/PrismLibrary/Prism/pull/195

**Comment by odedlevy** [comment]
I reviewed the code yet I thought of something a bit different unless I am
missing out on something:

   1. In the bootstrapper we have already mapped our Views to a string
   using the Container.RegisterTypeForNavigation method
   2. At some point we would like to navigate to a new page. Using plain
   old Xamarain we would use the source page to navigate to the target page
   using: sourePage.Navigation.PushAsync(targetPage). And when navigating to a
   NavigationPage we would push a wrapped target inside a NavigationPage
   (e.g. sourePage.Navigation.PushAsync(new NavigationPage(targetPage)).
   3. When using Prism I would expect something different. Since in Prism
   in order to navigate from a viewModel we use the
   NavigationService.Navigate("page name") we would expect prism to enable us
   at this point to supply some kind of means for informing that I currently
   require a NavigationPage wrapper. One way would be to pass an enum
   (e.g.NavigationService.Navigate("page name", PageType.Navigaiton) leaving
   prism the implementation of wrapping the page. ( I am not fund of this
   option yet it is a possibility)
   4. A different option is to use the INavigaitonPageProvider meaning I
   would do something like: NavigationService.Navigate("page
   name",MyNavigationPageProvider). The INavigaitonPageProvider  interface
   should have a method similar to:
      1. Page ProvidePage(Page targetPage) - internally if required the
      user would wrap the target page with any type of page he requires.
   5. This would also give him the flexibility to send a different provider
   per each navigation (assuming this is required)
   6. Note that it is also important to let Prims manage the initiation of
   the Page since when using INavigationAware we can decide if  to create a
   new instance of the page or use an existing one. Using the provider like so
   enables Prims to manage the page lifecycle.

Oded

On Sun, Oct 11, 2015 at 9:56 PM, Brian Lagunas <notifications@github.com>
wrote:

> @odedlevy <https://github.com/odedlevy> there is no need for an Enum.
> Please see the implementation here:
>
>
> https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/INavigationPageProvider.cs
>
> And here:
>
>
> https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Navigation/NavigationPageProviderAttribute.cs
>
> You can see the code snippet here for an example of how it would be
> implemented with some small changes since this PR is outdated now:
>
> #195 <https://github.com/PrismLibrary/Prism/pull/195>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-147235179>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
Yes, the current code accomplishes everything you mentioned except currently to enable it you must attribute the view with the provider you want to use.

The reason I am not in favor of adding a param to the Navigate method is because now you have introduced an interface with knowledge of the XF.Page type into your ViewModel which breaks the MVVM concept.  I wouldn't mind adding the param, but I need to find away to remove this Page type dependency.

**Comment by odedlevy** [comment]
Brian are you referring to passing the INavigaitonPageProvider parameter in
the view model as if we are passing an XF Page type?
I understand the concern but using the attribute on the ViewModel also
exposes the same provider.

I totally agree that it is preferable that the target page and not the
source page decide on the page type, similar to the attribute solution. I
think that Xamarin has not done the best design for the navigation.

The solution I offered continues according to Xamarin design, meaning
enabling the Source to decide on the what type of page to use.Though it id
not thr prefered design it is still more flexible then the attribute option
since the user can decide per each navigation what to provider to use.

Therefore I think that each solution has it's pros and cons so there is no
absolute answer here.

Which path would you prefer?





On Sun, Oct 11, 2015 at 11:43 PM, Brian Lagunas <notifications@github.com>
wrote:

> Yes, the current code accomplishes everything you mentioned except
> currently to enable it you must attribute the view with the provider you
> want to use.
>
> The reason I am not in favor of adding a param to the Navigate method is
> because now you have introduced an interface with knowledge of the XF.Page
> type into your ViewModel which breaks the MVVM concept. I wouldn't mind
> adding the param, but I need to find away to remove this Page type
> dependency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-147243903>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by bartlannoeye** [comment]
Adding an optional parameter to the Navigate method gives most flexibility (different providers per page), if not for the fact that you're bringing information about the View (and a reference to XF.Page) into the ViewModel and that's something I personally want to stay clear of as well. I haven't used XF enough though to make the decision if this flexibility is necessary?

If someone can give an example that this flexibility is required and we can remove the dependency on the view, I'd say go for it (and it is in line with some other .NET functionalities like e.g. adding an IFormatProvider to string.Format()). But for now I would *stick with the attribute*, it's much cleaner than using some enum.

@odedlevy if I'm right according to the code in the PR, the attribute is placed on the view not the viewmodel.

**Comment by brianlagunas** [comment]
No. To clarify, the INavigationPageProvider reference the XF.Page type in its members. This means that when you use it in your VM, you now have reference to the XF.Page type, and now you also open a hole for the VM to inappropriately touch both the source Page and target Page within the VM.  This is not good.

The source still decides where you are navigating.

The attribute goes on the target View, not the ViewModel.  This keeps the View references and responsibilities in the View.

I do agree on the benefit of deciding which provider to use during each navigation action using the param approach.  But, I have to find a way to remove the reference, or exposure, of the XF.Page type on the interface so that I can add the param on the Navigate method.

**Comment by odedlevy** [comment]
Thanks for the clearance on the location of the attribute. That does make a
preferable design.

How about replacing the "Page" with a .Net "object" and that way avoiding
the need to reference XF on the VM?

On Mon, Oct 12, 2015 at 12:10 AM, Brian Lagunas <notifications@github.com>
wrote:

> No. To clarify, the INavigationPageProvider reference the XF.Page type in
> its members. This means that when you use it in your VM, you now have
> reference to the XF.Page type, and now you also open a hole for the VM to
> inappropriately touch both the source Page and target Page within the VM.
> This is not good.
>
> The source still decides where you are navigating.
>
> The attribute goes on the target View, not the ViewModel. This keeps the
> View references and responsibilities in the View.
>
> I do agree on the benefit of deciding which provider to use during each
> navigation action using the param approach. But, I have to find a way to
> remove the reference, or exposure, of the XF.Page type on the interface so
> that I can add the param on the Navigate method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-147246203>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
Yeah, I thought about that too. The problem with that is now you have to do casting from object to XF.Page in both the interface implementation and the Prism code base for consumption.  This not only puts a burden on writing the code, but also the performance hit taken with the boxing an unboxing.

Also this stills leaves the ViewModel open to the inappropriate touching of the source and target pages via the interface.

**Comment by odedlevy** [comment]
Which rolls us back to the attribute option.

A bit limiting but much better then the current options.


On Mon, Oct 12, 2015 at 12:22 AM, Brian Lagunas <notifications@github.com>
wrote:

> Yeah, I thought about that too. The problem with that is now you have to
> do casting from object to XF.Page in both the interface implementation and
> the Prism code base for consumption. This not only puts a burden on writing
> the code, but also the performance hit taken with the boxing an unboxing.
>
> Also this stills leaves the ViewModel open to the inappropriate touching
> of the source and target pages via the interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrismLibrary/Prism/issues/64#issuecomment-147246752>.
>



-- 
*Oded Levy, *Co-Founder and Manager
Razor Grip Solutions
Mobile : 054-5442069
Email : oded@razorgrip.com
Web: www.razorgrip.com

**Comment by brianlagunas** [comment]
So, I just discovered that you can create a class that derives from NavigationPage:

`public class MyNavigationPageA : NavigationPage {....}`

You just have to either pass you default page to through the constructor:
```
public class MyNavigationPageA : NavigationPage
{
    public MyNavigationPageA() : base (new ViewA()) {..}
}
```
, or call navigate.PushAsync in the constructor:
```
public class MyNavigationPageA : NavigationPage
{
    public MyNavigationPageA()
    {
        Navigation.PushAsync(new ViewA());
    }
}
```
So now the question is, should the NavigationPageProvider be removed?

**Comment by tomcrusader** [comment]
Is there now a version of Prism XF with some basic implementation and if yes, how to use it?

**Comment by brianlagunas** [comment]
There is in the current NuGet, but I have removed it in the latest source code check in.  I am re-working the navigation to support deep linking scenarios, and removed it o that I can rethink the solution after the navigation code has been stabilized.

**Comment by JeffDalby** [comment]
Any temporary workarounds while you rethink so we can build pages with toolbars for now?  I've got the 6.01 version which has a CreatePageForNavigation in the INavigationPageProvider , however it wants a (Page sourcePage, Page targetPage) which doesn't match the implementation in PR #195 example. Not sure how to make the conversion between it and:

    public class ViewANavigationPageProvider : INavigationPageProvider
    {
        Page _page = null;

        public void Initialize(Page page)
        {
            _page = page;
            NavigationPage.SetHasNavigationBar(_page, true);
            NavigationPage.SetBackButtonTitle(_page, "Go Back Sucka");
            NavigationPage.SetHasBackButton(_page, true);
        }

        public Page CreateNavigationPage()
        {
            var newPage = new NavigationPage(_page);
            newPage.BarBackgroundColor = Color.Green;
            newPage.BarTextColor = Color.White;
            return newPage;
        }
    }

I'm happy to go back and change things later once it's been decided on a "right" way to do it. Just currently stuck since I've got to build a page that requires a toolbar.

Have patience is a perfectly valid answer to this question. :-)

**Comment by brianlagunas** [comment]
In 6.0.1 you use the INavigationProvider like this:

https://github.com/PrismLibrary/Prism/blob/ba1858a088d6062a054f7deff3c3d7a68aa078b2/Documentation/Xamarin.Forms/3-NavigationService.md#wrapping-the-target-in-a-navigationpage

Like I said in the latest source code this has been removed.  I have checked in deep linking navigation support into the repo.  So if you work from source assemblies for now, you ca do this:

Navigate("ViewA/ViewB/MyNavigationPage/SubPageA/SubPageB");

In this code snippet, ViewA, ViewB, and MyNavigatinPage will automatically be navigated to modally, while the subpages of MyNavigationPage will automatically be navigated to non-modally.  MyNavigationPage is just an empty class that derives from NavigationPage.

Just so you now, you can create a Page that derives from NavigationPage.  You just have to make sure to navigate to a page in the ctor.

**Comment by JeffDalby** [comment]
Thanks for the quick response.  Somehow  missed that documentation in my searches.  I looked into creating a page that derives from NavigationPage, but it broke that code  I had done which was overriding OnInitialize in the bootstrapper so I could call OnNavigatedTo for whatever I returned as mainpage() since the context of the main page comes back as null if you set the mainpage to a derived class (which makes sense given it has no viewmodel)  Of course thinking about it, now I'm not sure that code is needed.  If I derive a page from NavigationPage, and in the constructor use Navigation.PushAsync(MyPage) will OnNavigated to be called?  I would think not, since its not using the NavigationService, but I'm no longer at a machine to test.

**Comment by brianlagunas** [comment]
The MainPage has to be created in code because the Application doesn't have a Navigation proxy.  So you are correct, your MainPage ViewModel will not have INavigationAware invoked since it wasn't navigated to using the NavigationService. What is your use-case to have it fire on the MainPage instantiation?  Could you not use the constructor of the ViewModel instead?

**Comment by JeffDalby** [comment]
Mostly because I learned Prism from the MVA course on Windows 8.1 Universal Apps which showed you can pass stuff to a page via the Navigation Service on startup. 😁

It's a port from Windows where we used app.xaml.cs to read roaming settings  which store things like what they have set the default startup page to, then we pass the primary account name to whatever page they set as the default via the navigation service. Also in the case of Windows we'd pass Cortana's stuff to the page if launched directly from it(her?) Of course we hope eventually as Microsoft expands Cortana to other platforms eventually Xamarin forms will support it, but if that ever happens its a long way off.  


We then have other pages that can also navigate to whatever page was used on startup  but pass it a different user account via the navigation service at which point we use onnavigated to load that accounts' data and set it up based on the info passed to it instead of the primary user.  I could move some of the OnNavigated to stuff to the viewmodel constructor but then I loose the ability to pass a different set of parameters on startup vs when navigated to from another page, and for some pages nearly all the data that is loaded for the page is dependant on the user passed to it.

So I the use case is, now that I've written all that out, is we have pages that depend on a user being passed to them to determine what they show. Users can switch which account is shown on one page and we need to pass it along as they navigate,  and they have the option to set different pages as the startup page (and eventually they'll be able to store which accounts data is shown at startup instead of always starting up to the default account). Most of the code for those pages viewmodel needs to know who's data it is supposed to be loading, and its been easiest to do that by passing it when we navigate to it. Think of it as in the AdventureWorks example being able to say always launch to X products page or to my order history page instead of the main page. You've got to pass the product id so it shows the right stuff.

I think I accidentally beat that horse to death in explaining it too many ways...sorry about that. I shouldn't post from my phone on a Friday night.

From your help on the other issue I opened I'm able to launch to whatever page and get the right viewmodel's OnNavigatedTo on startup..but then one of those potential pages needs a toolbar, which messes the whole thing up since the content page has to be initiated by a navigationpage to work.
Good times.

**Comment by brianlagunas** [comment]
So what this boils down to, is I need to add the ability to navigate using the INavigationService on App start up when the Applicatioon.Current.MainPage is null.  Is this correct?

Let me think about how I can do this.

**Comment by JeffDalby** [comment]
Until Xamrin makes it so you don't have to initialize a content page via a navigation page just to get access to the content page's built in toolbar I'm not sure there is another way.   

Honestly, the more I'm getting into XF the more I'm thinking forget using some of the controls they've built which attempt to function semi-natively. The reality is a Forms app isn't ever going to look very "native" anyway. So I may just go with the competing trend of consistency of brand/design and usage regardless of device.  

Seems much easier to fake the equivalent of the Windows Phone bottom app bar right in the content page, than to deal with the silliness of making an XF toolbar work.  Something I've got to think on.

As always thank you for your dedication to make Prism XF work.

**Comment by tomcrusader** [comment]
So I'm on Prism.Forms 6.0.1 via NuGet now, since that works fine with my current solution - no navigation page. But eventually I would certainly like to use a NavigationPage for example with a Xamarin MasterDetailPage.

It looks to be supported in **Prism.Forms 6.2.0-pre3**. What is yours, Brian, and everyone else's opinion on that? Will that fly as sort-of described in [the link](https://github.com/PrismLibrary/Prism/blob/ba1858a088d6062a054f7deff3c3d7a68aa078b2/Documentation/Xamarin.Forms/3-NavigationService.md#wrapping-the-target-in-a-navigationpage) you provided? :)

**Comment by brianlagunas** [comment]
Yes, navigating to a NavigationPage as the Detail page of a MasterDetail is fully supported in the latest preview.  The INavigationPageProvider has been removed and is no longer needed.

**Comment by ShahriatHossain** [comment]
On my Xamarin android MainActivity class I am using this code to navigate to one of my forms page:

var nav = new NavigationPage(new MyPclFormPage());
now it is redirecting to MyPclFormPage page but I have also snippet of code inside the MyPclFormPage's constructor:
private readonly INavigationService _navigationService;
public MyPclFormPage(INavigationService navigationService)
{
_navigationService = navigationService;
this.NavigateToDetail();
}
private async void NavigateToDetail()
{
await _navigationService.Navigate("DetailPage", null, false);

}

Now it seems that DetailPage constructor is firing but page is not navigating. Can you help me what I have done wrong?
