### ISSUE TITLE
Release Prism for XF 6.2

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#648]
I will be releasing Prism for Xamarin.Forms 6.2 as soon as Xamarin releases their stable version of Xamarin.Forms 2.3.1.

Xamarin fixed 2 major blocking navigation bugs in XF 2.3.1, and Prism cannot be released as stable until the fixes for these bugs have been released as stable.

**Comment by tomcrusader** [comment]
Could you specify those blockers, so we can decide if they prevent us from going into production with Prism using current pre?

One thing we've talked about is back navigation, which in my case could be worked around in the physical Page.

**Comment by dansiegel** [comment]
@tomcrusader it's in the [Milestones](https://github.com/PrismLibrary/Prism/milestones/Prism%20for%20Xamarin%20Forms%206.2)

**Comment by tomcrusader** [comment]
So assuming XF 2.3.1.110-pre1 works in a reasonably stable way, does it consequently fix issues with Prism (in my case master/detail hamburger menu disappearing on iOS)?

https://forums.xamarin.com/discussion/70166/xamarin-forms-2-3-1-pre1#latest

**Comment by brianlagunas** [comment]
yes

**Comment by tomcrusader** [comment]
Hi Brian

When you're back from vacation, please clear the versioning up?
We're talking about 6.2.0 and Prism.Forms, right? Since that's the Xamarin.Forms package.

But the pre's for Prism.Forms are **6.1.0**, while Prism.Unity and Prism.Core are **6.2.0**?
Just wondering what's up with that :)
https://www.nuget.org/packages/Prism.Forms/6.1.0-pre7

**Comment by bartlannoeye** [comment]
@tomcrusader different packages/platforms have different versions. It's never been our intention to have all package versions in sync, because this would require version bumps on some packages without changes.

Since the pre's for Prism.Forms are 6.1.0-preXX, I expect Prism.Forms to be released as 6.1.0 indeed (so the title of the issue/milestone is incorrect imho).

**Comment by tomcrusader** [comment]
So how are we looking guys? Does 2.3.1 "stable" work?
http://forums.xamarin.com/discussion/70166/xamarin-forms-2-3-1-stable/p1

**Comment by brianlagunas** [comment]
I'm in Sydney the rest of the week. I'll be releasing a new stable build next week :)

**Comment by brianlagunas** [comment]
Just a quick update.  I am going to get some small updates in and then I plan on releasing 6.2 as stable end of this week (week of Aug 8).

**Comment by brianlagunas** [comment]
It has been done!  Available on NuGet now
