### ISSUE TITLE
[XF] Remove NavigateAsync<TViewModel> or keep it?

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#673]
I need your help.

I am considering removing support for navigating to a ViewModel using `INavigationService.NavigateAsync<TViewModel>()`.  We are making changes to how registration works and in order to continue to support this, we would need to add new extension methods that would be used specifically for navigating using ViewModels.

I was thinking of calling the method `Conatiner.RegisterTypeForViewModelNavigation<TView, TViewModel>()`.  Only then would `NavigateAsync<TViewModel>` work.

So should we keep it and add the new extension methods to support it, or remove it completely?

If we do keep it, should we remove the method `NavigateAsync<TViewModel>`  signature off of the INavigationService interface and just make it an extension method too?

**Comment by dansiegel** [comment]
Well I think you know my opinion. Navigating to ViewModel's is just a bad practice. I'd rather see someone have to jump through hoops to do things poorly than to encourage it.

**Comment by brianlagunas** [comment]
I completely agree with you, and I even tell people not to do that.  Especially when you start getting into modules and navigating between them.  I think Prism can be opinionated in this.  I can provide a sample on how to write the extension methods so devs that want to can, but they have to purposely opt-in

**Comment by kdawg1406** [comment]
Umm...  Why remove this from the API?  What's the motivation and benefit?

Are these developers using this pattern?

**Comment by brianlagunas** [comment]
@kdawg1406 the motivation is two fold. One is to keep the current navigation consistent and to eliminate any confusion between how `NavigateAsync("VIewName")` and `NavigateAsync<TViewModel>()` works in combination with the registration methods `RegisterTypeForNavigation<TView>("ViewName")` and `RegisterTypeForNavigation<TView, TViewModel>`.  This has been a source of confusion a number of times.

The other is that this coupling is discouraged and this type of navigation is not present in any other Prism platform (back to consistency).

`NavigateAsync<TViewModel>` was added early on before the code base really matured, and now it is becoming clear that it should not be there.

**Comment by dvorn** [comment]
@brianlagunas In Prism.WPF there is a "View Model-first" approach to navigation.  It does not use view model locator.  I used it to great benefit in testing.  Will there be something analogous on other platforms? (I new very little about other platforms, just curious.)

**Comment by brianlagunas** [comment]
@dvorn yes, and no.  There was nothing specific in Prism tat allowed you to navigate to a ViewModel similar to `NavigateAsync<TViewModel>`, but Prism for WPF is so flexible you essentially registered your VM with a name, and then gave it a key.  But you still had to navigate via the key.

**Comment by kdawg1406** [comment]
I recommend pinging the XAML Disciples Google Group.  I think there is a ViewModel first camp out there.

Would this change break the ViewModel first developers?

**Comment by scionwest** [comment]
Why is this even a question? This contract exists on an interface, it shouldn't be removed. I'm sorry, but this is exactly the reason why I have not used Prism since you guys took over. Not to sound harsh, but you break contracts with little regard to the impact this has on people using it. The small amount of time I spent following this project I had my code break out from under me with updates that didn't even increment the major version number. 

An interface provides me a contract and I don't expect it to change. There are some who believe it shouldn't change even with a major version number change, but I'm not sure I agree with that. In this case however, I only see two options. Leave it, or increment to a new major version and break the contract. Otherwise leave it.

**Comment by brianlagunas** [comment]
@kdawg1406 There is no real ViewModel first in Xamarin.Forms.  Essentially you are only using the ViewModel.GetType().FullName as the navigation key, but you are always navigating via a Page

**Comment by scionwest** [comment]
As an aside to my previous post, I'd also like to ask why is it bad to have view model first navigation? MVVM is all about view models knowing of each other, but not knowing anything about the view. It's a very one-way relationship. Using magic strings that use convention to lookup a View is gross. You shouldn't be leaking your views into your view models in MVVM

**Comment by brianlagunas** [comment]
@scionwest Prism for Xamarin.Forms is brand new, and there has only been one stable release.  It would be naïve to think we got it right on the first try.

> I'm sorry, but this is exactly the reason why I have not used Prism since you guys took over. Not to sound harsh, but you break contracts with little regard to the impact this has on people using it.

What contracts have been broken since we took this over?  All updates have been released as a preview, and nothing has been a breaking change yet (when we RTM there will be).  I think this statement is way out of bounds and is quite insulting especially considering that you have never been involved in any of the internal discussions regarding making a breaking change.  You do not know how much time and effort we put into this project and into preventing breaking changes.  In the case of Prism for Xamarin.Forms, breaking changes from the first stable release were required in order to have a viable framework, because we didn't get it right the first time.

> The small amount of time I spent following this project I had my code break out from under me with updates that didn't even increment the major version number. 

There have only been updates on the preview channel.  If you are using these, you must expect an unstable code base.  If you wait until the RTM, you will only have to fix the breaks, which will be documented, once.  This is an evolving code base, but it is stabilizing quickly.

> As an aside to my previous post, I'd also like to ask why is it bad to have view model first navigation? MVVM is all about view models knowing of each other, but not knowing anything about the view. It's a very one-way relationship. Using magic strings that use convention to lookup a View is gross. You shouldn't be leaking your views into your view models in MVVM

It's bad because you are creating a tight coupling to other classes (ViewModels).  Your VMs must know about other VMs.  This is not good in my book.  Especially in more loosely coupled apps in which you are navigating within a module that has no reference to another module in which the target view exists.  There is absolutely ZERO view leakage using strings.  That's the entire point of it.  If you don't want to use the View name by default, then you supply your own that represents the business case and can even use constants so you're not so grossed out.

None the less, you do not have to use Prism.  That is your choice.  But if you want to actually contribute, you can make your case for the topic at hand and not blast the team for past decisions that are trying to improve the framework.

**Comment by scionwest** [comment]
> It would be naïve to think we got it right on the first try.

Sigh - If you can't take a little bit of criticism without becoming insulted then I'm sorry. This is software development in the open. Some of it should be expected. In _no_ place in my post did I question you and the teams intelligence or ability to do your job. I simply expressed a frustration with introducing a breaking change. I even said "sorry to be harsh". If being frustrated about a change makes me naive, then so be it.

> I think this statement is way out of bounds and is quite insulting especially considering that you have never been involved in any of the internal discussions regarding making a breaking change.

Nope, I don't work with you guys so I guess I wouldn't be privy to those internal conversations. Not exactly my fault when they're, you know, internal. You blasted this out on twitter for feedback, where not many people are privy to those internal conversations, so I'm simply providing that feedback.

> You do not know how much time and effort we put into this project and into preventing breaking changes

Which is appreciated. As a maintainer of an open source project, I understand this. You can't let your devotion to your project and love of the product blind you from potential issues or valid complaints from the customers who use it. We all love the OSS projects we work on, more often than not that's why they're OSS in the first place. You've also got people who use your projects (regardless if it's XF or WPF) in their projects and don't care how much you, or I, love our OSS projects and how many hundreds of hours of our free time is sunk in to them. All they care is that you broke their enterprise or commercial product and they now must spend money to fix it. I know you are aware of this, considering you work for a company that has a huge customer base :)

> There have only been updates on the preview channel. If you are using these, you must expect an unstable code base. If you wait until the RTM, you will only have to fix the breaks, which will be documented, once. 

Alright, this is where I fall on my sword a bit. So yes, there have been breaking changes in the past with the WPF specific stuff. More specifically moving from 6.0.0 to 6.1. I didn't realize until you're response that this was Xamarin specific. I saw XF, but didn't know what it stood for. This repository is /PrismLibrary/Prism, so the assumption was this change was going to made across all platforms. I totally agree with pre-release/beta/preview stuff being allowed to make breaking changes all day long. That's the point. I dealt with it for months w/ .NET Core and didnt complain, because I understood what I was getting into.

> It's bad because you are creating a tight coupling to other classes (ViewModels).

Tight coupling is perfectly fine in the same domain layer. Not every application uses modules, at least in WPF, and forcing everyone to magic strings when there already exists tight coupling within the domain is just meh to me. I don't know how XF is setup since I've not used it.

> If you don't want to use the View name by default, then you supply your own that represents the business case and can even use constants so you're not so grossed out.

Fair enough.

> But if you want to actually contribute, you can make your case for the topic at hand and not blast the team

Again, some advice. learn to take a bit of criticism. I even said "Not to sound harsh" in an attempt to say, "i don't mean for this to sound mean, it's just frustrating". and saying i don't use it because you've broken things in the past, (with no cussing even or name calling even!) is hardly blasting your entire team with insults.

- Naive developer.

**Comment by brianlagunas** [comment]
@kdawg1406 to your point, the concept of navigating via ViewModels is very common, and to keep support for it would only require the addition of 3 new extension methods for registering the Views/VM's for ViewModel based navigation.  Essentially 6 lines of code, so it's not a big deal to keep it.  The only requirement would be a retraining on the registration for this type of navigation.

So instead of using the standard
`Container.RegsiterTypeForNavigation<TVIew, TViewModel>()`
You would use
`Container.RegisterTypeForViewMOdelNavigation<TView, TViewModel>()`

Maybe that's not a big deal.

**Comment by kdawg1406** [comment]
API looks clean, discoverable, and lets developers author their applications they way they want.

Win-win.

**Comment by scionwest** [comment]
I like that the method is more discrete. Much clearer that its intent is for navigation view view models.

**Comment by brianlagunas** [comment]
@scionwest When you start a sentence with "I don't mean to be [insert term here]", it doesn't give you an excuse to be what you said you didn't mean to be.  

> Again, some advice. learn to take a bit of criticism.
Fair enough. I'm a little cranky tonight.  So I may have been a little harsh in my reply. I apologize for that.

A little advice to you, make sure you fully understand the issue being discussed before expressing your very strong opinion :)

None the less, I am still waiting for community feedback.  I am not opposed to keeping it, I just want to make sure this is something that will provide value and that we can keep in the code base without introducing confusion with our current navigation concepts.

**Comment by dansiegel** [comment]
To be fair here I would say if people are really using it currently, then the appropriate thing to do is to make the extensions obsolete and remove them in a later release.

**Comment by brianlagunas** [comment]
@dansiegel well, the problem with that is we are fixing #666 to behave as expected and eliminate the current navigation registration confusion, which essentially breaks the current `NavigatAsync<TviewModel>`. 

So we can keep it, but if we do we need to provide new extension methods that allow it to be used.  Otherwise, it will be useless and unusable in its current state.

**Comment by TaviTruman** [comment]
@brianlagunas we do a lot of multiple-shell work in prism and use have tabs linked via messaging and Eventing. I never navigate to a ViewModel - that just seems wrong and laden with all kinds of badness. So I have no need for it as PRISM has a long and valued legacy in providing solid guidance; I would not like to see the API adjusted to support Navigation to a ViewModel. I do think it time to consider Design Patterns and Idioms like Reactive Extensions' Hot Observables combined with the Repository Pattern.

**Comment by dansiegel** [comment]
@brianlagunas like I said before I don't care for it and am all for it being removed... I think I've been fairly outspoken on my dislike of the pattern in general. It doesn't seem to have much traction for usage, but if it did then making it obsolete would be the way to go. Of course nothing says obsolete like it doesn't work right 😉

**Comment by brianlagunas** [comment]
Here are two limitations of ViewModel based Navigation:

- No support for navigating to views in unreferenced modules
- No support for deep linking.

These are two more reasons in favor of removing the ability to navigate via ViewModels.

One option would be to remove the `NavigateAsync<TVIewModel>` from the API and provide a GIST of the extension methods that a developer could add to their project if they wanted t support it.

https://gist.github.com/brianlagunas/40b8a7d1e25ccc64623b19f11d758171

**Comment by dvorn** [comment]
I have a fairly successful Prism.WPF application which utilizes viewmodel-first approach.  I think some day I will need to port it to UWP and/or Xamarin.

Remember, MVVM is about testing decoupled view models.  In my application I am able to do _acceptance tests_ using view model without actual views (some mock views are provided, though).  No viewmodel locator, but datatemplates in the views.  The tests cover complete user scenarios: from program start to program termination.

What are my options with new Prism on UWP and Xamarin?

I do not care about a particular form of NavigateAsync with templated view model, in WPF I used strings anyway.  But seemingly the solution for navigation with view models just boils down to viewmodel locator which requires views anyway.

**Comment by brianlagunas** [comment]
@dvorn Although your question is off topic, there is no ViewModel first navigation in Xamarin.Forms.  It's not possible. Navigation is Page based.  Doesn't matter though, because you still navigate with strings/uri in Prism for XF so nothing changes conceptually wise.

**Comment by Troto** [comment]
@brianlagunas I'm in favor of the change because it would be much clearer that it's not the preferred way of navigating. I started using view model navigation just to make refactoring easier but ended up wasting heaps of time trying to figure out how to do exactly the limitations you listed above. It wasn't clear they weren't available with view model navigation.

**Comment by brianlagunas** [comment]
Thanks for all the feedback. I have decided to remove it, but I will provide a GIST of the extension methods a developer could use in their app in order to add this capability as an opt-in feature.
