### ISSUE TITLE
[XF] potential GoBackAsync issue

### ISSUE THREAD

**Issue by powerdude** [PrismLibrary/Prism#677]
I've been playing around with and studying the code and I ran into a little problem.  I'll post another issue on what i'm trying to do, but i've noticed that GoBackAsync does something that I think should be different, but wanted to talk about it here.  In this code:

```
               Page previousPage = GetOnNavigatedToTarget(page, useModalForDoPop);

                OnNavigatedFrom(page, segmentParameters);

               var poppedPage = await DoPop(page.Navigation, useModalForDoPop, animated);
```
I think DoPop should be called with `previousPage.Navigation` instead of `page.Navigation`.  It is the previous page's navigation where the current page was pushed normally or modally and the code should be checking against that instead of the current page.  It's possible you'd get the same NavigationProxy from the current page, but i ran into a case where i didn't and then i get an error that the modal stack was empty.  Basically, was doing the following:

```
NavigateAsync("masterdetail\mynav\mypage");
NavigateAsync("mypage2")
NavigateAsync("mypage3", true)
GoBackAsync()
```

Also, wouldn't it also make sense to update the _page variable here so that the service is still aware of what the current page is now?

**Comment by brianlagunas** [comment]
If you call Pop from the previous page, you will not get the behavior your are expecting.  Navigation always has to happen relative to the current page.  The reason you get an error about the modal stack being empty is because Xamarin treats the MainPage separately from the Model stack.  So you may have two pages (MainPage and a PopModalAsync). When you call Pop your modal stack is now empty even though you still have a MainPage.  This has been fixed in the latest Prism code base, but the NuGet hasn't been updated yet.
