### ISSUE TITLE
Tag Milestones

### ISSUE THREAD

**Issue by toadzky** [PrismLibrary/Prism#691]
If you are going to release preview builds into nuget, you should probably be tagging them in git so that if I need to debug an issue, I can checkout the tag and see the code as it was built. Right now, I have no visibility into what state `pre7` was when it went to nuget. That makes debugging specific things VERY hard because I'm never sure whether the code I'm looking at matches the compiled binaries.

**Comment by dansiegel** [comment]
To be fair here you could probably get the information you're looking for by blaming the file in question. That said there is a v6.2-Preview branch which I believe @brianlagunas updates just before releasing the latest preview.

**Comment by toadzky** [comment]
i'm not looking for blame, i'm looking to step through to figure out why behavior isn't what i expect. blame doesn't help there. and if the milestones aren't tagged, how would blame tell me which commit matches the build i'm depending on?

also, that branch is like 50 commits behind master.

**Comment by dansiegel** [comment]
@toadzky Git Blame is not about Blaming and Shaming. It helps to give you the history of particular blocks of code within a specified file. If you have a block of code that you are questioning you can always blame it to see if it has been changed before or after the current Preview Release.

That said the v6.2-Preview branch is largely behind master because of the PRs that have been pulled into master since pre7 was released including the addition of Autofac support for Xamarin Forms.

**Comment by brianlagunas** [comment]
Yeah, that's probably a good idea.  I never thought of it.  I was just trying to get the packages out the door as quickly as possible.  For the next releases I'll be sure to tag them.  Thanks for the suggestion.
