### ISSUE TITLE
[XF] Bring Async to INavigationAware

### ISSUE THREAD

**Issue by sschutten** [PrismLibrary/Prism#704]
Currently I like to use OnNavigatedTo to initialize my view models asynchronously since most of the time I need to read something from disk, a database or a web service. Since OnNavigatedFrom and OnNavigatedTo are void it's not a pleasant process and creating an async void is [bad code](http://haacked.com/archive/2014/11/11/async-void-methods/).

It would be great if an async version of INavigationAware is introduced, similarly to the IConfirmNavigationRequestAsync interface.

**Comment by dvorn** [comment]
The issue is deeper than just "bad code".  During navigation, the systems _informs_ the current view that it is navigating from it by the call to OnNavigatedFrom, then creates a new view, activates it, and informs it that it was activated by the call to OnNavigatedTo.

Now, if those methods were asynchronous, what the system is supposed to do: will it wait for the methods to complete or not?

If the system waits for the methods to complete, then what the UI will look like during the execution of OnNavigatedFrom and the user is supposed to do during this time?  The navigation started, the old view is supposed to be non-functional, but the new view, the target of the navigation, has not been created and activated yet.  The same with the new target view during the execution of OnNavigatedTo.

If the system just starts those asynchronous methods and does not wait for their completion, then it is no different from implementing those methods as "async void".  This is the same "fire and forget".

Thus, actually you need to have a proper design of your views and navigation between them.  E.g., the old view may implement IConfirmNavigationRequestAsync (for which the system will wait) and during the execution of CanNavigateAsync display a window asking the user to wait while the data is being saved.  Something similar with the target view: have it displaying some "Please wait..." message until the data was properly initialized.

**Comment by dvorn** [comment]
See http://stackoverflow.com/questions/38040922/use-asynchonous-tasks-with-inavigationaware-with-prism but you will also need to catch possible exception from "await".

**Comment by sschutten** [comment]
Good points and thanks for the elaborate explanation. I haven't looked at it that way. Then I guess the best way is to use an async void in combination with proper exception handling.

**Comment by DavidStrickland0** [comment]
> If the system waits for the methods to complete, then what the UI will look like during the execution of OnNavigatedFrom and what the user is supposed to do during this time?

The methods are currently synch... they wait and pause navigation by default out of the box. Stating they shouldnt be Asynch because they would then pause the navigation doesnt make sense. If they returned a task then the developer would have options how they want to implement and the methods would be able to play well with the rest of the rest of the Async stack by default. 



> you need to have a proper design of your views and navigation between them. E.g., the old view may implement IConfirmNavigationRequestAsync

Im sorry stating that your old View\ViewModel should have deepknowledge of the new View\ViewModel and in fact thus every "old" View\ViewModel that wants to navigate to that page must likewise have deep knowledge on the new View\ViewModel sounds a lot like spegetti code not "proper design" The only ViewModel That should be deciding if the LoginPage should show or not is the LoginPageViewModel not every page throughout the app that might have the login link on it.

**Comment by brianlagunas** [comment]
That's why you should use async methods that don't block UI or navigation execution.

**Comment by DavidStrickland0** [comment]
> That's why you should use async methods that don't block UI or navigation execution.

Where do I block the popping of the login page and use cached credentials instead? I dont want the login page to show.

**Comment by brianlagunas** [comment]
IConfirmatNavigationAsync

**Comment by DavidStrickland0** [comment]
So every page in the entire app that might want to navigate to a given page has to implement IConfirmNavigationAsync  and decide what to do with the NextViewModel they might want to navigate to? So the parent has to have deep knowledge of every child and a change in the functionality of the child thus may require me to tough every parent? 

Secondly how does one handle exceptions in non blocking Async void methods theres no way to catch the exception short of the App wide exception handler because its fired and forgotten.

**Comment by brianlagunas** [comment]
No, you asked about popping a page, which you would use the ICOnfirmNaviagtionAsync method. Now you are talking about a different scenario.

You handle exceptions just like you would handle any other non-blocking async operation. Nothing changes.

**Comment by DenisZhukovski** [comment]
Sorry guys but I want to add my 2 penny here. You've created a great navigation service but I got into a situation that I can't solve. 
The problem is:
In our application we want to let viewmodel to initialize itself. But we don't want to be redirected to the page before the initialization complete and if some exception occurs we want to notify parent viewmodel about it. In other words we don't want to have some user experience when user can get to a page with viewmodel error state. Maybe you have some thoughts about the solution. Thanks.

**Comment by DavidStrickland0** [comment]
> You handle exceptions just like you would handle any other non-blocking async operation. Nothing changes.

You can't catch async void OnNavigatingTo. It's fired and forgotten. I could catch it just like i catch any other non-blocking async operation IF it was like any other nonblocking async operation and returned a task.

**Comment by DavidStrickland0** [comment]
> you asked about popping a page, which you would use the ICOnfirmNaviagtionAsync method

So every page in the entire app that might want to navigate to a given page has to implement IConfirmNavigationAsync and decide what to do with the NextViewModel they might want to navigate to? 
Take for example a Shopping cart with a link to the loginpage. If the user has thier info locally cached I dont want to show the login page otherwise I do. Per your example shoppingcart now needs to know to check if the user credentials are cached in the ICOnfirmNaviagtionAsync method. Later we add to the flow and now It also needs to make sure in the ICOnfirmNaviagtionAsync method that if the Login Details are cached and the Credit Card Details aren't cached then I need to go to the creditcard details page instead of the login page  and all this logic needs to be in the IConfirmNaviagtionAsync of the shopping cart page. 
ConfirmNavigation makes perfect sense when its concerned with whether the ViewModel has all the info it needs to leave the page. But using it to determine if the next page can load, getting data for the next page or anything else that requires pre-knowledge by the parent of the construction of the child I would see as a step to far.

**Comment by brianlagunas** [comment]
First off, you can't make a navigation decision in OnNavigatingTo. The page is not part of the NavigationStack so if you tried to navigate from there is would fail. Second, XF itself does not provide an async version of its OnAppearing/Disappearing either.  So how would you do this in a non-Prism app using only the XF APIs that are not Task based?  There is also the issue of the INavAware interfaces being called in more places than just navigating forward with a button click. There are many scenarios this interface is called where any async version would/could not be invoked causing a ton of confusion, duplication of code and a different set of threading problems.

The approach you described is actually a good approach. You must know your navigation path before navigating. The fact that you want to navigation to a page, create it, render it, and then decide if they should be immediately navigated to another page is a performance overhead I wouldn't want in my app.

As with most OSS projects, you are more than welcome to customize prism to fit your needs.

**Comment by brianlagunas** [comment]
I think this may help some people: https://johnthiriet.com/removing-async-void/

**Comment by DavidStrickland0** [comment]
> The fact that you want to navigation to a page, create it, render it, and then decide if they should be immediately navigated to another page is a performance overhead I wouldn't want in my app.

I think were missing an important piece of communication here. Async void OnNavigatingTo promotes exactly this antipattern and this is precisely why I've been saying it should never be used. Its **Async void** there is nothing awaiting it. Whatever is happening in the method that causes it to be async. The page will likely be created, loaded on the stack and rendered before ONavigatingTo finishes, you might as well have just put the logic (whatever it is) in OnNavigatedTo it will have the same effect and be more predicatable about when the code will be complete. 

The only predictable implementation of OnNavigatingTo is a Blocking implementation. Either Sync or async awaited. With Async Awaited you can free up the TPL to go do something else why you wait. If theres an Exception the NavigationService is informed BEFORE the page loads and the navigation stops.


> First off, you can't make a navigation decision in OnNavigatingTo. 
The 7.1 Implementation of the NavigationService added the ability to return Exceptions from Navigation. Throwing an UnAuthorizedException is a pretty clear navigation decision. 

> You must know your navigation path before navigating.
Granted but the path is all you should know. Not the nitty gritty of how the child page loads it data or validates its contents. 

> By the way, in your sample you were not handling any exceptions, only throwing them.
https://github.com/DavidStrickland0/ONavigatingTo/blob/master/PrismNavigationDemo/PrismNavigationDemo/ViewModels/MainPageViewModel.cs

        private async Task NavigateToExistingFailedPage()
        {
            try
            {
                await NavigationService.NavigateAsync("ExistingFailedPage");
            }
            catch (Exception e)
            {
                NavigateToPageCommandResult = e.Message;
            }
        }
Exception Handler never gets hit OnNavigatingTo is Async Void.

> As with most OSS projects, you are more than welcome to customize prism to fit your needs.
Looked into it Unfortunately DoNavigation is a static so its basically going to take rewrite of the entire Navigation Stack.

**Comment by brianlagunas** [comment]
Your advice not to use OnNavigatingTo is ill-advised. It may not work for your scenario, but it does work for many other apps that are in production today.

Add the try catch around your code in the async void method.

I can make DoNavigation extensible.  For now, you can just copy/paste the navigation service into your app to modify it.

**Comment by DavidStrickland0** [comment]
Using async void never works the way they'll expect it to. If they are doing anything short of logging that navigation is about to occur (and likely getting that log entry afterwards) it will bite them eventually with weird errors and race conditions that only crop up on certain devices under certain conditions etc.

Adding a try catch in the async void method wont do anything useful. Theres no way to marshell it back to the UI thread no way to inform the user the error occurred or alter the application flow short of doing it up in the Application Unhandled Exception Hook all the way at the top.

> I can make DoNavigation extensible. For now, you can just copy/paste the navigation service into your app to modify it. 

Thanks appreciate that. I think that is the plan for now not sure if were going to offer it back up to the community or not unfortunately the politics around getting an OSS offering approved is likely more work than the code.

Brian: Thanks for the time and thanks for keeping Prism going and responding to issues as quick as you do.

**Comment by DavidStrickland0** [comment]
Looks like a coworker got time to put a solution together. Its working for our needs and thought Id throw it up in case anyone else feels the urge. https://github.com/Pavel-Sulimau/Prism.Xamarin.AsyncNavigation/

**Comment by brianlagunas** [comment]
If you use the preview, you don't have to duplicate all that code. You can just derive from PageNavigationService and override the methods like DoNavigateAction. It will eliminate a ton of code.

**Comment by DavidStrickland0** [comment]
Unfortunately we have several apps live and getting sign off atm to use preview code in production is an uphill battle we do look forward to the release so we can do just that. Thanks for the heads up.
