### ISSUE TITLE
VMs do not raise navigation methods when used in CarouselView

### ISSUE THREAD

**Issue by adrianknight89** [PrismLibrary/Prism#749]
I'm testing out the new XF CarouselView. I wanted to display a content page as a carousel item; however, view models do not raise navigation events.

VM property:

`public ObservableCollection<Page> Pages { get; set; }`

In VM constructor:

```
Pages = new ObservableCollection<Page>
{
    new Page1 {Title = "Title1"},
    new Page2 {Title = "Title2"},
    new Page3 {Title = "Title3"},
    new Page4 {Title = "Title4"},
    new Page5 {Title = "Title5"}
};
```

Navigation events are called on the carousel VM but not in each individual page VM. Is this expected behavior or can we improve upon this?

**Comment by joacar** [comment]
If I remember correctly the CarouselView is available as separate NuGet and not part of Xamarin.Forms.  Check #650 where I think the CarouselView is discussed.

**Comment by brianlagunas** [comment]
A CarouselView is not a Page, but rather a control on a Page and therefore will not receive navigation events.

**Comment by dansiegel** [comment]
@adrianknight89 As mentioned CarouselView is part of a [separate package](https://www.nuget.org/packages/Xamarin.Forms.CarouselView/) so even if it made sense to do something it couldn't be supported in any of the existing packages without creating a new dependency that most people aren't using, and it would have require Prism to be in preview since the CarouselView package is only a preview currently. 

I'm not going to try to get into good design vs bad design debates here, but note that because the CarouselView is a child element on a page, the CarouselView's children would be sharing the same BindingContext (ViewModel). Assuming you take care of any necessary design issues here, you can accomplish what you're looking for by implementing a behavior for the CarouselView similar to PR #712. Note that all of the events that you would need are specifically tied to the [CarouselView](https://github.com/xamarin/Xamarin.Forms.CarouselView/blob/master/txt/src/carouselView/dev/Shared/CarouselView.cs) and not the [ItemsView](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ItemsView.cs) that it derives from so you would have to implement the behavior for the CarouselView specifically.
