### ISSUE TITLE
[XF] NavigationService Extensibility

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#754]
The Navigation Service should be updated to provide for more extensibility.

1) private methods should at least be made protected so that should someone choose to implement a customized navigation service they can utilize the existing functions that the PageNavigationService uses.
2) ```Page CreatePageFromSegment( string segment )``` should be added to the INavigationService interface. This would make it easier to implement extension methods for the INavigationService for instance if you were looking to use a 3rd party library like Rg.Plugins.Popup

**Comment by brianlagunas** [comment]
I'm comfortable making those methods protected virtual.  However, I will not be adding CreatePageFromSegment to the INavigationService as this will expose a Papge object via ViewModels, and it will clutter the API with a method that has nothing to do with the public API related to navigation.  We could possibly create a new INavigationServiceImpl interface with those types of things, but I'm not sure if that would help you or not, because I'm not sure I would have INavigationService implement INavigationServiceImpl or not.

**Comment by dansiegel** [comment]
I was hoping to make the INavigationService extensible for odd ball scenarios like I mentioned. But at the same time I can understand your point why you wouldn't want a Page object being exposed to a ViewModel. I suppose if ```CreatePageFromSegment( ... )``` was made protected you could create a custom Navigation Service that implements another interface while still maintaining the ability to easily create a page without having to rewriting that code.

**Comment by brianlagunas** [comment]
Were you going to prep a PR for your suggested protected modifier changes?

**Comment by dansiegel** [comment]
Yeah I'll try to get that in today

**Comment by brianlagunas** [comment]
Fixed with #766

**Comment by SeeD-Seifer** [comment]
I would love to use this improvement in my current project. When is it expected to make a new NuGet release?

**Comment by brianlagunas** [comment]
No until the behvaior stuff is nailed down
