### ISSUE TITLE
ObservesProperty Suggession

### ISSUE THREAD

**Issue by noufionline** [PrismLibrary/Prism#760]
Hi Brian,

Is it possible to extend ObservesProperty to execute RaiseCanExecuteChanged() even when a property changes inside the payload?

Example:

` UpdateCommand = new DelegateCommand(Update, CanUpdate).ObservesProperty(() => Entity);`

Now with the current scenario RaiseCanExecuteChanged() is executed every time Entity  is set.
But my point is If Entity itself if implementing INotifyPropertyChanged then any property change inside the Entity should also raise RaiseCanExecuteChanged().

Is this possible to achieve?

Best Regards,

Noufal

**Comment by joacar** [comment]
Hi,

Off course it is possible, but I guess that the current solution prevents that for some reason. One reason might be that a potentially long-lived object is sent to the constructor of a view model and then in `ObserversProperty` a reference to that object might cause the view model not to be garbage collected. This can, however, be fixed by using `WeakReference` or/and a proxy class mainting a weak reference to the entity to observer as well as the view model.

If you have resharper installed it is fairly easy (think it is Alt+Insert when on the instance field of `Entity`) to generate delegeting members for in your view model and then observe those properties.

That might also be the approached recommended and why they didn't implement `ObservesProperty` for classes.

@brianlagunas will tell you have it really is :)

**Comment by briannoyes** [comment]
@noufionline I think what you are asking for is to allow ObservesProperty to be pointed at a whole object, not just an individual property on that object as the trigger for checking CanExecute?

I don't think it was anything intentional in leaving it out. @brianlagunas will have to respond on that one. 

In terms of the memory leak concern @joacar - I don't think there would be a problem there since the command would normally be scoped to the ViewModel, and if the ViewModel can be GC'd so can the command and what it points to. Plus monitoring the object as a whole would involve the same reference that watching a specific property does.

We'll look into maybe adding this.

**Comment by joacar** [comment]
@briannoyes I thought that it would create a reference loop.

Small example
``
// Long lived object
public class Settings : INotifyPropertyChanged
{
     public static Settings Current {get; private set;}
}

public class ViewModel
{
    public ViewModel()
    {
        MyCommand = new DelegateCommand(...)
                    .Observe(Settings.Current) // Take instance if INotifyPropertyChanged
     }
}
``

Since `Observes` will attach to `PropertyChanged` event handler - will the GC still be able to collect `ViewModel` even thought they reference each other since the `ViewModel` owns the command?

Just happy to learn new things :)

**Comment by noufionline** [comment]
@joacar In my viewModel I always have properties within the scope of the viewmodel itself. So like @briannoyes suggested it would be ideal to implement this features.

In my case I am enabling a save button based on whether an entity is valid or not. and that validation is happening every time a property changes inside the Entity.

with the current implementation I am forced to do like this.

`  public DeliveryNote Entity
{
	get { return _entity; }
	set
	{
		_entity = value;
		INotifyPropertyChanged propertyChanged = Entity as INotifyPropertyChanged;
		if (propertyChanged != null)
			propertyChanged.PropertyChanged += (e, s) =>
			{
				SaveCommand.RaiseCanExecuteChanged();
			};
	}
}`

**Comment by briannoyes** [comment]
@joacar in your example, yes you would leak the reference because of Current being static. But that would true with any event subscription on a static object... one of the many reasons statics (globals) are evil. I avoid them like the plague for this reason and because they also create havoc if you are trying to unit test the code.

**Comment by joacar** [comment]
@briannoyes Got it thanks! I have some apps where I've registered the implementation of `ISettings` as singleton and have it injected and I guess this as well would introduce leakage..

**Comment by brianlagunas** [comment]
I did intentionally leave this out because during my initial attempt at supporting this, I found managing the lifetime of the objects too complicated.  I could not detect when the instance property was set to a new instance and therefore unhook the previous and hook into the new instance.  Not to mention, what happens when you start trying to do Person.Address.Street.  So by adding this we are also opening a can of feature worms.

@briannoyes, or anyone else for that matter, if you have any ideas to simplify this I would love to hear them.

**Comment by nickkazepis** [comment]
This might be a totally different subject but I'm going to give it a try anyway since I'm not 100% sure it goes off scope of this suggestion. I would like to be able to observe properties of the object being passed as the DelegateCommand's argument. For example, I could declare a DelegateCommand<CustomType> which takes a CanExecute and an Execute both with an argument of type <CustomType> that they can work on, however I would like to be able to observe a property of that argument to refresh the CanExecute. For example ... new DelegateCommand<CustomType>(..., ...).Observes( (CustomType ct) => ct.Property );

Finally, I have two more questions, why pressing a button which binds to a command does not refresh the CanExecute of the button? I end up pressing the button, nothing happens because the CanExecute returns false but the button does not get deactivated until I explicitly call RaiseCanExecuteChanged().

And Secondly why all those anonymous lambda while passing arguments to the base constructors and why ``` protected readonly Func<object, Task> _executeMethod;``` has been made readonly?

**Comment by brianlagunas** [comment]
I think you are trying to turn the ObservesProperty feature into something is was not meant to be.  It is not meant to be a generic observer that can observe anything passed in.  It is meant to observe properties that have been defined within the VM.  If you want to just observe anything, then there are other observer patterns available to you.

Because the Xamarin.Forms Button class does not raise ICommand.CanExecuteChanged when you click on it.  Actually no button in any XAML platform does, and it probably shouldn't.

Those lambas are needed in order for the DelegateCommand to work.  And that variable is readonly because it can only be set once.

**Comment by brianlagunas** [comment]
Just an update.  Support for nested properties has been added in the latest code base.  Should be available in the next major release

**Comment by noufionline** [comment]
Great 👍 news Brian. Thanks a lot!
When can tentatively expect the major release? Just a rough estimate will do.

**Comment by brianlagunas** [comment]
Not sure.  We are working on a number of large features including .NET Standard support.  I also have some travel coming up.  Hopefully a couple of months.  We will be releasing previews more frequently though.  So keep an eye out for those.

**Comment by ileonidmas** [comment]
Dear Brian,
are there any news about next major release?
Leo

**Comment by dansiegel** [comment]
@ileonidmas the Prism.Core and Prism.Forms packages are all available currently on our MyGet CI feed. We are working on some updates that are holding back UWP and WPF.

**Comment by ileonidmas** [comment]
Thank you! Now it works like a charm)
