### ISSUE TITLE
PlatformInitializer called to late

### ISSUE THREAD

**Issue by dersia** [PrismLibrary/Prism#771]
So this maybe just a problem for but I wanted to ask if there is a reason why "_platformInitializer?.RegisterTypes(Container);" is called after "RegisterTypes();"?

I have a SQLite implementation that is registered platform-wise, but my Repositories are registered in the my "SharedApplication" pcl.

But since the registration of the platform services are done after the application ones unity is failing.

I could use a module for that though, since the registrations of the modules is done afterwards, but I wanted to ask first.

**Comment by brianlagunas** [comment]
This is so that your platform specific services can utilize the services from the PCL.  All navigation then occurs after all types have been registered so that VM's can utilize all services with no issues.  This tells me you are trying to resolve an instance of a service before all types have been registered.

**Comment by dersia** [comment]
You are totally right. I think it was a bit late yesterday evening... Sorry for that!

**Comment by mikegottlieb** [comment]
@brianlagunas I understand your comment, but I'm wondering how this ordering makes sense when registering instances rather than just types. Should I be registering instances somewhere other than in RegisterTypes?

My scenario is that my platform specific code creates an instance of the object that manages session/authentication information. This is because it has to interact with device specific secure storage. My PCL has my API client that utilizes my session/authentication object.

The same is true for my logging, telemetry, geolocation, and push notifications managers. All need platform specific implementations, but are utilized by common code in the PCL. Prior to updating to Prism 6.2 I did my own implementation for registering platform specific types before shared types in my bootstrapper. My common code was able to call Resolve to get the instance registered by the platform specific code and pass that to new singletons that it was constructing and registering.

What is the intended way to handle this scenario in Prism 6.2?

**Comment by brianlagunas** [comment]
You would use the IPlatformInitializer to register your types in the specific platform projects.

**Comment by mikegottlieb** [comment]
@brianlagunas I understand that, but what about registering instances that depend on each other? It might be clearer with code.

Here is my initializer:
```
public class iOSInitializer : IPlatformInitializer
	{
		public void RegisterTypes(IUnityContainer container)
		{
			container.RegisterInstance<ILogManager>(LogManager.Instance);
			container.RegisterInstance<IPlatformInfo>(new PlatformInfo());
			container.RegisterInstance<ISessionProvider>(new SessionProvider());

			TelemetryService telemetryService = new TelemetryService();
			telemetryService.Configure();
			container.RegisterInstance<ITelemetryService>(telemetryService);

			LocationProvider locationProvider = new LocationProvider(telemetryService);
			container.RegisterInstance<ILocationProvider>(locationProvider);

			container.RegisterInstance<INotificationsService>(new NotificationsService());
			container.RegisterInstance<ITripLoggingReminder>(new TripLoggingReminder());
			container.RegisterInstance<INativePlacesApi>(new NativePlacesApi(locationProvider));
		}
	}
```

And here is the RegisterTypes implementation in my PrismApplication

```
protected override void RegisterTypes()
		{
			this.SessionProvider = this.Container.Resolve<ISessionProvider>();
			this.LocationProvider = this.Container.Resolve<ILocationProvider>();
			this.TelemetryService = this.Container.Resolve<ITelemetryService>();
			this.NotificationsService = this.Container.Resolve<INotificationsService>();

			ILogManager logManager = this.Container.Resolve<ILogManager>();
			IPlatformInfo platformInfo = this.Container.Resolve<IPlatformInfo>();

			this.StatsProvider = new StatsProvider(logManager);
			this.Container.RegisterInstance<StatsProvider>(this.StatsProvider);

			ApiClient client = new ApiClient(platformInfo, this.SessionProvider, logManager);
			this.Container.RegisterInstance<ApiClient>(client);

			this.AuthenticationService = new AuthenticationService(client, this.SessionProvider,  this.TelemetryService, logManager);
			this.Container.RegisterInstance<AuthenticationService>(this.AuthenticationService);
			this.AuthenticationService.Initialize();

			this.Container.RegisterTypeForNavigation<NavigationPage>();

			this.Container.RegisterTypeForNavigation<HomeView, HomeViewModel>();
			this.Container.RegisterTypeForNavigation<MasterDetailHomeView, MasterDetailHomeViewModel>();
}
```

As you can see the platform code needs to register a number of singletons that are used by singletons in the shared code. The singletons in the shared code cannot be constructed without retrieving the platform specific singletons first. That is not possible because the platform specific RegisterTypes method is called 2nd.

Is there a different way to do this that is supported? I understand that the current implementation allows you to use services from the PCL in the platform specific code and how that might be useful. However, the reason I use Xamarin Forms is so that I can do minimal work in the platform specific realm. I tend to build small isolated components to use to interact with platform specific APIs and then surface those up to the common code. That means that most of my platform specific types have few dependencies to inject, but my PCL ones depend on all of those platform specific types.

**Comment by brianlagunas** [comment]
Why are you resolving objects and setting properties in a method meant for registering types?  Set your properties in OnInitialized after all your types have been registered. Also, only set properties if you need to use them in the actual App.cs.  If you are creating them just to pass into a ctor of a class to create, you're doing it wrong.  Use the DI container to your advantage.  As long as all of your types are property registered, you do not have to manually pass in any of the dependencies at all.  The container will create them for you, no matter how nested the dependency tree is.  You should rarely have to call `Container.RegisterIntance`.

**Comment by mikegottlieb** [comment]
I was using the RegisterTypes step to register instances simply because of the similarity in naming convention and duty of "registering" things. I hadn't seen any documentation that suggested a more appropriate home.

I am setting those properties in App.cs because they are used in App.cs. For other services that I don't use in App.cs I don't hold a reference in a property and I just use DI.

I don't think it is weird to be using RegisterInstance. I have about 20 or so singletons in my application. These are objects that communicate with different APIs whether they be on my servers or in different libraries on the phone. Since they are singletons calling RegisterInstance is how I make sure that only one instance is used through all of my ViewModels. Having multiple instances of these objects would be both expensive and dangerous. This is why the RegisterInstance method exists.

I think what you are trying to say is that RegisterTypes should only be used to register types that are created by the container and that OnInitialized is the place to create singletons and register them. That is fair and that was what I was trying to understand about the design of Prism.

When you responded to @dersia earlier you said

> This is so that your platform specific services can utilize the services from the PCL.

I was confused because my "services" are all singletons and are therefore registered via calls to RegisterInstance. When I read your response I thought you had made the decision that it was more common to implement a service in the shared code and utilize it in the platform code. That was interesting to me because my code tends to work in the opposite direction and it has felt really natural to do it that way.

So it seems like the right way for me to accomplish what I need is similar to what I used to do. During initialization I need my common application to tell my platform specific code to new up its singletons and register them to the container. That should be easy to whip together.

Thanks for the clarification!

**Comment by brianlagunas** [comment]
I personally never use `RegisterInstance` to register singletons except in rare cases.  I would always recommend using `RegisterType<TFrom,TTo>(new ContainerControlledLifetimeManager());`  That also registers objects as singletons and is lot less work than manually creating objects and passing in parameters via the ctor.  I always use `Container.Resolve` to create the objects and not manually new them up.

Though you do bring up a good point regarding the direction of dependencies.  After thinking about it more, I believe the IPlatformInitializer.RegisterTypes should be moved before the PrismApplication.RegisterTypes since the PCL will be using types from the platform project heads and not the other way around.  This will be an easy fix for the 6.3 release.

**Comment by dersia** [comment]
I agree with Brian, I would also use the `ContainerControlledLifetimeManager` for singletons. I often even often use a InjectionMember (Factory most of the times) to create my instance, if it is really needed.

But I disagree with: 
> ...since the PCL will be using types from the platform project heads and not the other way around.

I think there are cases where it's the other way around. When it comes to instance-registrations, you'll never now what they're depending on. 

As an example, you could have a register logging for ILoggingFacade and you might want to use it in the platform specific part. If this part is an instance-registration it would fail upon resolving.

There is no solution for all, we just have to agree to a direction and be aware when designing the architecture of the app.

BTW: with the PlatformInitializer-contructor it happend a few times for me, that navigation in OnInitialized failed, because the InitializeComponents was called inside the contructor and the constructor is called after OnInitilized. Is there a better way then calling an OnAfterInitlized-method from within the constructor?

**Comment by brianlagunas** [comment]
@dersia no, you must call InitializeComponent in the OnInitialized method right before navigating. Essentially, you will not be using the ctor of the application in a Prism application.

**Comment by mikegottlieb** [comment]
I was not aware of the `ContainerControlledLifetimeManager` thanks for the tip.

Unfortunately I think there is no perfect answer for the direction of dependencies issue and agree that it is best to pick a direction and design around the constraint. I kind of hit this not in Prism/Unity relating code, but in app startup. To use just iOS as an example my AppDelegate does some work to initialize itself and create my PrismApplication, then my PrismApplication is created and does some initialization, then it has to call back into my AppDelegate for some more platform specific work that utilizes parts of the PrismApplication.

I do it through events and delegates to avoid hard coupling, but it still isn't pretty. I'm hoping to eventually clean it up.

**Comment by dersia** [comment]
@mikegottlieb your architecture sounds really interesting. If you have some spare time, could you please make a sample and upload it? I'd really be interested in seeing it :)

**Comment by mikegottlieb** [comment]
lol to me it seems like it needs to be cleaned up. I'll try to put something together.

**Comment by mikegottlieb** [comment]
I don't have a sample ready yet, but I finally worked around the main issue I was trying to address that prompted me to upgrade to Prism 6.2 and I thought it might be worth sharing what I did because you either know a better way or want to take this case into consideration for future support.

I develop a Xamarin Forms app that runs on iOS and Android. My app makes use of geofences which means it does background work. iOS and Android have very different takes on background execution. On iOS everything is easy because your whole application will be started if a background event takes place. Therefore I know that my services are all initialized and ready for use.

Android presented problems. Xamarin Forms is designed around having a single `Activity` and that is meant to be the home of your initialization code, but that doesn't work for background scenarios because the activity won't be launched. I thought Prism would help and I would be able to create my `PrismApplication` in the background, but that failed because I wasn't calling `Xamarin.Forms.Forms.Init()`. That call is required and it takes both a `Bundle`, which I didn't have, and the `Context` of the current `Activity`, however no `Activity` was launched.

So I built a singleton that I named `ServiceStack`. My `ServiceStack` creates the `IUnityContainer`. Then it has a method called `RegisterServiceTypes(IPlatformInitializer initializer)` that registers common services and calls RegisterTypes on the `IPlatformInitializer`. I call this method before constructing my `PrismApplication` and I don't pass an `IPlatformInitializer` to my `PrismApplication` anymore. The last bit was that I overrode `CreateContainer` in my `PrismApplication` to return the container of the `ServiceStack`. That way when the rest of the `PrismApplication` code runs to register views and initialize my application it all uses the same container.

After doing that I was able to construct and initialize my `ServiceStack` in all of my Android background entry points and call the code I needed.

It works, and it isn't the ugliest thing I've ever seen but it does depend on a singleton that lives outside of the UnityContainer. If you guys have any feedback I would really appreciate it. When I have a second to breathe I'll put together a sample.

**Comment by kylewarren** [comment]
@brianlagunas did this happen in 6.3?

"Though you do bring up a good point regarding the direction of dependencies. After thinking about it more, I believe the IPlatformInitializer.RegisterTypes should be moved before the PrismApplication.RegisterTypes since the PCL will be using types from the platform project heads and not the other way around. This will be an easy fix for the 6.3 release."

**Comment by dansiegel** [comment]
@kylewarren 6.3 has already been released

**Comment by dansiegel** [comment]
@kylewarren sorry misread your question... 

you can see [PrismApplicationBase](https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/PrismApplicationBase.cs#L73), we are still calling the `RegisterTypes` before the `IPlatformInitializer.RegisterTypes`

**Comment by kylewarren** [comment]
Ok thanks for update!
