### ISSUE TITLE
Getting exception like System.InvalidCastException: Specified cast is not valid on Prism.Commands.DelegateCommandBase.CanExecute

### ISSUE THREAD

**Issue by ShahriatHossain** [PrismLibrary/Prism#799]
Hi, 
I am using Prism 6.1.10 and Xamarin.Forms 2.3.2 here. When I select an item from the ListView I am getting the exception like below only for iOS project but Droid project is working good:

{System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) 
System.Object:__castclass_with_cache (object,intptr,intptr)
  at Prism.Commands.DelegateCommand`1+<>c__DisplayClass1_0[T].<.ctor>b__1 (System.Object o)
 [0x00000] in <filename unknown>:0 
  at Prism.Commands.DelegateCommandBase.CanExecute (System.Object parameter) [0x00000] in <filename unknown>:0 
  
at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.CanExecute (System.Object parameter) [0x00000] in <filename unknown>:0 
  
at Uno.Behaviors.EventToCommandBehavior.OnEvent (System.Object sender, System.Object eventArgs) 

And here is my code snippet both for xaml and viewmodel:

```
<ListView ItemsSource="{Binding List}" x:Name="ListView">
      <ListView.Behaviors>
        <behav:EventToCommandBehavior EventName="ItemSelected" Command="{Binding DetailCommand}" CommandParameter="{Binding SelectedItem, Source={Reference ListView}}" />
      </ListView.Behaviors>
      <ListView.ItemTemplate>
        <DataTemplate>
          <ImageCell ImageSource="{Binding Logo}"
               Text="{Binding Name}" />
        </DataTemplate>
      </ListView.ItemTemplate>
    </ListView>
```

```
public DelegateCommand<ItemModel> DetailCommand { get; set; }
DetailCommand = new DelegateCommand<ItemModel>(NavigateToItemDetail);
private async void NavigateToItemDetail(ItemModel paramItem)
        {
           
        }
```

Can anybody tell me what I am doing wrong here? Why it is only working on my Droid project but not for iOS project?

**Comment by brianlagunas** [comment]
There was never a Prism 6.1.1, maybe you mean Prism 6.2.0 which is the most current version?  Also, this issue is not related to Prism as this appears to be a simple binding issue with Xamarin.Forms.  My Mac has stopped working so I am unable to test this.  You should start by slowing removing various bindings and see what the cause is.  Chances are this is a Xamarin.Forms issues, and should be reported to them.  I have a suspicion that is you remove the CommandParameter binding it would work.  THat's just a guess though.
