### ISSUE TITLE
IInteractionRequestAware: change FinishInteraction property to event handler

### ISSUE THREAD

**Issue by YehudahA** [PrismLibrary/Prism#82]
Because prism 6 has breaking changes, maybe this is an opportunity to make another change:

The currently definition of IInteractionRequestAware interface is:
``` cs
public interface IInteractionRequestAware
{
    Action FinishInteraction { get; set; }
    INotification Notification { get; set; }
}
```

And I suggest to change it to:
``` cs
public interface IInteractionRequestAware
{
    EventHandler FinishInteraction { get; set; }
    INotification Notification { get; set; }
}
```

The using of FinishInteraction as a property is quite strange: The programmer should not set this property, because the prism service set it. So, why it's defined as a property? in fact, it is an event.

**Comment by briannoyes** [comment]
We intentionally did not use EventHandler because doing so implies that the UI is passing a reference to itself (the object sender argument) to the ViewModel, which if used breaks the separation intentions of the MVVM pattern. And EventArgs is a useless argument in this case as well, so Action was a cleaner definition of what was needed - simply a poke to say the UI interaction is done. It was defined as a property because again an event requires an object reference to the thing that exposes the event - more coupling that goes counter to the MVVM pattern.

**Comment by YehudahA** [comment]
Brian, Thank you for your response, but what about:
``` cs
public interface IInteractionRequestAware
{
    public event Action FinishInteraction;
    INotification Notification { get; set; }
}
```
