### ISSUE TITLE
Optimize PopUpWindowAction to Create a new Content.

### ISSUE THREAD

**Issue by feinstein** [PrismLibrary/Prism#84]
One thing I don't like about `PopUpWindowAction` is that it will instantiate the `WindowContent` when the `View` loads and that object will sit there in memory, even if it's not in use. 

Not only this is a small memory leak in my opinion, but I also can't use the `WindowContent`'s `Constructor` like I would regularly, since it will be called just once, and not every time this content is shown (instead I have a setup method that is called everytime the `Notification` is set, but sometimes I would rather a constructor, specially for reusing old code).

So I came up with a solution that might cover most cases, and I would like to hear your opinions on this:

Instead of holding the `WindowContent` object itself, `PopUpWindowAction` could hold the `WindowContent` Type. This way, the constructor can be invoked using something like this:

    Activator.CreateInstance(this.WindowContent.GetType());

The only problem I see in this case is if the `PopUpWindowAction` is used with a `WindowContent` that had any `Properties` changed by external code, but since this is supposed to get a reference there in xaml in most scenarios, I don't think this sould be a problem.

Also, both ways of operations can be provided, if the user sets the `WindowType`, it creates based on Type, if it doesn't, it goes normally as it is right now.

I am willing to do this modification to the library myself, but first I want to know the general opinion of the community, so I won't jump to code something that maybe goes against some architecture decision and won't be approved by the bar.

**Comment by brianlagunas** [comment]
You're assuming that WindowContent will always be a custom class.  A lot of times it's just a simple inline declaration of elements.  Also, this would introduce side effects such as trying to create the provided type when the request to show the Window is made, which causes delays due to the various logic and size of the element trying to be created.  Even then, the constructor would still only be invoked once.  Otherwise you are suggesting recreating the object every time it is shown.  Which would not be recommended.  If you have already created the necessary object, why destroy it and keep recreating it just for the sake of getting the constructor to fire each time it is shown?  Now this would most definitely increase your memory consumption as multiple copies of the same object type are being created and stored until the GC decided to clean them up.

This is not a memory leak in any sense of the term.  When the view is collected, the WindowContent is also collected which in turn frees up the memory that was allocated for those elements.  I see no benefit in providing this capability.

**Comment by feinstein** [comment]
Yes, you are right, I was assuming it was a custom class, that's how I do it, with a custom `UserControl`, I didn't realize some people will actually inline it.

And yes, I expressed myself wrongly, I didn't meant a memory leak on the true meaning of the technical term, I meant having an object in memory that might never be used. For example, if the program has a `Setup Window`, or any other kind of `Window` that the user might just not use at all, this `Window` will be sitting there in memory, quietly, taking memory space as long as the program lives, and the user might never even use it. That was my particular case, I have some 5 windows, that the user might never use, and they are all created when the `Main View` is created, since they will all popup from the `Main View`.

So I guess this is more a matter of project architecture, some projects will benefit more from a `Window` that has it's contents only created once, some will benefit from having them created when needed (or at least created once, but only when needed).

**Comment by brianlagunas** [comment]
It sounds like you should be using a dialog service rather than the PopUpWindowAction.

**Comment by feinstein** [comment]
Yes it does, I am coding one myself now, but I didn't find many good examples online, most are too much for what I need, any good examples are most welcome :) .
