### ISSUE TITLE
[readme] add an explicit mention of Xamarin.iOS and Xamarin.Android support

### ISSUE THREAD

**Issue by dodikk** [PrismLibrary/Prism#841]
It's not quite clear whether it is possible to use prism in Xamarin apps based on UIKit or native UI frameworks of other platforms. 

It would be nice to have an explicit statement on that in the readme. As well as a mention about this feature presence in a roadmap (if any).

**Comment by brianlagunas** [comment]
I would assume since the first sentience in the ReadMe explicitly states "Xamarin Forms", all docs reference Xamarin.Forms, the NuGet packages are post fixed with ".Forms", and there is no mention of Xamarin.iOS, Xamarin.Android, UIKit or native UI frameworks that it would be quite clear that Xamarin is not a target for Prism.
