### ISSUE TITLE
Navigation between tabbed pages in XF

### ISSUE THREAD

**Issue by beylkhanovdamir** [PrismLibrary/Prism#856]
I have Tabbed main page with 2 children tabs with attached viewmodels. 
When I'm trying to click on Catalog tab page, OnNavigatedTo event in attached viewmodel is not firing , but Catalog tab page is appeared

How can I switch between tabs and OnNavigatedTo event is fired?

**CatalogPageViewModel**:

`public class CatalogPageViewModel : ViewModelBase
	{
...
	public override void OnNavigatedTo(NavigationParameters parameters)
		{
			base.OnNavigatedTo(parameters);
			// not firing
		}
...
}

`

**App.xaml.cs**:

protected override void RegisterTypes()
		{
			Container.RegisterTypeForNavigation<CatalogPage,CatalogPageViewModel>(nameof(CatalogPage));
			Container.RegisterTypeForNavigation<HomePage, HomePageViewModel>(nameof(HomePage));
		}

**HomePage**:

<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:views="clr-namespace:merchandise_app.Views;assembly=merchandise_app"
             xmlns:mvvm="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             xmlns:behaviors="clr-namespace:Corcav.Behaviors;assembly=Corcav.Behaviors"
             x:Class="merchandise_app.Views.HomePage" mvvm:ViewModelLocator.AutowireViewModel="True">
	<TabbedPage.Children>
		<NavigationPage Title="Dashboard" Icon="dashboard.png">
			<x:Arguments>
				<views:DashBoardPage></views:DashBoardPage>
			</x:Arguments>
		</NavigationPage>
		<NavigationPage Title="Catalog" Icon="catalog.png">
			<x:Arguments>
				<views:CatalogPage></views:CatalogPage>
			</x:Arguments>
		</NavigationPage>
	</TabbedPage.Children>
</TabbedPage>

**Comment by lhughey** [comment]
I'm having the exact same issue as you are.  It looks like we may be using different versions of the XF Prism, or using your own base class. I'm posting some code below, since we are doing slightly different things, but are having the same results.

Upon starting the app, I'm simply loading the TabbedPage, which displays the ViewA.  I'm browsing to ViewB, via the tab, and back to ViewA.  None of the navigating methods within ViewA or ViewB are being triggered when navigating from the tabs.  However, navigating from a command (like from a button) is triggering the commands are expected.  

**App.xaml.cs** 
`
await NavigationService.NavigateAsync("MainTabbedPage", animated: false);
//MainTabbedPage, ViewA and ViewB are registered for Navigation
`
**MainTabbedPage**
`        <NavigationPage Title="ViewA">
            <x:Arguments>
                <local:ViewA Title="ViewA"/>
            </x:Arguments>
        </NavigationPage>
        <NavigationPage Title="ViewB">
            <x:Arguments>
                <local:ViewB Title="ViewB"/>
            </x:Arguments>
        </NavigationPage>`

**ViewA**
`public class ViewAViewModel : BindableBase, INavigationAware
    {
 public void OnNavigatedFrom(NavigationParameters parameters)
        {
           Debug.WriteLine("No Soup");
        }

        public void OnNavigatedTo(NavigationParameters parameters)
        {
            Debug.WriteLine("No Soup");
        }

        public void OnNavigatingTo(NavigationParameters parameters)
        {
            Debug.WriteLine("No Soup");
        }
}`

**Comment by brianlagunas** [comment]
One thing to realize is that switching tabs is not a navigation operation and would not call the INavigationAware interfaces.

If you want to call the INavigationAwar emethods when you first navigate to the TabbedPage, ou must include the default page in your navigation URI.

`_navigationService.NavigateAsync("MyTabbedPage/SelectedTab");`

As far as tab selection goes, we are working on solution in issue #650 .  I am closing this as a duplicate, you can follow the status of issue #650.

**Comment by lhughey** [comment]
Thanks for the quick response Brian and the great work with Prism.  I'll follow issue 650.  It looks like someone posted a workaround that is said to work until you've worked the fix into a release.
