### ISSUE TITLE
[XF] Call IDestructible when using an absolute URI

### ISSUE THREAD

**Issue by brianlagunas** [PrismLibrary/Prism#862]
While the addition of the IDestructible behavior is great, is does not work when using an absolute URI to reset the navigation stack.  I have not been able to reliably traverse the navigation stack in order to call the interface methods during this navigation scenario.  I need to figure this out.  This will most likely need to be done on line 178 of the PageNavigationService just before the call to DoPush.

**Comment by nuitsjp** [comment]
I made it with your idea.
However, there are some problems.

1. I have problems with Mock and I can not write test cases
In Xamarin.Forms ModalStacks are shared.
PushModalAsync -> PushAsync -> PushAsync -> PushModalAsync
In this case Xamarin.Forms, Page.Navigation.ModalStack.Count of all Page is 2.
But Prism 's Mock does not work anymore.
Unfortunately, we need to manipulate the Internal property.
It is necessary to rely on Reflection, this is not beautiful.
But if need testing, there is no other way.

2. NavigationPage children are not in good order of calling
NavigationPage> PageA> PageB
At this time, Destroy is now called in the following order.
PageA> PageB> NavigationPage
The next one should be better.
PageB> PageA> NavigationPage

In response to this problem, I would like to make the following changes
1. Fix Mock so that NavigationStack works properly (using Reflection)
2. Prepare a mechanism that can store the order of issue of Navigation Events
3. Fix the Destroy problem of NavigationPage

Can I tackle these problems?
For now, I will send you the RP of the code that will work with the title problem.

**Comment by brianlagunas** [comment]
Yes, I would like to see your solution.

**Comment by nuitsjp** [comment]
I have discussion.
Currently, the processing order of events.
1. OnNavigatingTo
2. Destroy
3. OnNavigatedFrom
4. OnNavigatedTo

Setting BindingContext to null in Destory
For this reason, OnNavigatedFrom of ViewModel is not called.
Is this appropriate?

https://github.com/nuitsjp/Prism/blob/fix-call-idestructible-when-using-an-absolute-uri/Source/Xamarin/Prism.Forms.Tests/Navigation/PageNavigationServiceFixture.cs#L248

**Comment by brianlagunas** [comment]
No. When going back, the order is 

Hardware/software button:
1. OnNavigatedFrom (Source)
2. OnNavigatedTo (Target)
3. Destroy (Source)

Calling GoBackAsync
1. OnNavigatingTo (Target)
2. OnNavigatedFrom (Source)
3. OnNavigatedTo (Target)
4. Destroy (Source)

Also, I do not want to create our own INaviagtion to replicate the XF navigation stack.  We must depend on the XF navigation functionality.  Otherwise our tests are not accurate.  If we have a custom INavigation that works properly, but the XF navigation is broken we will not know there is an issue.

**Comment by nuitsjp** [comment]
Fixed event order when absolute navigation.
And, removed INavigation implementation class.

I gave up emulating the behavior of NavigationStack.
In order to emulate without implementing INavigation, UI Test is necessary.
Because Xamarin.Forms uses the Platform class.
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/Platform.cs

Instead, I created a method that calls all the Destories of Page contained in ModalStack this time.
https://github.com/nuitsjp/Prism/blob/fix-call-idestructible-when-using-an-absolute-uri/Source/Xamarin/Prism.Forms/Common/PageUtilities.cs#L77

Finally, it was necessary to record the execution order of the events.
For this reason, disabled execution on multithreading of tests.
