### ISSUE TITLE
[XF] Handling parameters in OnNavigatingTo breaks GoBack

### ISSUE THREAD

**Issue by gmwilhelm** [PrismLibrary/Prism#873]
### Package info

- Platform: Xamarin.Forms
- Prism version: 6.3.0-pre1
- Xamarin version (if applicable): 2.3.3.175

### Repro steps

App with 3 pages: Mainpage, PageA, PageB

NavigateAsync from MainPage to PageA with a parameter, handle parameter in PageA OnNavigatingTo
NavigateAsync from PageA to PageB
GoBackAsync from PageB to PageA

Result: OnNavigatingTo of PageA is executed, but PageB is still displayed

When i remove the handling of the parameter in PageA OnNavigatingTo, it works correct.
It also works correct if i add parameters in PageB GoBackAsync.

See attached zip file for an example app

[GoBackTestApp.zip](https://github.com/PrismLibrary/Prism/files/643639/GoBackTestApp.zip)

**Comment by brianlagunas** [comment]
Without even looking at the sample I can probably guess that you aren't checking for the existence of a parameter before you try to read it which is causing an exception.

You probably have a single line of code like this: `string p = (string)parameters["key"];`

What you should have is:
```
if (parameters.ContainsKey("key"))
{
    string p = (string)parameters["key"];
}
```

**Comment by gmwilhelm** [comment]
Thanks Brian, you are correct.

But i still have two questions about this:

1. in OnNavigatedTo the single line works, without checking for a parameter first,
2. if there is an exception, why does the app still run? Is the exception catched in the prism code?

**Comment by brianlagunas** [comment]
1. You get an exception any time you try to get a value from a dictionary and it doesn't exist. It appears to work because OnNavigatedTo occurs **after** navigation has occurred, while OnNaviatingTo happens **before** navigation occurs. Since the exception happens before navigation, it will not change pages.
2. Yes, it is handled in the navigation service so the app doesn't come crashing down because the developer didn't check for the existence of keys before accessing them :)

**Comment by dansiegel** [comment]
It's worth noting that exceptions caught by the NavigationService are logged with ILoggerFacade. If you haven't registered a custom implementation, by default it uses ```System.Diagnostics.Debug.WriteLine``` so it should be in the output in VS/XS.
