### ISSUE TITLE
Prism.Wpf - RaisingRequests from non UI threads

### ISSUE THREAD

**Issue by buldo** [PrismLibrary/Prism#878]
If raise InteractionRequest from non UI thread InvalidOperationException will be fired.

Maybe InteractionRequest will able to check current thread an raise event only on UI thread?

**Comment by dvorn** [comment]
@buldo Having that incorporated into the Raise method will create problems for unit-testing.  Also, someone may want to have multiple UI threads in their applications.

On the other hand, it is easy to create an extension method for IInteractionRequest and Raise on whatever context you like.  (I did that in some apps.)

As a final note: the entire idea of raising interaction request from background thread should be taken with extreme care.  Because the background thread is not synchronized with UI thread and in general does not know what UI is doing at the moment.  For instance, you may attempt to raise a dialog while the user is having OpenFileDialog open.

May be a better approach would be to signal the UI thread from the background thread that something happened and then have the UI thread decide what to do depending on the UI state.

**Comment by briannoyes** [comment]
Agree with @dvorn this would add too much complexity to a mechanism that is already more complex than I would like.

If you need to trigger showing a dialog to a user from a background thread, I would recommend firing a PubSubEvent from the background thread and subscribe with ThreadOption.UIThread and have the handler trigger the dialog.

**Comment by ronnieoverby** [comment]
This might help someone with this issue:

```c#
public static void Exec(this IEventAggregator events, Action action, ThreadOption threadOption = ThreadOption.UIThread)
{
    var e = events.GetEvent<ExecMessage>();
    ExceptionDispatchInfo exception = null;

    using (var waitHandle = new ManualResetEventSlim())
    {
        Action<ExecMessage> handleMessage = msg =>
        {
            try
            {
                msg.Action?.Invoke();
            }
            catch(Exception ex)
            {
                exception = ExceptionDispatchInfo.Capture(ex);
            }
            finally
            {
                waitHandle.Set();
            }
        };

        using (e.Subscribe(handleMessage, threadOption))
        {
            e.Publish(new ExecMessage { Action = action });
            waitHandle.Wait();
            exception?.Throw();
        }
    }
}

private class ExecMessage : PubSubEvent<ExecMessage>
{
    public Action Action { get; set; }
}

```

It's general purpose, but for the issue of NotificationRequests use it like:

```c#
private void RaiseNotification(string title, object content) =>
    _events.Exec(() => NotificationRequest.Raise(new Notification { Title = title, Content = content }));

```
