### ISSUE TITLE
XF: Choppy navigation from page without to page with navigation header

### ISSUE THREAD

**Issue by hardcodet** [PrismLibrary/Prism#879]
My app's home page doesn't have a navigation header, and when navigating to another page that does have one, the following happens:

* The navigation header of the new page is being displayed on top of the old content.
* The old content is accordingly moved down, which is a rather choppy business.
* The new page's content is being displayed as a replacement of the old content.

While a small thing, the delay is extremely noticable and makes the app look and feel like an unfinished prototype. I tried using the new OnNavigatingTo interface to set stuff up, but that only caused the navigation header to be updated with the proper title on top of the old home page.

Not sure this can be solved by Prism, or is an issue with Xamarin Forms though.

### Package info

- Platform: XF Forms / Android
- Prism version: Latest
- Xamarin version (if applicable): 2.3.3
- Windows 10 SDK version (if applicable):
- Other version info:

### Repro steps

Have a page without a nav header, navigate to a page that has one.

**Comment by brianlagunas** [comment]
There is not enough information in your issue for me to understand what the issue really is.  Is it an issue with updating the state of a page?  Your repo steps are not sufficient to see any issues.  If your issue is that the page loads and then you notice a delay in the data being updated which results in a "choppy" experience then this is not something you can do a whole lot about.  This is the nature of data binding.  I would recommend using the OnNavigatingTo so you can prep your data prior to the page being displayed.  It is hard to tell what the root issue is as your issue is not descriptive enough.

**Comment by hardcodet** [comment]
The issue is that if you navigate from page1 to page2, and page1 doesn't have a navigation header, then the navigation header of page2 is being displayed on top of the content of page1 for like half a second until page2 is loaded. As mentioned, OnNavigatingTo doesn't make a difference.

I think it's a Xamarin issue though, there's a similar bug open for XF on iOS.

**Comment by brianlagunas** [comment]
Yeah, that's definitely not something Prism even has access to or can manipulate.
