### ISSUE TITLE
[XF] Back button doesn't show when using master detail and tabbed pages

### ISSUE THREAD

**Issue by powerdude** [PrismLibrary/Prism#892]
### Package info

- Platform: UWP
- Prism version: 6.2
- Xamarin version (if applicable):
- Other version info:

### Repro steps
If the sample HelloWorld project is updated so that the CommandParameter for either of the buttons is "MyNavigationPage/MyTabbedPage", and then you click on the button on either tabs, the back button won't show and the menu is unavailable.  I think the menu going away is a Xamarin bug though and i've reported that.

**Comment by brianlagunas** [comment]
This is because it is navigating modally.  You need to set the `useModalNavigation = false` in order to navigate from within  a child ContentPage that is in a TabbedPage, that is wrapped in a NavigationPage that is being used as the Detail of a MasterDetailPage.  See how things start to get complex :)

**Comment by powerdude** [comment]
hi @brianlagunas ,

thanks.  I didn't realize that not specifying useModalNavigation would default to true.  Seems a bit counter-intuitive since nullable booleans would default to false.

**Comment by brianlagunas** [comment]
It's not about what the default value of a nullable type is, it's about the expectations of the platform.  XF default expected navigation is modal.  While the Prism INavigationService tries it's best to be smart about handling the navigation, there are certain scenarios in which it simply falls back to the platform expectations.  This just happens to be one of those scenarios. That's why the parameter exists so that you can override it's behavior.
