### ISSUE TITLE
Projects not buildable on Windows 10 

### ISSUE THREAD

**Issue by Rhywden** [PrismLibrary/Prism#91]
Subject title should be sufficient - VS 2015 complains that the SDK for the repo's files is not compatible to the release version of the SDK.

Also, might I humbly suggest that taking a vacation right around the corner of a _major_ release is not a good idea? Particularly when the landing page only states "We're on a vacation!" - but there's neither a date mentioned when this vacation started nor when it's supposed to end.

**Comment by bartlannoeye** [comment]
Check PR #90 for the code updated to the RTM SDK if you're in urgent need of a compiling version.

I'm pretty confident @briannoyes or @brianlagunas will merge (or update the solution themselves) as soon as they find the time. I know RTM is a major release, but this is still an open source project where everybody contributes on in their spare time without any renumeration and we just happen to be in the summer holiday period.

**Comment by brianlagunas** [comment]
Please remember this is an open source project in which we, as well as many other community members, contribute to in our spare time.  Spare time that we must find somewhere between our fulltime jobs, families, and other life responsibilities.  So please forgive us for not putting our family vacations on hold so that we can be ready to support Microsoft's initial RTM of Windows 10.

As @bartlannoeye pointed out, the community has already stepped up and provided a compiling version, which is awesome.  When we return from vacation, we will be merging everything into the main repo.

A big thank you to @ElementalNex, @Feinstein, and @veccie for the awesome community support.

**Comment by Rhywden** [comment]
Okay, I apologize for that.

Still, it would be nice if there was some kind of dates attached to the notice that you're on vacation - it's a bit vague.

**Comment by brianlagunas** [comment]
I don't know when Brian Noyes' vacation will end, but mine will be Aug 23rd.

**Comment by briannoyes** [comment]
Fixed
