### ISSUE TITLE
ValidatableBindableBase.SetProperty fails in .Net Native

### ISSUE THREAD

**Issue by LukeWATC** [PrismLibrary/Prism#975]
When I run my UWP Prism apps in .Net Native mode, ValidatableBindableBase's SetProperty method doesn't work. Visual Studio displays the error "RuntimeExceptionHelpers.cs not found" every time the SetProperty is called.

**Comment by NewBLife** [comment]
Are you use the release version? Maybe you need to set the Default.rd.xml . @LukeWATC

**Comment by bartlannoeye** [comment]
Weird nobody mentioned this before as this is core functionality. Do you have a small repro? I'll look into it asap.

**Comment by LukeWATC** [comment]
I've published a repro to GitHub: [https://github.com/LukeWATC/PrismIssueTest](url)

**Comment by LukeWATC** [comment]
Any updates on this issue?

**Comment by brianlagunas** [comment]
So I looked into this and there is no rhyme or reason for this error.  This can not be reproduced in a C# project.  It seems this only occurs in a VB project.  What's strange is that if you derive from BindableBase it works perfectly.  It only crashes with ValidatableBindableBase.  What's even stranger is that if you simply override the SetProperty method and don't change anything, it works just fine.
```
		Protected Overrides Function SetProperty(Of T)(ByRef storage As T, value As T, <CallerMemberName> Optional propertyName As String = Nothing) As Boolean

			Return MyBase.SetProperty(storage, value, propertyName)

		End Function
```
Unfortunately, this is one of those weird things that I have no idea what the cause is and I'm going to blame VB and .NET Native compile chain.  So you can either add the simple override or switch to use C#.
