### ISSUE TITLE
Should Prism.Forms continue to use the DependencyService

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism#982]
Currently all of the Containers (except Autofac) support the use of the `Xamarin.Forms.DependencyService` to resolve any services that it may be aware of, but that were never registered with the container. 

  - For those big on patterns, the use of the `DependencyService` does represent an Anti-Pattern as you're relying effectively on a second container.
  - For those who currently rely on this particularly for services from 3rd party libraries, this would be a breaking change.
  - If we do continue to use the DependencyService as a last ditch effort to resolve services, we would need to add this support into `Prism.Autofac.Forms`

**Comment by bartlannoeye** [comment]
_Big cheers for the Autofac implementation !_

I've been tuning down on the use of `ServiceLocator` (which is a 'similar anti-pattern') over the last year. Cutting out a dependency of that size is quite a challenge and the question is if it can completely be replaced by DI (preferably ctor, if needed property). You don't want to simply replace the `DependenyService` by the `ServiceLocator` pattern.

**Comment by brianlagunas** [comment]
I think we should drop it.  Not only is the XF DependencyService an anti-pattern, it is screwing with our WithAutoConcreteTypeResolution behaviors.  If someone want to use the XF DependencyService they have to use the IDependencyService to use it in an MVVM friendly way.  We will no longer automatically do it.

**Comment by hnabbasi** [comment]
This is something we ran into recently. Whenever we found ourselves resorting to `ServiceLocator` (XF.DependencyService), we refactored to be more MVVM friendly and because it introduced headaches when unit testing. We also wrap any 3rd party libraries to register with our Unity container for the same reason.

Personally, I think we can live without XF.DependencyService, but, I also think it might be a good idea to leave it in there as an option, for now. Prism.Forms community is growing and more developers are join in. A lot of these developers I talked to, are new to MVVM/PRISM and are coming from Xamarin-lead tutorials where they push SL heavily. Prism.Forms should be flexible to accommodate them while making them use MVVM the proper way. If you use Prism.Forms properly, you will never need XF.DependencyService, eventually we can take it out. IMO

Are folks using **AutoFac** asking for this support?

**Comment by dansiegel** [comment]
@hnabbasi I don't think anyone using AutoFac ever noticed. This was something that was uncovered when some of the tests were fixed to properly test for this capability. Version 7.0.0 will likely see all support for the XF.DependencyService removed. 

It sounds like you're following a much better pattern 👍

**Comment by brianlagunas** [comment]
We would likely keep the IDependencyService in place, but remove the auto-resolve feature of the XF DependencyService.

**Comment by brianlagunas** [comment]
I'm closing this as there is no community discussion.  For now, we will keep what we have.
