### ISSUE TITLE
RequestNavigate not working with more than 1 RegionName

### ISSUE THREAD

**Issue by kcabral817** [PrismLibrary/Prism#988]
- Platform:  WPF Windows 10
- Prism version:  6.2.0.0
- Xamarin version (if applicable):  N/A
- Windows 10 SDK version (if applicable):  N/A
- Other version info:  Visual Studio 2017.  TabGroupPaneRegionAdapter

### Repro steps
IG6:SplitPane IG6:XamDockManager.InitialLocation="DockedTop"> 
<IG6:TabGroupPane x:Name="MessageGroupPane" prism:RegionManager.RegionName="{x:Static inf:RegionNames.MessageGroupPane}">

<IG6:SplitPane IG6:XamDockManager.InitialLocation="DockedBottom"
<IG6:TabGroupPane x:Name="MainContentGroupPane"  prism:RegionManager.RegionName="{x:Static inf:RegionNames.MainContentGroupPane}">   

public class InfrastructureModule : IModule
{
    container.RegisterType<IMessageViewVM, MessageViewVM>();
    container.RegisterType<object, MessageView>("MessageView");
    regionManager.RegisterViewWithRegion(RegionNames.MessageGroupPane, typeof(MessageView));
}

private void Navigate(string uri)
{
regionManager.RequestNavigate(RegionNames.MessageGroupPane, uri);  <--- region is never set.
}

Please describe the issue/request in detail.
When the code executes, ALL views are placed in the last tabGroupPane identified in the XAML --in this case the MainContentGroupPane-- not in the requested region MessageGroupPane.

The reason that it isn't working is because the field _regionTarget never gets changed. Since TabGroupPaneRegionAdapter is shared between each of the TabGroupPanes in the application, this field never changing is the issue, as each item added will only ever go into the last added TabGroupPane's region.  

CASE NUMBER / CAS-182192-Q0L9M2 (Brian L might have access to this case)

**Comment by brianlagunas** [comment]
This is not an issue with Prism, it falls out side the scope of support on this site.  The good news is that this does work, the bad news is that the issue is in your custom region adapter and you have to find it.  You haven't provided any code or samples that run, so no one will be able to help you as this is a vey custom implementation that no one has access to.  If you narrowed the problem down to "_regionTarget never gets updated" then you need to make sure you are updating it.  This appears to be a globally scoped variable you use to track the region.  This is a bad idea since region adapters are a singleton.
